export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  SOURCE_UNAVAILABLE = 'SOURCE_UNAVAILABLE',
  SOURCE_TIMEOUT = 'SOURCE_TIMEOUT',
  SOURCE_RATE_LIMIT = 'SOURCE_RATE_LIMIT',
  SOURCE_INVALID_RESPONSE = 'SOURCE_INVALID_RESPONSE',
  PROTOCOL_ERROR = 'PROTOCOL_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED'
}
