import { ExtendedSourceDef } from './extended_sources.js';

export const ADDITIONAL_SOURCES: Record<string, ExtendedSourceDef> = {
  // ==========================================
  // 1. Frontier AI Models & Open Inference
  // ==========================================
  deepseek_ai_blog: {
    id: 'deepseek_ai_blog',
    name: 'DeepSeek AI Research',
    description: 'Frontier reasoning architectures, DeepSeek V3/R1 MoE scaling, DeepSeek-Coder, and low-cost training breakthroughs',
    enabled: true,
    protocol: 'rss',
    connector: 'deepseek_ai_blog',
    baseUrl: 'https://deepseek.com/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'llms', 'open-source-ai', 'research'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'DeepSeek AI',
    region: 'Asia',
    country: 'China'
  },
  alibabacloud_qwen: {
    id: 'alibabacloud_qwen',
    name: 'Qwen Open AI & Alibaba Cloud',
    description: 'Qwen2.5 foundation models, Qwen-VL multimodal reasoning, Qwen-Coder code generation, and open-weights releases',
    enabled: true,
    protocol: 'rss',
    connector: 'alibabacloud_qwen',
    baseUrl: 'https://qwenlm.github.io/blog/index.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'llms', 'open-source-ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Alibaba Cloud Qwen Team',
    region: 'Asia',
    country: 'China'
  },
  moonshot_ai_kimi: {
    id: 'moonshot_ai_kimi',
    name: 'Moonshot AI & Kimi',
    description: 'Long-context LLM architecture, million-token context reasoning, and multimodal agentic intelligence',
    enabled: true,
    protocol: 'rss',
    connector: 'moonshot_ai_kimi',
    baseUrl: 'https://moonshot.cn/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'llms'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Moonshot AI',
    region: 'Asia',
    country: 'China'
  },
  vllm_project_blog: {
    id: 'vllm_project_blog',
    name: 'vLLM Project & PagedAttention',
    description: 'High-throughput LLM inference, PagedAttention memory management, chunked prefill, and multi-GPU tensor parallel serving',
    enabled: true,
    protocol: 'rss',
    connector: 'vllm_project_blog',
    baseUrl: 'https://blog.vllm.ai/feed.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'llms', 'open-source-ai', 'ai-hardware'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'vLLM Project Team',
    region: 'Global',
    country: 'United States'
  },
  llama_cpp_news: {
    id: 'llama_cpp_news',
    name: 'llama.cpp & GGUF Local Inference',
    description: 'Raw C/C++ LLM inference, GGUF quantization formats, Metal and CUDA acceleration, and ultra-lightweight edge computing',
    enabled: true,
    protocol: 'rss',
    connector: 'llama_cpp_news',
    baseUrl: 'https://github.com/ggerganov/llama.cpp/releases.atom',
    authType: 'none',
    categories: ['ai', 'llms', 'open-source-ai', 'programming'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Georgi Gerganov & llama.cpp Community',
    region: 'Global',
    country: 'Bulgaria'
  },
  tensorrt_llm_news: {
    id: 'tensorrt_llm_news',
    name: 'NVIDIA TensorRT-LLM',
    description: 'Enterprise GPU inference acceleration, FP8/INT4 quantization, in-flight batching, and Blackwell Hopper kernel optimizations',
    enabled: true,
    protocol: 'rss',
    connector: 'tensorrt_llm_news',
    baseUrl: 'https://github.com/NVIDIA/TensorRT-LLM/releases.atom',
    authType: 'none',
    categories: ['ai', 'ai-hardware', 'semiconductors', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'NVIDIA',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 2. Vector Databases & RAG Infrastructure
  // ==========================================
  qdrant_vector_db: {
    id: 'qdrant_vector_db',
    name: 'Qdrant Vector Database',
    description: 'Rust-based vector similarity search engine, payload filtering, HNSW graph indexing, and multimodal neural search',
    enabled: true,
    protocol: 'rss',
    connector: 'qdrant_vector_db',
    baseUrl: 'https://qdrant.tech/blog/index.xml',
    authType: 'none',
    categories: ['ai', 'database', 'developer-tools', 'open-source-ai'] as any,
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Qdrant Solutions',
    region: 'Europe',
    country: 'Germany'
  },
  milvus_vector_db: {
    id: 'milvus_vector_db',
    name: 'Milvus Distributed Vector Database',
    description: 'Cloud-native vector database designed for billion-scale similarity indexing, hybrid query execution, and streaming insertion',
    enabled: true,
    protocol: 'rss',
    connector: 'milvus_vector_db',
    baseUrl: 'https://milvus.io/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'cloud', 'developer-tools', 'open-source-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Zilliz / Milvus Project',
    region: 'Global',
    country: 'United States'
  },
  weaviate_vector_db: {
    id: 'weaviate_vector_db',
    name: 'Weaviate Vector Search Engine',
    description: 'Open-source AI-native vector database, hybrid sparse-dense search, generative feedback loops, and multi-tenant RAG pipelines',
    enabled: true,
    protocol: 'rss',
    connector: 'weaviate_vector_db',
    baseUrl: 'https://weaviate.io/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'open-source-ai', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Weaviate B.V.',
    region: 'Europe',
    country: 'Netherlands'
  },
  chroma_db_blog: {
    id: 'chroma_db_blog',
    name: 'Chroma AI Vector Store',
    description: 'Developer-first embeddings database, document indexing, semantic caching, and client-side AI app integration',
    enabled: true,
    protocol: 'rss',
    connector: 'chroma_db_blog',
    baseUrl: 'https://www.trychroma.com/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'programming', 'open-source-ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Chroma Inc.',
    region: 'Global',
    country: 'United States'
  },
  pinecone_eng_blog: {
    id: 'pinecone_eng_blog',
    name: 'Pinecone Engineering',
    description: 'Serverless vector indexing, graph ANN algorithms, multi-tenant cloud storage, and low-latency retrieval architecture',
    enabled: true,
    protocol: 'rss',
    connector: 'pinecone_eng_blog',
    baseUrl: 'https://www.pinecone.io/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'cloud', 'developer-tools', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Pinecone Systems',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 3. Quantum Computing & Deep Physics
  // ==========================================
  ibm_quantum: {
    id: 'ibm_quantum',
    name: 'IBM Quantum Computing',
    description: 'Superconducting transmon processors, Condor & Heron QPUs, Qiskit open-source SDK, and quantum error mitigation',
    enabled: true,
    protocol: 'rss',
    connector: 'ibm_quantum',
    baseUrl: 'https://www.ibm.com/quantum/blog/rss.xml',
    authType: 'none',
    categories: ['quantum-computing', 'research', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'IBM Quantum',
    region: 'Global',
    country: 'United States'
  },
  google_quantum_ai: {
    id: 'google_quantum_ai',
    name: 'Google Quantum AI',
    description: 'Superconducting quantum error correction, Willow chip milestones, Sycamore architecture, and Cirq framework',
    enabled: true,
    protocol: 'rss',
    connector: 'google_quantum_ai',
    baseUrl: 'https://quantumai.google/research/rss.xml',
    authType: 'none',
    categories: ['quantum-computing', 'research', 'ai-hardware'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Google Quantum AI',
    region: 'Global',
    country: 'United States'
  },
  quanta_magazine: {
    id: 'quanta_magazine',
    name: 'Quanta Magazine (Math & Computer Science)',
    description: 'In-depth reporting on theoretical computer science, computational complexity, pure mathematics, and quantum physics',
    enabled: true,
    protocol: 'rss',
    connector: 'quanta_magazine',
    baseUrl: 'https://api.quantamagazine.org/feed/',
    authType: 'none',
    categories: ['research', 'quantum-computing', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Simons Foundation',
    region: 'Global',
    country: 'United States'
  },
  rigetti_computing: {
    id: 'rigetti_computing',
    name: 'Rigetti Computing',
    description: 'Modular superconducting quantum processors, Aspen-M chip architecture, and hybrid quantum-classical computing',
    enabled: true,
    protocol: 'rss',
    connector: 'rigetti_computing',
    baseUrl: 'https://www.rigetti.com/news?format=rss',
    authType: 'none',
    categories: ['quantum-computing', 'ai-hardware', 'research'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Rigetti Computing',
    region: 'Global',
    country: 'United States'
  },
  ionq_news: {
    id: 'ionq_news',
    name: 'IonQ Quantum Systems',
    description: 'Trapped-ion quantum architecture, barium ion gates, high-fidelity algorithmic qubits (#AQ), and quantum networking',
    enabled: true,
    protocol: 'rss',
    connector: 'ionq_news',
    baseUrl: 'https://ionq.com/feed/news.xml',
    authType: 'none',
    categories: ['quantum-computing', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'IonQ Inc.',
    region: 'Global',
    country: 'United States'
  },
  xanadu_pennylane: {
    id: 'xanadu_pennylane',
    name: 'Xanadu & PennyLane',
    description: 'Photonic quantum computing, quantum machine learning, PennyLane differentiable programming, and Borealis quantum advantage',
    enabled: true,
    protocol: 'rss',
    connector: 'xanadu_pennylane',
    baseUrl: 'https://pennylane.ai/blog/rss.xml',
    authType: 'none',
    categories: ['quantum-computing', 'machine-learning', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Xanadu Quantum Technologies',
    region: 'Americas',
    country: 'Canada'
  },
  physics_world: {
    id: 'physics_world',
    name: 'Physics World Computing & Materials',
    description: 'Breakthroughs in quantum computing, solid-state materials, nanophotonics, superconducting circuits, and detectors',
    enabled: true,
    protocol: 'rss',
    connector: 'physics_world',
    baseUrl: 'https://physicsworld.com/feed/',
    authType: 'none',
    categories: ['quantum-computing', 'research', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Institute of Physics (IOP)',
    region: 'Europe',
    country: 'United Kingdom'
  },
  cern_computing: {
    id: 'cern_computing',
    name: 'CERN Computing & WLCG',
    description: 'Worldwide LHC Computing Grid, exabyte particle data storage, distributed event reconstruction, and high-energy physics software',
    enabled: true,
    protocol: 'rss',
    connector: 'cern_computing',
    baseUrl: 'https://home.cern/rss/news/computing.xml',
    authType: 'none',
    categories: ['research', 'cloud', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'CERN',
    region: 'Europe',
    country: 'Switzerland'
  },

  // ==========================================
  // 4. Space Exploration & Aerospace Tech
  // ==========================================
  nasa_tech: {
    id: 'nasa_tech',
    name: 'NASA Space Technology & Missions',
    description: 'Artemis lunar infrastructure, deep space optical communications, ion propulsion, and orbital robotic systems',
    enabled: true,
    protocol: 'rss',
    connector: 'nasa_tech',
    baseUrl: 'https://www.nasa.gov/news-release/feed/',
    authType: 'none',
    categories: ['technology', 'research', 'robotics'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'NASA',
    region: 'Global',
    country: 'United States'
  },
  esa_technology: {
    id: 'esa_technology',
    name: 'ESA European Space Agency Technology',
    description: 'Ariane 6 launch systems, robotic planetary landers, Earth observation constellations, and space situational awareness',
    enabled: true,
    protocol: 'rss',
    connector: 'esa_technology',
    baseUrl: 'https://www.esa.int/rssfeed/Technology',
    authType: 'none',
    categories: ['technology', 'research', 'robotics'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'European Space Agency',
    region: 'Europe',
    country: 'France'
  },
  planetary_society: {
    id: 'planetary_society',
    name: 'The Planetary Society',
    description: 'Planetary defense, LightSail solar sailing, Europa Clipper discoveries, and robotic exploration advocacy',
    enabled: true,
    protocol: 'rss',
    connector: 'planetary_society',
    baseUrl: 'https://www.planetary.org/rss/articles',
    authType: 'none',
    categories: ['technology', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'The Planetary Society',
    region: 'Global',
    country: 'United States'
  },
  ars_technica_space: {
    id: 'ars_technica_space',
    name: 'Ars Technica Space Exploration',
    description: 'In-depth aerospace reporting, commercial space race, Starship testing, orbital mechanics, and satellite telemetry',
    enabled: true,
    protocol: 'rss',
    connector: 'ars_technica_space',
    baseUrl: 'https://feeds.arstechnica.com/arstechnica/space',
    authType: 'none',
    categories: ['technology', 'research'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Ars Technica / Condé Nast',
    region: 'Global',
    country: 'United States'
  },
  nasa_jpl_news: {
    id: 'nasa_jpl_news',
    name: 'NASA Jet Propulsion Laboratory',
    description: 'Mars Perseverance rover autonomy, Ingenuity aerial flight data, outer planet orbiters, and deep space telemetry',
    enabled: true,
    protocol: 'rss',
    connector: 'nasa_jpl_news',
    baseUrl: 'https://www.jpl.nasa.gov/feeds/news/',
    authType: 'none',
    categories: ['robotics', 'technology', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'NASA / Caltech JPL',
    region: 'Global',
    country: 'United States'
  },
  spaceflight_now: {
    id: 'spaceflight_now',
    name: 'Spaceflight Now',
    description: 'Up-to-the-minute rocket launch coverage, orbital mission updates, countdown tracking, and stage separation analysis',
    enabled: true,
    protocol: 'rss',
    connector: 'spaceflight_now',
    baseUrl: 'https://spaceflightnow.com/feed/',
    authType: 'none',
    categories: ['technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Spaceflight Now',
    region: 'Global',
    country: 'United States'
  },
  universe_today: {
    id: 'universe_today',
    name: 'Universe Today Space & Physics',
    description: 'Astrophysics research, exoplanet surveys, James Webb Space Telescope observations, and orbital mechanics',
    enabled: true,
    protocol: 'rss',
    connector: 'universe_today',
    baseUrl: 'https://www.universetoday.com/feed/',
    authType: 'none',
    categories: ['research', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Universe Today',
    region: 'Global',
    country: 'Canada'
  },

  // ==========================================
  // 5. Autonomous Vehicles, Robotics & Edge Vision
  // ==========================================
  waymo_blog: {
    id: 'waymo_blog',
    name: 'Waymo Safety & Autonomous Driving',
    description: 'Waymo Driver foundation models, Lidar-radar-camera sensor fusion, million-mile safety validation, and commercial robotaxis',
    enabled: true,
    protocol: 'rss',
    connector: 'waymo_blog',
    baseUrl: 'https://waymo.com/blog/feed.xml',
    authType: 'none',
    categories: ['robotics', 'ai', 'computer-vision', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Waymo LLC (Alphabet)',
    region: 'Global',
    country: 'United States'
  },
  cruise_autonomy: {
    id: 'cruise_autonomy',
    name: 'Cruise AI & Autonomy',
    description: 'Self-driving vehicle architecture, urban edge cases, neural motion planning, and real-time simulation testing',
    enabled: true,
    protocol: 'rss',
    connector: 'cruise_autonomy',
    baseUrl: 'https://medium.com/feed/cruise',
    authType: 'none',
    categories: ['robotics', 'ai', 'computer-vision'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cruise LLC',
    region: 'Global',
    country: 'United States'
  },
  zoox_blog: {
    id: 'zoox_blog',
    name: 'Zoox Autonomous Mobility',
    description: 'Purpose-built bidirectional autonomous robotaxis, four-wheel steering, 360-degree sensor coverage, and urban autonomy',
    enabled: true,
    protocol: 'rss',
    connector: 'zoox_blog',
    baseUrl: 'https://zoox.com/feed/',
    authType: 'none',
    categories: ['robotics', 'ai', 'computer-vision', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Zoox (Amazon)',
    region: 'Global',
    country: 'United States'
  },
  aurora_innovation: {
    id: 'aurora_innovation',
    name: 'Aurora Autonomous Freight & Driver',
    description: 'Autonomous Class 8 trucking, Aurora Driver perception stack, FirstLight Lidar, and high-speed highway navigation',
    enabled: true,
    protocol: 'rss',
    connector: 'aurora_innovation',
    baseUrl: 'https://aurora.tech/blog/rss.xml',
    authType: 'none',
    categories: ['robotics', 'ai', 'computer-vision'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Aurora Innovation',
    region: 'Global',
    country: 'United States'
  },
  comma_ai: {
    id: 'comma_ai',
    name: 'comma.ai & openpilot',
    description: 'End-to-end vision neural driving policies, openpilot open-source ADAS, embedded hardware, and crowd-sourced driving telemetry',
    enabled: true,
    protocol: 'rss',
    connector: 'comma_ai',
    baseUrl: 'https://blog.comma.ai/rss/',
    authType: 'none',
    categories: ['robotics', 'ai', 'computer-vision', 'open-source-ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'comma.ai',
    region: 'Global',
    country: 'United States'
  },
  opencv_official: {
    id: 'opencv_official',
    name: 'OpenCV Official Computer Vision',
    description: 'Open source computer vision library, OpenCV 5 spatial AI, DNN module inference, and edge optical flow algorithms',
    enabled: true,
    protocol: 'rss',
    connector: 'opencv_official',
    baseUrl: 'https://opencv.org/feed/',
    authType: 'none',
    categories: ['computer-vision', 'ai', 'programming', 'open-source-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'OpenCV Foundation',
    region: 'Global',
    country: 'United States'
  },
  open_robotics_ros: {
    id: 'open_robotics_ros',
    name: 'Open Robotics & ROS 2',
    description: 'Robot Operating System 2 (ROS 2), Gazebo physics simulation environment, DDS middleware, and real-time robotic controls',
    enabled: true,
    protocol: 'rss',
    connector: 'open_robotics_ros',
    baseUrl: 'https://www.openrobotics.org/blog?format=rss',
    authType: 'none',
    categories: ['robotics', 'open-source-ai', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Open Robotics / OSRF',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 6. Bioinformatics & Computational Biology
  // ==========================================
  isomorphic_labs: {
    id: 'isomorphic_labs',
    name: 'Isomorphic Labs (Digital Biology)',
    description: 'AlphaFold 3 biological structure prediction, computational ligand docking, and generative AI drug candidate design',
    enabled: true,
    protocol: 'rss',
    connector: 'isomorphic_labs',
    baseUrl: 'https://www.isomorphiclabs.com/news/rss.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'research', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Isomorphic Labs (Alphabet)',
    region: 'Europe',
    country: 'United Kingdom'
  },
  broad_institute: {
    id: 'broad_institute',
    name: 'Broad Institute of MIT and Harvard',
    description: 'Genomic medicine, CRISPR prime editing, single-cell RNA sequencing algorithms, and biomedical machine learning',
    enabled: true,
    protocol: 'rss',
    connector: 'broad_institute',
    baseUrl: 'https://www.broadinstitute.org/news/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Broad Institute',
    region: 'Americas',
    country: 'United States'
  },
  genentech_research: {
    id: 'genentech_research',
    name: 'Genentech Computational Biology',
    description: 'Prescient Design generative molecular models, antibody engineering, cancer genomics, and computational pathology',
    enabled: true,
    protocol: 'rss',
    connector: 'genentech_research',
    baseUrl: 'https://www.gene.com/stories/rss',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Genentech / Roche',
    region: 'Global',
    country: 'United States'
  },
  ginkgo_bioworks: {
    id: 'ginkgo_bioworks',
    name: 'Ginkgo Bioworks Synthetic Biology',
    description: 'Cell programming platform, automated high-throughput biofoundries, enzyme engineering, and biological AI models',
    enabled: true,
    protocol: 'rss',
    connector: 'ginkgo_bioworks',
    baseUrl: 'https://www.ginkgobioworks.com/feed/',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Ginkgo Bioworks',
    region: 'Global',
    country: 'United States'
  },
  nature_biotechnology: {
    id: 'nature_biotechnology',
    name: 'Nature Biotechnology News',
    description: 'Peer-reviewed breakthroughs in CRISPR, base editing, synthetic genomics, cellular therapies, and AI for science',
    enabled: true,
    protocol: 'rss',
    connector: 'nature_biotechnology',
    baseUrl: 'https://www.nature.com/nbt.rss',
    authType: 'none',
    categories: ['research', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Nature Portfolio',
    region: 'Global',
    country: 'United Kingdom'
  },
  genomeweb_tech: {
    id: 'genomeweb_tech',
    name: 'GenomeWeb Bio-IT & Sequencing',
    description: 'Next-generation sequencing instrumentation, bioinformatics pipelines, spatial biology, and precision oncology assays',
    enabled: true,
    protocol: 'rss',
    connector: 'genomeweb_tech',
    baseUrl: 'https://www.genomeweb.com/rss/all',
    authType: 'none',
    categories: ['research', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'GenomeWeb / Crain',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 7. Cryptographic Foundations & High Assurance
  // ==========================================
  vitalik_buterin: {
    id: 'vitalik_buterin',
    name: 'Vitalik Buterin Research Essays',
    description: 'Deep dives on cryptographic SNARKs, proof-of-stake economics, rollups, account abstraction, and decentralized governance',
    enabled: true,
    protocol: 'rss',
    connector: 'vitalik_buterin',
    baseUrl: 'https://vitalik.eth.limo/feed.xml',
    authType: 'none',
    categories: ['cybersecurity', 'programming', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Vitalik Buterin',
    region: 'Global',
    country: 'Canada'
  },
  paradigm_research: {
    id: 'paradigm_research',
    name: 'Paradigm Research & Engineering',
    description: 'Formal verification, zero-knowledge virtual machines (Reth & Alloy in Rust), MEV research, and mechanism design',
    enabled: true,
    protocol: 'rss',
    connector: 'paradigm_research',
    baseUrl: 'https://www.paradigm.xyz/rss.xml',
    authType: 'none',
    categories: ['cybersecurity', 'programming', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Paradigm Operations',
    region: 'Global',
    country: 'United States'
  },
  a16z_crypto: {
    id: 'a16z_crypto',
    name: 'a16z Crypto Research',
    description: 'Polynomial commitments, SNARK prover performance, consensus protocols, and verifiable computation theory',
    enabled: true,
    protocol: 'rss',
    connector: 'a16z_crypto',
    baseUrl: 'https://a16zcrypto.com/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'research', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Andreessen Horowitz Crypto',
    region: 'Global',
    country: 'United States'
  },
  ethereum_foundation: {
    id: 'ethereum_foundation',
    name: 'Ethereum Foundation Blog',
    description: 'Protocol upgrades, PeerDAS data availability sampling, Verkle trees, cryptography grants, and core client consensus',
    enabled: true,
    protocol: 'rss',
    connector: 'ethereum_foundation',
    baseUrl: 'https://blog.ethereum.org/feed.xml',
    authType: 'none',
    categories: ['cybersecurity', 'programming', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Ethereum Foundation',
    region: 'Global',
    country: 'Switzerland'
  },
  flashbots_research: {
    id: 'flashbots_research',
    name: 'Flashbots Research & PBS',
    description: 'Mitigating maximal extractable value (MEV), SUAVE decentralized block building, cryptographic privacy, and SGX enclaves',
    enabled: true,
    protocol: 'rss',
    connector: 'flashbots_research',
    baseUrl: 'https://writings.flashbots.net/rss.xml',
    authType: 'none',
    categories: ['cybersecurity', 'programming', 'research'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Flashbots Collective',
    region: 'Global',
    country: 'United States'
  },
  chainlink_engineering: {
    id: 'chainlink_engineering',
    name: 'Chainlink Engineering & CCIP',
    description: 'Decentralized oracle networks, Cross-Chain Interoperability Protocol (CCIP), cryptographic proof of reserves, and data feeds',
    enabled: true,
    protocol: 'rss',
    connector: 'chainlink_engineering',
    baseUrl: 'https://blog.chain.link/rss/',
    authType: 'none',
    categories: ['cybersecurity', 'cloud', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Chainlink Labs',
    region: 'Global',
    country: 'United States'
  },
  electric_coin_co: {
    id: 'electric_coin_co',
    name: 'Electric Coin Co (Halo 2 ZK)',
    description: 'Halo 2 recursive zero-knowledge proving system, transparent SNARKs without trusted setup, and cryptographic privacy protocols',
    enabled: true,
    protocol: 'rss',
    connector: 'electric_coin_co',
    baseUrl: 'https://electriccoin.co/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'research', 'programming'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Electric Coin Company',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 8. Global High-Scale Engineering Tech Blogs
  // ==========================================
  grab_tech: {
    id: 'grab_tech',
    name: 'Grab Tech Blog',
    description: 'Southeast Asia hyper-app scale, driver-passenger matchmaking algorithms, geocoding engines, and multi-region Kubernetes',
    enabled: true,
    protocol: 'rss',
    connector: 'grab_tech',
    baseUrl: 'https://engineering.grab.com/feed.xml',
    authType: 'none',
    categories: ['cloud', 'programming', 'technology', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Grab Holdings',
    region: 'Asia',
    country: 'Singapore'
  },
  gojek_tech: {
    id: 'gojek_tech',
    name: 'GoTo / Gojek Tech Blog',
    description: 'High-throughput microservices, real-time dynamic pricing, Kafka streaming pipelines, and mobile super-app architecture',
    enabled: true,
    protocol: 'rss',
    connector: 'gojek_tech',
    baseUrl: 'https://www.gojek.io/blog/rss.xml',
    authType: 'none',
    categories: ['cloud', 'programming', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'GoTo Group',
    region: 'Asia',
    country: 'Indonesia'
  },
  mercadolibre_tech: {
    id: 'mercadolibre_tech',
    name: 'Mercado Libre Tech',
    description: 'Latin America largest commerce & fintech cloud, Fury platform, distributed payments ledger, and cross-border logistics',
    enabled: true,
    protocol: 'rss',
    connector: 'mercadolibre_tech',
    baseUrl: 'https://medium.com/feed/mercadolibre-tech',
    authType: 'none',
    categories: ['cloud', 'programming', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Mercado Libre',
    region: 'Latin America',
    country: 'Argentina'
  },
  booking_tech: {
    id: 'booking_tech',
    name: 'Booking.com Technology Blog',
    description: 'High-scale global accommodation graphs, randomized A/B experimentation engines, machine learning search ranking, and infra',
    enabled: true,
    protocol: 'rss',
    connector: 'booking_tech',
    baseUrl: 'https://medium.com/feed/booking-com-development',
    authType: 'none',
    categories: ['cloud', 'programming', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Booking Holdings',
    region: 'Europe',
    country: 'Netherlands'
  },
  zalando_engineering: {
    id: 'zalando_engineering',
    name: 'Zalando Engineering',
    description: 'Microfrontends, multi-tenant Kubernetes clusters, high-scale fashion recommendation algorithms, and open source tooling',
    enabled: true,
    protocol: 'rss',
    connector: 'zalando_engineering',
    baseUrl: 'https://engineering.zalando.com/atom.xml',
    authType: 'none',
    categories: ['cloud', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Zalando SE',
    region: 'Europe',
    country: 'Germany'
  },
  swiggy_tech: {
    id: 'swiggy_tech',
    name: 'Swiggy Bytes Tech Blog',
    description: 'Hyper-local on-demand food and grocery delivery, real-time routing engines, battery optimization, and low-latency APIs',
    enabled: true,
    protocol: 'rss',
    connector: 'swiggy_tech',
    baseUrl: 'https://bytes.swiggy.com/feed',
    authType: 'none',
    categories: ['cloud', 'programming', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Swiggy Limited',
    region: 'Asia',
    country: 'India'
  },
  flipkart_engineering: {
    id: 'flipkart_engineering',
    name: 'Flipkart Tech & Engineering',
    description: 'E-commerce flash sales infrastructure (Big Billion Days), distributed caching tiers, supply chain automation, and ML discovery',
    enabled: true,
    protocol: 'rss',
    connector: 'flipkart_engineering',
    baseUrl: 'https://tech.flipkart.com/feed',
    authType: 'none',
    categories: ['cloud', 'programming', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Flipkart (Walmart)',
    region: 'Asia',
    country: 'India'
  },
  monzo_tech: {
    id: 'monzo_tech',
    name: 'Monzo Technology Blog',
    description: 'Modern bank architecture on AWS, 2,500+ Go microservices on Kubernetes, distributed banking ledger, and zero trust networking',
    enabled: true,
    protocol: 'rss',
    connector: 'monzo_tech',
    baseUrl: 'https://monzo.com/blog/feed.xml',
    authType: 'none',
    categories: ['cloud', 'programming', 'cybersecurity'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Monzo Bank Limited',
    region: 'Europe',
    country: 'United Kingdom'
  },
  revolut_tech: {
    id: 'revolut_tech',
    name: 'Revolut Engineering',
    description: 'Global financial super-app scale, real-time FX settlement engines, anti-fraud neural classifiers, and microservice resilience',
    enabled: true,
    protocol: 'rss',
    connector: 'revolut_tech',
    baseUrl: 'https://medium.com/feed/revolut',
    authType: 'none',
    categories: ['cloud', 'programming', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Revolut Ltd',
    region: 'Europe',
    country: 'United Kingdom'
  },
  wise_engineering: {
    id: 'wise_engineering',
    name: 'Wise Tech Blog',
    description: 'Cross-border borderless money transmission, distributed ledgers, zero-spread currency conversion, and global Kafka mesh',
    enabled: true,
    protocol: 'rss',
    connector: 'wise_engineering',
    baseUrl: 'https://medium.com/feed/wise-engineering',
    authType: 'none',
    categories: ['cloud', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Wise Payments Ltd',
    region: 'Europe',
    country: 'United Kingdom'
  },
  klarna_engineering: {
    id: 'klarna_engineering',
    name: 'Klarna Engineering',
    description: 'Real-time credit underwriting at scale, consumer shopping graph, AI customer service agents, and cloud event streaming',
    enabled: true,
    protocol: 'rss',
    connector: 'klarna_engineering',
    baseUrl: 'https://medium.com/feed/klarna-engineering',
    authType: 'none',
    categories: ['cloud', 'programming', 'ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Klarna Bank AB',
    region: 'Europe',
    country: 'Sweden'
  },
  deliveroo_engineering: {
    id: 'deliveroo_engineering',
    name: 'Deliveroo Engineering',
    description: 'Real-time hyper-local courier dispatch, logistics simulation engines, rider routing algorithms, and backend services',
    enabled: true,
    protocol: 'rss',
    connector: 'deliveroo_engineering',
    baseUrl: 'https://deliveroo.engineering/feed.xml',
    authType: 'none',
    categories: ['cloud', 'programming', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Deliveroo plc',
    region: 'Europe',
    country: 'United Kingdom'
  },
  riot_games_engineering: {
    id: 'riot_games_engineering',
    name: 'Riot Games Technology',
    description: 'Global real-time game servers, low-latency UDP networking, Vanguard anti-cheat kernel drivers, and distributed game state',
    enabled: true,
    protocol: 'rss',
    connector: 'riot_games_engineering',
    baseUrl: 'https://technology.riotgames.com/news/feed',
    authType: 'none',
    categories: ['programming', 'cloud', 'cybersecurity', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Riot Games',
    region: 'Global',
    country: 'United States'
  },
  spotify_rd: {
    id: 'spotify_rd',
    name: 'Spotify Engineering & R&D',
    description: 'Backstage developer portal, billion-track audio recommendation graph, low-latency client streaming, and data fleet ops',
    enabled: true,
    protocol: 'rss',
    connector: 'spotify_rd',
    baseUrl: 'https://engineering.atspotify.com/feed/',
    authType: 'none',
    categories: ['cloud', 'programming', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Spotify AB',
    region: 'Europe',
    country: 'Sweden'
  },

  // ==========================================
  // 9. Modern Web Systems & Frontend Runtimes
  // ==========================================
  tanstack_blog: {
    id: 'tanstack_blog',
    name: 'TanStack Official Blog',
    description: 'Tanner Linsley and team on TanStack Query, TanStack Table, TanStack Router, TanStack Virtual, and full-stack type safety',
    enabled: true,
    protocol: 'rss',
    connector: 'tanstack_blog',
    baseUrl: 'https://tanstack.com/blog/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Tanner Linsley & TanStack Team',
    region: 'Global',
    country: 'United States'
  },
  anthony_fu_blog: {
    id: 'anthony_fu_blog',
    name: 'Anthony Fu (Vue, Vite & Tooling)',
    description: 'Vue Core team, Vite, UnoCSS, Vitest, unplugin, Shiki syntax highlighter, and modern open-source toolchain development',
    enabled: true,
    protocol: 'rss',
    connector: 'anthony_fu_blog',
    baseUrl: 'https://antfu.me/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Anthony Fu',
    region: 'Global',
    country: 'Japan'
  },
  overreacted_dan: {
    id: 'overreacted_dan',
    name: 'Overreacted (Dan Abramov)',
    description: 'Mental models for React, React Server Components (RSC), JavaScript execution mechanics, and declarative interface design',
    enabled: true,
    protocol: 'rss',
    connector: 'overreacted_dan',
    baseUrl: 'https://overreacted.io/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Dan Abramov',
    region: 'Europe',
    country: 'United Kingdom'
  },
  kentcdodds_blog: {
    id: 'kentcdodds_blog',
    name: 'Kent C. Dodds (Epic Web)',
    description: 'Full-stack JavaScript, React Testing Library, Remix architecture, state management patterns, and software reliability',
    enabled: true,
    protocol: 'rss',
    connector: 'kentcdodds_blog',
    baseUrl: 'https://kentcdodds.com/blog/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Kent C. Dodds',
    region: 'Global',
    country: 'United States'
  },
  joshwcomeau_blog: {
    id: 'joshwcomeau_blog',
    name: 'Josh W. Comeau Interactive Tech',
    description: 'Modern CSS layout algorithms, React spring physics animations, frontend performance, and visual accessibility',
    enabled: true,
    protocol: 'rss',
    connector: 'joshwcomeau_blog',
    baseUrl: 'https://www.joshwcomeau.com/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Josh W. Comeau',
    region: 'Americas',
    country: 'Canada'
  },
  lee_robinson_blog: {
    id: 'lee_robinson_blog',
    name: 'Lee Robinson (Modern Web)',
    description: 'Next.js App Router, edge computing runtime architectures, React Server Actions, and web developer productivity',
    enabled: true,
    protocol: 'rss',
    connector: 'lee_robinson_blog',
    baseUrl: 'https://leerob.io/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'cloud'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Lee Robinson',
    region: 'Global',
    country: 'United States'
  },
  nuxt_blog: {
    id: 'nuxt_blog',
    name: 'Nuxt.js Framework Blog',
    description: 'Full-stack Vue framework, Nitro universal server engine, auto-imports, hydration optimizations, and server-side rendering',
    enabled: true,
    protocol: 'rss',
    connector: 'nuxt_blog',
    baseUrl: 'https://nuxt.com/blog/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Nuxt Team',
    region: 'Europe',
    country: 'France'
  },
  remix_run_blog: {
    id: 'remix_run_blog',
    name: 'Remix & React Router',
    description: 'Web standards, nested routing, HTTP caching semantics, server mutations, and progressive enhancement',
    enabled: true,
    protocol: 'rss',
    connector: 'remix_run_blog',
    baseUrl: 'https://remix.run/blog/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Shopify / Remix Team',
    region: 'Global',
    country: 'United States'
  },
  biomejs_blog: {
    id: 'biomejs_blog',
    name: 'Biome Toolchain (Rust Linter & Formatter)',
    description: 'Ultra-fast Rust-based linter, formatter, and parser for JavaScript, TypeScript, JSX, and CSS',
    enabled: true,
    protocol: 'rss',
    connector: 'biomejs_blog',
    baseUrl: 'https://biomejs.dev/feed.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Biome Project',
    region: 'Global',
    country: 'United States'
  },
  preact_blog: {
    id: 'preact_blog',
    name: 'Preact Core Blog',
    description: 'Fast 3kB React alternative, Signals reactivity primitive, DOM diffing optimizations, and edge rendering',
    enabled: true,
    protocol: 'rss',
    connector: 'preact_blog',
    baseUrl: 'https://preactjs.com/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Jason Miller & Preact Team',
    region: 'Global',
    country: 'United States'
  },
  v8_js_engine: {
    id: 'v8_js_engine',
    name: 'Google V8 JavaScript Engine',
    description: 'Ignition bytecode interpreter, TurboFan optimizing compiler, WebAssembly garbage collection, and ECMAScript features',
    enabled: true,
    protocol: 'rss',
    connector: 'v8_js_engine',
    baseUrl: 'https://v8.dev/blog.atom',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Google V8 Team',
    region: 'Global',
    country: 'United States'
  },
  electron_blog: {
    id: 'electron_blog',
    name: 'Electron Framework Blog',
    description: 'Cross-platform desktop application framework, Chromium & Node.js integration, sandboxing, and memory reductions',
    enabled: true,
    protocol: 'rss',
    connector: 'electron_blog',
    baseUrl: 'https://www.electronjs.org/blog/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'OpenJS Foundation / Electron Team',
    region: 'Global',
    country: 'United States'
  },
  tauri_apps_blog: {
    id: 'tauri_apps_blog',
    name: 'Tauri Apps (Rust Desktop Framework)',
    description: 'Lightweight, memory-efficient desktop and mobile application framework using OS webviews and a secure Rust backend',
    enabled: true,
    protocol: 'rss',
    connector: 'tauri_apps_blog',
    baseUrl: 'https://v2.tauri.app/blog/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'cybersecurity'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Tauri Programme',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 10. Offensive Security, Threat Hunting & Reverse Engineering
  // ==========================================
  sans_isc_diary: {
    id: 'sans_isc_diary',
    name: 'SANS Internet Storm Center (ISC)',
    description: 'Daily operational cyber threat diary, active exploitation monitoring, honeypot telemetry, and zero-day patch alerts',
    enabled: true,
    protocol: 'rss',
    connector: 'sans_isc_diary',
    baseUrl: 'https://isc.sans.edu/rssfeed.xml',
    authType: 'none',
    categories: ['cybersecurity', 'cloud', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'SANS Institute',
    region: 'Global',
    country: 'United States'
  },
  mandiant_threat_intelligence: {
    id: 'mandiant_threat_intelligence',
    name: 'Google Mandiant Threat Intelligence',
    description: 'Nation-state advanced persistent threat (APT) attribution, ransomware incident response, and malware disassembly',
    enabled: true,
    protocol: 'rss',
    connector: 'mandiant_threat_intelligence',
    baseUrl: 'https://cloud.google.com/feeds/mandiant-threat-intelligence.xml',
    authType: 'none',
    categories: ['cybersecurity', 'cloud'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Mandiant / Google Cloud',
    region: 'Global',
    country: 'United States'
  },
  black_hills_infosec: {
    id: 'black_hills_infosec',
    name: 'Black Hills Information Security',
    description: 'Red teaming methodologies, Active Directory penetration testing, defense evasion, and adversary emulation',
    enabled: true,
    protocol: 'rss',
    connector: 'black_hills_infosec',
    baseUrl: 'https://www.blackhillsinfosec.com/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Black Hills Information Security',
    region: 'Global',
    country: 'United States'
  },
  liveoverflow_security: {
    id: 'liveoverflow_security',
    name: 'LiveOverflow Security & Binary Exploitation',
    description: 'Reverse engineering, binary exploitation, memory corruption vulnerabilities, heap spraying, and hardware hacking',
    enabled: true,
    protocol: 'rss',
    connector: 'liveoverflow_security',
    baseUrl: 'https://liveoverflow.com/feed.xml',
    authType: 'none',
    categories: ['cybersecurity', 'programming', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'LiveOverflow',
    region: 'Europe',
    country: 'Germany'
  },
  specterops_blog: {
    id: 'specterops_blog',
    name: 'SpecterOps (BloodHound & Identity Threat)',
    description: 'Attack path management, BloodHound graph theory, Windows authentication internals, and adversary tradecraft',
    enabled: true,
    protocol: 'rss',
    connector: 'specterops_blog',
    baseUrl: 'https://posts.specterops.io/feed',
    authType: 'none',
    categories: ['cybersecurity', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'SpecterOps Inc.',
    region: 'Global',
    country: 'United States'
  },
  red_canary_research: {
    id: 'red_canary_research',
    name: 'Red Canary Threat Research',
    description: 'Endpoint telemetry analytics, MITRE ATT&CK technique breakdown, threat detection reports, and behavioral malware analysis',
    enabled: true,
    protocol: 'rss',
    connector: 'red_canary_research',
    baseUrl: 'https://redcanary.com/blog/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Red Canary',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 11. Kernels, Operating Systems & Low-Level Runtime
  // ==========================================
  kernelnewbies_linux: {
    id: 'kernelnewbies_linux',
    name: 'KernelNewbies Linux Subsystem News',
    description: 'Detailed breakdowns of Linux kernel release features, memory management patches, eBPF subsystems, and scheduler revisions',
    enabled: true,
    protocol: 'rss',
    connector: 'kernelnewbies_linux',
    baseUrl: 'https://kernelnewbies.org/LinuxChanges?action=rss_rc',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'KernelNewbies Community',
    region: 'Global',
    country: 'United States'
  },
  lwn_kernel: {
    id: 'lwn_kernel',
    name: 'LWN.net Linux Kernel Coverage',
    description: 'In-depth investigative reports on Linux kernel development, memory management, concurrency, and security patches',
    enabled: true,
    protocol: 'rss',
    connector: 'lwn_kernel',
    baseUrl: 'https://lwn.net/headlines/rss',
    authType: 'none',
    categories: ['programming', 'cybersecurity', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Eklektix, Inc. / LWN.net',
    region: 'Global',
    country: 'United States'
  },
  freebsd_foundation: {
    id: 'freebsd_foundation',
    name: 'FreeBSD Foundation News',
    description: 'FreeBSD operating system engineering, ZFS filesystem enhancements, bhyve hypervisor, and network stack improvements',
    enabled: true,
    protocol: 'rss',
    connector: 'freebsd_foundation',
    baseUrl: 'https://freebsdfoundation.org/feed/',
    authType: 'none',
    categories: ['programming', 'cloud', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'FreeBSD Foundation',
    region: 'Global',
    country: 'United States'
  },
  debian_dev_news: {
    id: 'debian_dev_news',
    name: 'Debian Developer News',
    description: 'The universal operating system, reproducible builds, dpkg and apt package management, and kernel security updates',
    enabled: true,
    protocol: 'rss',
    connector: 'debian_dev_news',
    baseUrl: 'https://bits.debian.org/feeds/feed.rss',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Debian Project',
    region: 'Global',
    country: 'United States'
  },
  fedora_magazine: {
    id: 'fedora_magazine',
    name: 'Fedora Magazine & Engineering',
    description: 'Cutting-edge Linux distribution features, Wayland compositors, systemd developments, and Fedora Silverblue immutable OS',
    enabled: true,
    protocol: 'rss',
    connector: 'fedora_magazine',
    baseUrl: 'https://fedoramagazine.org/feed/',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Fedora Project / Red Hat',
    region: 'Global',
    country: 'United States'
  },
  gentoo_news: {
    id: 'gentoo_news',
    name: 'Gentoo Linux News',
    description: 'Source-based meta-distribution, Portage package manager, toolchain hardening, GCC compiler optimizations, and ebuilds',
    enabled: true,
    protocol: 'rss',
    connector: 'gentoo_news',
    baseUrl: 'https://www.gentoo.org/news/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Gentoo Foundation',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 12. Game Tech, Real-Time Rendering & Graphics
  // ==========================================
  unreal_engine_tech: {
    id: 'unreal_engine_tech',
    name: 'Unreal Engine Tech Blog',
    description: 'Nanite virtualized geometry, Lumen dynamic global illumination, Chaos physics engine, and MetaHuman facial rigs',
    enabled: true,
    protocol: 'rss',
    connector: 'unreal_engine_tech',
    baseUrl: 'https://www.unrealengine.com/en-US/feed',
    authType: 'none',
    categories: ['programming', 'technology', 'computer-vision'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Epic Games',
    region: 'Global',
    country: 'United States'
  },
  unity_tech_blog: {
    id: 'unity_tech_blog',
    name: 'Unity Technologies Engineering',
    description: 'Data-Oriented Technology Stack (DOTS), Universal Render Pipeline (URP), High Definition Render Pipeline, and burst compilers',
    enabled: true,
    protocol: 'rss',
    connector: 'unity_tech_blog',
    baseUrl: 'https://blog.unity.com/feed',
    authType: 'none',
    categories: ['programming', 'technology', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Unity Technologies',
    region: 'Global',
    country: 'United States'
  },
  godot_engine_blog: {
    id: 'godot_engine_blog',
    name: 'Godot Engine Developer Blog',
    description: 'Free open-source game engine, Vulkan rendering backend, scene tree architecture, GDScript compiler, and physics engine',
    enabled: true,
    protocol: 'rss',
    connector: 'godot_engine_blog',
    baseUrl: 'https://godotengine.org/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'open-source-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Godot Engine Community',
    region: 'Global',
    country: 'Argentina'
  },
  blender_dev_blog: {
    id: 'blender_dev_blog',
    name: 'Blender Developer Blog',
    description: 'Cycles ray-tracing render engine, EEVEE Next real-time viewport, Geometry Nodes, and open-source 3D pipeline tools',
    enabled: true,
    protocol: 'rss',
    connector: 'blender_dev_blog',
    baseUrl: 'https://code.blender.org/feed/',
    authType: 'none',
    categories: ['programming', 'technology', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Blender Foundation',
    region: 'Europe',
    country: 'Netherlands'
  },
  inigo_quilez_graphics: {
    id: 'inigo_quilez_graphics',
    name: 'Inigo Quilez Computer Graphics',
    description: 'Signed distance functions (SDFs), procedural shader mathematics, raymarching algorithms, and Shadertoy rendering techniques',
    enabled: true,
    protocol: 'rss',
    connector: 'inigo_quilez_graphics',
    baseUrl: 'https://iquilezles.org/feed.xml',
    authType: 'none',
    categories: ['programming', 'technology', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Inigo Quilez',
    region: 'Global',
    country: 'Spain'
  },
  graphics_programming_weekly: {
    id: 'graphics_programming_weekly',
    name: 'Graphics Programming Weekly',
    description: 'Curated technical digest covering Vulkan, DirectX 12, Metal, GPU compute shaders, radiance cascades, and path tracing',
    enabled: true,
    protocol: 'rss',
    connector: 'graphics_programming_weekly',
    baseUrl: 'https://alain.xyz/feed.xml',
    authType: 'none',
    categories: ['programming', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Alain Galvan & Graphics Programming Weekly',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 13. Distributed Compute, Streaming & Data Engines
  // ==========================================
  sqlite_news: {
    id: 'sqlite_news',
    name: 'SQLite Database News & Architecture',
    description: 'The world most deployed SQL engine, write-ahead logging (WAL), B-tree storage, and zero-configuration embedded persistence',
    enabled: true,
    protocol: 'rss',
    connector: 'sqlite_news',
    baseUrl: 'https://sqlite.org/news.rss',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'D. Richard Hipp & SQLite Team',
    region: 'Global',
    country: 'United States'
  },
  scylladb_engineering: {
    id: 'scylladb_engineering',
    name: 'ScyllaDB NoSQL Distributed Database',
    description: 'Ultra-low latency C++ NoSQL database, Seastar thread-per-core asynchronous architecture, and Cassandra compatibility',
    enabled: true,
    protocol: 'rss',
    connector: 'scylladb_engineering',
    baseUrl: 'https://www.scylladb.com/feed/',
    authType: 'none',
    categories: ['cloud', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ScyllaDB Inc.',
    region: 'Global',
    country: 'United States'
  },
  apache_flink_blog: {
    id: 'apache_flink_blog',
    name: 'Apache Flink Stateful Streaming',
    description: 'True event-driven stream processing, exactly-once state consistency, event time windowing, and streaming data analytics',
    enabled: true,
    protocol: 'rss',
    connector: 'apache_flink_blog',
    baseUrl: 'https://flink.apache.org/feed.xml',
    authType: 'none',
    categories: ['cloud', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Apache Software Foundation',
    region: 'Global',
    country: 'United States'
  },
  apache_spark_news: {
    id: 'apache_spark_news',
    name: 'Apache Spark Distributed Analytics',
    description: 'Unified analytics engine for large-scale data processing, Spark SQL Catalyst optimizer, and Tungsten off-heap execution',
    enabled: true,
    protocol: 'rss',
    connector: 'apache_spark_news',
    baseUrl: 'https://spark.apache.org/rss/news.xml',
    authType: 'none',
    categories: ['cloud', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Apache Software Foundation',
    region: 'Global',
    country: 'United States'
  },
  polars_data_blog: {
    id: 'polars_data_blog',
    name: 'Polars Fast DataFrames in Rust',
    description: 'Blazingly fast columnar DataFrame library in Rust and Python, Apache Arrow memory spec, multi-threaded query optimization',
    enabled: true,
    protocol: 'rss',
    connector: 'polars_data_blog',
    baseUrl: 'https://pola.rs/posts/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Polars Foundation',
    region: 'Europe',
    country: 'Netherlands'
  },
  haskell_weekly: {
    id: 'haskell_weekly',
    name: 'Haskell Weekly & Pure FP',
    description: 'Pure functional programming, strong static typing, category theory applications, GHC compiler optimizations, and lazy evaluation',
    enabled: true,
    protocol: 'rss',
    connector: 'haskell_weekly',
    baseUrl: 'https://haskellweekly.news/newsletter.rss',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Taylor Fausak & Haskell Community',
    region: 'Global',
    country: 'United States'
  },
  phoenix_framework: {
    id: 'phoenix_framework',
    name: 'Phoenix Framework & LiveView',
    description: 'High-concurrency web architecture on the Erlang BEAM virtual machine, Phoenix LiveView server-rendered reactive websockets',
    enabled: true,
    protocol: 'rss',
    connector: 'phoenix_framework',
    baseUrl: 'https://www.phoenixframework.org/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'cloud'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Chris McCord & Phoenix Core Team',
    region: 'Global',
    country: 'United States'
  },
  clojure_news: {
    id: 'clojure_news',
    name: 'Clojure News & Datomic',
    description: 'Dynamic functional language on the JVM, immutable persistent data structures, software transactional memory, and Datomic',
    enabled: true,
    protocol: 'rss',
    connector: 'clojure_news',
    baseUrl: 'https://clojure.org/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Rich Hickey & Clojure Team',
    region: 'Global',
    country: 'United States'
  }
};
