export interface ExtendedSourceDef {
  id: string;
  name: string;
  description: string;
  enabled: boolean;
  protocol: 'rss' | 'atom' | 'rest';
  connector: string;
  baseUrl: string;
  authType: 'none' | 'api_key' | 'bearer';
  categories: string[];
  fetchIntervalMinutes: number;
  timeoutMs: number;
  maxRetries: number;
  paginationSupport: boolean;
  searchSupport: boolean;
  requiresKey: boolean;
  rateLimitPerMinute: number;
  attribution: string;
  region: string;
  country?: string;
}

export const EXTENDED_SOURCES: Record<string, ExtendedSourceDef> = {
  // 1. AI Coding Assistants & Autonomous Agents
  cursor_blog: {
    id: 'cursor_blog',
    name: 'Cursor AI Blog',
    description: 'Official engineering and product updates from the AI-first code editor Cursor (Anysphere), covering speculative editing and agentic workflows',
    enabled: true,
    protocol: 'rss',
    connector: 'cursor_blog',
    baseUrl: 'https://www.cursor.com/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'ai-agents', 'programming'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cursor (Anysphere)',
    region: 'Global',
    country: 'United States'
  },
  replit_blog: {
    id: 'replit_blog',
    name: 'Replit Agent & Engineering',
    description: 'Autonomous software development, Replit Agent architectures, cloud developer environments, and containerized runtime systems',
    enabled: true,
    protocol: 'rss',
    connector: 'replit_blog',
    baseUrl: 'https://blog.replit.com/feed.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'ai-agents', 'startups'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Replit',
    region: 'Global',
    country: 'United States'
  },
  aider_blog: {
    id: 'aider_blog',
    name: 'Aider AI Pair Programming',
    description: 'State-of-the-art terminal AI coding assistant, git history integration, repository maps, and multi-file code editing benchmarks',
    enabled: true,
    protocol: 'rss',
    connector: 'aider_blog',
    baseUrl: 'https://aider.chat/blog/feed.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'programming', 'open-source-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Aider (Paul Gauthier)',
    region: 'Global',
    country: 'United States'
  },
  modal_labs: {
    id: 'modal_labs',
    name: 'Modal Labs AI Infrastructure',
    description: 'Serverless cloud compute, sub-second GPU container cold starts, distributed AI model hosting, and batch worker architectures',
    enabled: true,
    protocol: 'rss',
    connector: 'modal_labs',
    baseUrl: 'https://modal.com/blog/feed.xml',
    authType: 'none',
    categories: ['cloud', 'ai', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Modal Labs',
    region: 'Global',
    country: 'United States'
  },
  anyscale_blog: {
    id: 'anyscale_blog',
    name: 'Anyscale & Ray Systems',
    description: 'Distributed computing, Ray architecture, scalable LLM fine-tuning, high-throughput model serving, and cluster orchestration',
    enabled: true,
    protocol: 'rss',
    connector: 'anyscale_blog',
    baseUrl: 'https://www.anyscale.com/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'cloud', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Anyscale (Ray Project)',
    region: 'Global',
    country: 'United States'
  },
  bentoml_blog: {
    id: 'bentoml_blog',
    name: 'BentoML AI Serving',
    description: 'Unified model serving framework, BentoCloud, vLLM acceleration, and high-performance production inference pipelines',
    enabled: true,
    protocol: 'rss',
    connector: 'bentoml_blog',
    baseUrl: 'https://bentoml.com/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'open-source-ai', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'BentoML',
    region: 'Global',
    country: 'United States'
  },
  fireworks_ai: {
    id: 'fireworks_ai',
    name: 'Fireworks AI Research',
    description: 'Lightning-fast inference engines, speculative decoding, production model serving, and compound AI system architectures',
    enabled: true,
    protocol: 'rss',
    connector: 'fireworks_ai',
    baseUrl: 'https://fireworks.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'llms', 'cloud', 'developer-tools'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Fireworks AI',
    region: 'Global',
    country: 'United States'
  },
  fal_ai_blog: {
    id: 'fal_ai_blog',
    name: 'Fal.ai Generative Media',
    description: 'Ultra-fast diffusion pipelines, real-time video/image generation APIs, and serverless compute for creative multimodal models',
    enabled: true,
    protocol: 'rss',
    connector: 'fal_ai_blog',
    baseUrl: 'https://fal.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'generative-ai', 'cloud', 'developer-tools'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Fal.ai',
    region: 'Global',
    country: 'United States'
  },
  openrouter_blog: {
    id: 'openrouter_blog',
    name: 'OpenRouter AI Dispatches',
    description: 'Global LLM routing analytics, token volume trends, pricing economics, and latency benchmarks across foundation models',
    enabled: true,
    protocol: 'rss',
    connector: 'openrouter_blog',
    baseUrl: 'https://openrouter.ai/blog/feed.xml',
    authType: 'none',
    categories: ['ai', 'llms', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'OpenRouter',
    region: 'Global',
    country: 'United States'
  },
  sglang_project: {
    id: 'sglang_project',
    name: 'SGLang Serving Engine',
    description: 'Structured generation, RadixAttention KV cache reuse, and high-throughput LLM serving runtime benchmarks',
    enabled: true,
    protocol: 'rss',
    connector: 'sglang_project',
    baseUrl: 'https://sgl-project.github.io/feed.xml',
    authType: 'none',
    categories: ['ai', 'open-source-ai', 'llms', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'SGLang Team (LMSYS)',
    region: 'Global',
    country: 'United States'
  },
  lm_studio_blog: {
    id: 'lm_studio_blog',
    name: 'LM Studio Local AI',
    description: 'On-device LLM execution, GGUF and llama.cpp runtime optimizations, local agent tooling, and private desktop AI',
    enabled: true,
    protocol: 'rss',
    connector: 'lm_studio_blog',
    baseUrl: 'https://lmstudio.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'open-source-ai', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'LM Studio',
    region: 'Global',
    country: 'United States'
  },
  deepseek_news: {
    id: 'deepseek_news',
    name: 'DeepSeek AI Research',
    description: 'Open-weights frontier reasoning models, DeepSeek-R1 reinforcement learning, and Mixture-of-Experts architecture breakthroughs',
    enabled: true,
    protocol: 'rss',
    connector: 'deepseek_news',
    baseUrl: 'https://api.deepseek.com/news/rss.xml',
    authType: 'none',
    categories: ['ai', 'research', 'open-source-ai', 'llms'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'DeepSeek AI',
    region: 'Asia-Pacific',
    country: 'China'
  },
  qwen_ai: {
    id: 'qwen_ai',
    name: 'Qwen Team & Alibaba Cloud',
    description: 'Open foundation models, Qwen reasoning series, vision-language architectures, and code generation benchmarks',
    enabled: true,
    protocol: 'rss',
    connector: 'qwen_ai',
    baseUrl: 'https://qwenlm.github.io/blog/index.xml',
    authType: 'none',
    categories: ['ai', 'open-source-ai', 'models', 'research'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Qwen Team (Alibaba Cloud)',
    region: 'Asia-Pacific',
    country: 'China'
  },

  // 2. Vector Databases, Streaming & High-Performance Data Systems
  clickhouse_blog: {
    id: 'clickhouse_blog',
    name: 'ClickHouse Engineering',
    description: 'Real-time analytical database management, columnar storage, vectorized SIMD execution, and high-throughput event processing',
    enabled: true,
    protocol: 'rss',
    connector: 'clickhouse_blog',
    baseUrl: 'https://clickhouse.com/blog/rss.xml',
    authType: 'none',
    categories: ['technology', 'developer-tools', 'cloud', 'programming'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ClickHouse',
    region: 'Global',
    country: 'United States'
  },
  polars_blog: {
    id: 'polars_blog',
    name: 'Polars DataFrames',
    description: 'Blazingly fast multi-threaded DataFrame library written in Rust, query optimization, and memory-efficient data processing',
    enabled: true,
    protocol: 'rss',
    connector: 'polars_blog',
    baseUrl: 'https://pola.rs/posts/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'research', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Polars (Ritchie Vink)',
    region: 'Global',
    country: 'Netherlands'
  },
  apache_arrow_blog: {
    id: 'apache_arrow_blog',
    name: 'Apache Arrow & Parquet',
    description: 'Cross-language development platform for in-memory columnar data, zero-copy inter-process communication, and analytics acceleration',
    enabled: true,
    protocol: 'rss',
    connector: 'apache_arrow_blog',
    baseUrl: 'https://arrow.apache.org/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Apache Software Foundation',
    region: 'Global',
    country: 'United States'
  },
  redis_blog: {
    id: 'redis_blog',
    name: 'Redis Systems Engineering',
    description: 'In-memory caching architectures, Redis vector database enhancements, distributed cluster scaling, and low-latency storage',
    enabled: true,
    protocol: 'rss',
    connector: 'redis_blog',
    baseUrl: 'https://redis.io/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'cloud', 'technology', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Redis',
    region: 'Global',
    country: 'United States'
  },
  questdb_blog: {
    id: 'questdb_blog',
    name: 'QuestDB Time-Series',
    description: 'Fast open-source SQL time-series database, SIMD parallelized querying, financial market telemetry, and zero-GC Java design',
    enabled: true,
    protocol: 'rss',
    connector: 'questdb_blog',
    baseUrl: 'https://questdb.com/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'QuestDB',
    region: 'Global',
    country: 'United Kingdom'
  },
  lancedb_blog: {
    id: 'lancedb_blog',
    name: 'LanceDB Serverless Vector DB',
    description: 'Serverless multi-modal vector database built on the Lance columnar format, RAG retrieval benchmarks, and disk-based indexing',
    enabled: true,
    protocol: 'rss',
    connector: 'lancedb_blog',
    baseUrl: 'https://blog.lancedb.com/rss/',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'open-source-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'LanceDB',
    region: 'Global',
    country: 'United States'
  },
  chroma_blog: {
    id: 'chroma_blog',
    name: 'Chroma AI Vector Database',
    description: 'Open-source AI-native embedding database for LLM applications, document chunking, semantic retrieval, and agent memory',
    enabled: true,
    protocol: 'rss',
    connector: 'chroma_blog',
    baseUrl: 'https://www.trychroma.com/blog/feed.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'open-source-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Chroma',
    region: 'Global',
    country: 'United States'
  },
  milvus_blog: {
    id: 'milvus_blog',
    name: 'Milvus Distributed Vector DB',
    description: 'Billion-scale similarity search, distributed vector database architectures, HNSW indexing, and multimodal search at hyperscale',
    enabled: true,
    protocol: 'rss',
    connector: 'milvus_blog',
    baseUrl: 'https://milvus.io/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'open-source-ai', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Milvus (LF AI & Data)',
    region: 'Global',
    country: 'United States'
  },

  // 3. Cloud Runtimes, Tooling & Systems Engineering
  docker_engineering: {
    id: 'docker_engineering',
    name: 'Docker Engineering',
    description: 'Container runtimes, BuildKit performance, Docker Desktop enhancements, container security, and developer productivity',
    enabled: true,
    protocol: 'rss',
    connector: 'docker_engineering',
    baseUrl: 'https://www.docker.com/blog/feed/',
    authType: 'none',
    categories: ['developer-tools', 'cloud', 'programming', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Docker',
    region: 'Global',
    country: 'United States'
  },
  prisma_engineering: {
    id: 'prisma_engineering',
    name: 'Prisma Data & ORM',
    description: 'Next-generation ORM, type-safe database access, schema migrations, edge caching with Accelerate, and serverless queries',
    enabled: true,
    protocol: 'rss',
    connector: 'prisma_engineering',
    baseUrl: 'https://www.prisma.io/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Prisma',
    region: 'Global',
    country: 'Germany'
  },
  biome_blog: {
    id: 'biome_blog',
    name: 'Biome Formatter & Linter',
    description: 'Rust-based ultra-fast formatter and linter for JavaScript, TypeScript, JSX, and JSON, modernizing web developer tooling',
    enabled: true,
    protocol: 'rss',
    connector: 'biome_blog',
    baseUrl: 'https://biomejs.dev/feed.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'open-source-ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Biome Project',
    region: 'Global',
    country: 'United States'
  },
  zig_foundation: {
    id: 'zig_foundation',
    name: 'Zig Software Foundation',
    description: 'Systems programming language without hidden control flow, memory allocations, or libc dependency; comptime metaprogramming',
    enabled: true,
    protocol: 'rss',
    connector: 'zig_foundation',
    baseUrl: 'https://ziglang.org/news/index.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Zig Software Foundation',
    region: 'Global',
    country: 'United States'
  },
  cloudflare_engineering: {
    id: 'cloudflare_engineering',
    name: 'Cloudflare Systems Engineering',
    description: 'Global Anycast network architecture, edge compute runtimes, Rust network stacks, DNS infrastructure, and DDoS mitigation',
    enabled: true,
    protocol: 'rss',
    connector: 'cloudflare_engineering',
    baseUrl: 'https://blog.cloudflare.com/rss/',
    authType: 'none',
    categories: ['cloud', 'technology', 'cybersecurity', 'developer-tools'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cloudflare',
    region: 'Global',
    country: 'United States'
  },
  github_next: {
    id: 'github_next',
    name: 'GitHub Next Research',
    description: 'Speculative prototypes, Copilot Workspace, voice coding, and exploring the frontier of AI-assisted software craftsmanship',
    enabled: true,
    protocol: 'rss',
    connector: 'github_next',
    baseUrl: 'https://github.next/feed.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'research', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'GitHub Next',
    region: 'Global',
    country: 'United States'
  },

  // 4. Next-Gen AI Hardware, Silicon & Quantum Computing
  tenstorrent_blog: {
    id: 'tenstorrent_blog',
    name: 'Tenstorrent AI Silicon',
    description: 'RISC-V processor architecture, Wormhole and Blackhole AI accelerators, and open-source software stacks led by Jim Keller',
    enabled: true,
    protocol: 'rss',
    connector: 'tenstorrent_blog',
    baseUrl: 'https://tenstorrent.com/feed.xml',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'ai', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Tenstorrent',
    region: 'Global',
    country: 'Canada'
  },
  dwave_quantum: {
    id: 'dwave_quantum',
    name: 'D-Wave Quantum Systems',
    description: 'Quantum annealing systems, Advantage processor architectures, hybrid classical-quantum solvers, and enterprise combinatorial optimization',
    enabled: true,
    protocol: 'rss',
    connector: 'dwave_quantum',
    baseUrl: 'https://www.dwavesys.com/feed.xml',
    authType: 'none',
    categories: ['quantum-computing', 'research', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'D-Wave Quantum Inc.',
    region: 'Global',
    country: 'Canada'
  },
  graphcore_blog: {
    id: 'graphcore_blog',
    name: 'Graphcore IPU Intelligence',
    description: 'Intelligence Processing Units, massively parallel graph computation, fine-grained silicon parallelism, and machine intelligence models',
    enabled: true,
    protocol: 'rss',
    connector: 'graphcore_blog',
    baseUrl: 'https://www.graphcore.ai/posts/rss.xml',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'ai', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Graphcore (SoftBank)',
    region: 'Europe',
    country: 'United Kingdom'
  },
  sambanova_blog: {
    id: 'sambanova_blog',
    name: 'SambaNova Systems',
    description: 'Reconfigurable Dataflow Architecture (RDA), full-stack enterprise AI platforms, ultra-fast 1,000+ tps Llama-3 serving appliances',
    enabled: true,
    protocol: 'rss',
    connector: 'sambanova_blog',
    baseUrl: 'https://sambanova.ai/feed.xml',
    authType: 'none',
    categories: ['ai-hardware', 'ai', 'cloud', 'enterprise'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'SambaNova Systems',
    region: 'Global',
    country: 'United States'
  },
  untether_ai: {
    id: 'untether_ai',
    name: 'Untether AI Spatial Compute',
    description: 'At-memory compute architectures, ultra-high energy efficiency neural acceleration, and autonomous vehicle inference silicon',
    enabled: true,
    protocol: 'rss',
    connector: 'untether_ai',
    baseUrl: 'https://www.untether.ai/blog-feed.xml',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Untether AI',
    region: 'Global',
    country: 'Canada'
  },
  hailo_ai: {
    id: 'hailo_ai',
    name: 'Hailo Edge AI Processors',
    description: 'Top-tier edge AI microprocessors, deep learning acceleration for embedded systems, smart cameras, and industrial robotics',
    enabled: true,
    protocol: 'rss',
    connector: 'hailo_ai',
    baseUrl: 'https://hailo.ai/blog/feed.xml',
    authType: 'none',
    categories: ['ai-hardware', 'robotics', 'ai', 'semiconductors'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Hailo Technologies',
    region: 'Global',
    country: 'Israel'
  },

  // 5. Cloud Security, Vulnerabilities & Enterprise Threat Research
  redhat_security: {
    id: 'redhat_security',
    name: 'Red Hat Security Advisories',
    description: 'Enterprise Linux CVE tracking, kernel security vulnerability updates, SELinux policies, and OpenShift container defense',
    enabled: true,
    protocol: 'rss',
    connector: 'redhat_security',
    baseUrl: 'https://access.redhat.com/security/data/metrics/rhsa.rss',
    authType: 'none',
    categories: ['cybersecurity', 'cloud', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Red Hat Security',
    region: 'Global',
    country: 'United States'
  },
  unit42_threats: {
    id: 'unit42_threats',
    name: 'Palo Alto Networks Unit 42',
    description: 'World-renowned threat intelligence, nation-state advanced persistent threat (APT) tracking, ransomware campaigns, and zero-day forensics',
    enabled: true,
    protocol: 'rss',
    connector: 'unit42_threats',
    baseUrl: 'https://unit42.paloaltonetworks.com/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Palo Alto Networks Unit 42',
    region: 'Global',
    country: 'United States'
  },
  sentinelone_labs: {
    id: 'sentinelone_labs',
    name: 'SentinelLabs Threat Research',
    description: 'Deep technical research on adversary tradecraft, macOS and Linux malware reverse engineering, and cloud security exploits',
    enabled: true,
    protocol: 'rss',
    connector: 'sentinelone_labs',
    baseUrl: 'https://www.sentinelone.com/labs/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'SentinelLabs',
    region: 'Global',
    country: 'United States'
  },
  wiz_security_research: {
    id: 'wiz_security_research',
    name: 'Wiz Cloud Security Research',
    description: 'Discovery of hyperscaler cloud isolation bypasses, cross-tenant vulnerabilities, Kubernetes exploits, and AI infrastructure risks',
    enabled: true,
    protocol: 'rss',
    connector: 'wiz_security_research',
    baseUrl: 'https://www.wiz.io/blog/rss.xml',
    authType: 'none',
    categories: ['cybersecurity', 'cloud', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Wiz Research',
    region: 'Global',
    country: 'United States'
  },
  aqua_security: {
    id: 'aqua_security',
    name: 'Aqua Security Team Nautilus',
    description: 'Honeypot telemetry, cloud-native container attacks, supply chain compromise techniques, and Kubernetes threat vectors',
    enabled: true,
    protocol: 'rss',
    connector: 'aqua_security',
    baseUrl: 'https://blog.aquasec.com/rss.xml',
    authType: 'none',
    categories: ['cybersecurity', 'cloud', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Aqua Security Nautilus',
    region: 'Global',
    country: 'United States'
  },

  // 6. Independent & Investigative Technology Journalism
  four_zero_four_media: {
    id: 'four_zero_four_media',
    name: '404 Media',
    description: 'Groundbreaking independent investigative journalism on hacking, privacy violations, AI ethics, digital rights, and surveillance capitalism',
    enabled: true,
    protocol: 'rss',
    connector: 'four_zero_four_media',
    baseUrl: 'https://www.404media.co/rss/',
    authType: 'none',
    categories: ['technology', 'cybersecurity', 'ethics', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: '404 Media',
    region: 'Global',
    country: 'United States'
  },
  platformer_news: {
    id: 'platformer_news',
    name: 'Platformer (Casey Newton)',
    description: 'Essential reporting at the intersection of big tech monopolies, social networks, AI governance, and democratic institutions',
    enabled: true,
    protocol: 'rss',
    connector: 'platformer_news',
    baseUrl: 'https://www.platformer.news/rss/',
    authType: 'none',
    categories: ['technology', 'ai', 'policy'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Platformer (Casey Newton)',
    region: 'Global',
    country: 'United States'
  },
  garbage_day: {
    id: 'garbage_day',
    name: 'Garbage Day (Ryan Broderick)',
    description: 'Tracking internet culture, algorithmic sludge, memes, generative AI oddities, and digital media platform evolution',
    enabled: true,
    protocol: 'rss',
    connector: 'garbage_day',
    baseUrl: 'https://www.garbageday.email/feed',
    authType: 'none',
    categories: ['technology', 'social-media', 'ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Garbage Day (Ryan Broderick)',
    region: 'Global',
    country: 'United States'
  },
  techdirt: {
    id: 'techdirt',
    name: 'Techdirt (Mike Masnick)',
    description: 'Digital civil liberties, Section 230 platform speech laws, copyright jurisprudence, patent reform, and technology regulation',
    enabled: true,
    protocol: 'rss',
    connector: 'techdirt',
    baseUrl: 'https://www.techdirt.com/feed/',
    authType: 'none',
    categories: ['technology', 'policy', 'ethics'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Techdirt (Mike Masnick)',
    region: 'Global',
    country: 'United States'
  },
  the_information_tech: {
    id: 'the_information_tech',
    name: 'The Information AI & Tech',
    description: 'High-impact investigative technology reporting, venture capital financing scoops, founder drama, and artificial intelligence boardroom shifts',
    enabled: true,
    protocol: 'rss',
    connector: 'the_information_tech',
    baseUrl: 'https://www.theinformation.com/feed',
    authType: 'none',
    categories: ['technology', 'ai', 'startups'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'The Information',
    region: 'Global',
    country: 'United States'
  },
  semafor_tech: {
    id: 'semafor_tech',
    name: 'Semafor Technology',
    description: 'Global technology journalism, semiconductor trade policies, Chinese AI advancements, and hyperscaler geopolitics',
    enabled: true,
    protocol: 'rss',
    connector: 'semafor_tech',
    baseUrl: 'https://www.semafor.com/feed/tech.xml',
    authType: 'none',
    categories: ['technology', 'ai', 'policy'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Semafor Media',
    region: 'Global',
    country: 'United States'
  },

  // 7. Premier AI Podcasts & Media
  hard_fork_nyt: {
    id: 'hard_fork_nyt',
    name: 'Hard Fork (New York Times)',
    description: 'Kevin Roose and Casey Newton exploring rapid AI developments, Silicon Valley power shifts, and technological disruptions',
    enabled: true,
    protocol: 'rss',
    connector: 'hard_fork_nyt',
    baseUrl: 'https://feeds.simplecast.com/54nAGcIl',
    authType: 'none',
    categories: ['ai', 'technology', 'podcast'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'The New York Times',
    region: 'Global',
    country: 'United States'
  },
  no_priors_ai: {
    id: 'no_priors_ai',
    name: 'No Priors AI Podcast',
    description: 'Elad Gil and Sarah Guo interviewing leading founders, researchers, and engineers building the artificial intelligence revolution',
    enabled: true,
    protocol: 'rss',
    connector: 'no_priors_ai',
    baseUrl: 'https://feeds.megaphone.fm/nopriors',
    authType: 'none',
    categories: ['ai', 'startups', 'podcast', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'No Priors (Elad Gil & Sarah Guo)',
    region: 'Global',
    country: 'United States'
  },
  dwarkesh_podcast: {
    id: 'dwarkesh_podcast',
    name: 'Dwarkesh Podcast',
    description: 'In-depth longform technical dialogues with leading AI scientists, semiconductor architects, and frontier lab executives',
    enabled: true,
    protocol: 'rss',
    connector: 'dwarkesh_podcast',
    baseUrl: 'https://feed.podbean.com/dwarkesh/feed.xml',
    authType: 'none',
    categories: ['ai', 'research', 'podcast', 'semiconductors'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Dwarkesh Patel',
    region: 'Global',
    country: 'United States'
  }
};
