import { ExtendedSourceDef } from './extended_sources.js';

export const FRONTIER_SOURCES: Record<string, ExtendedSourceDef> = {
  // ==========================================
  // 1. AI Safety, Alignment & Evaluators
  // ==========================================
  metr_evals: {
    id: 'metr_evals',
    name: 'METR (Model Evaluation & Threat Research)',
    description: 'Empirical evaluations of autonomous replication, cyber capability thresholds, and catastrophic risks in frontier AI systems',
    enabled: true,
    protocol: 'rss',
    connector: 'metr_evals',
    baseUrl: 'https://metr.org/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'research', 'cybersecurity'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'METR Research',
    region: 'Global',
    country: 'United States'
  },
  redwood_research: {
    id: 'redwood_research',
    name: 'Redwood Research (Applied Alignment)',
    description: 'Applied AI alignment, adversarial training, causal scrubbing, and mechanistic interpretability of transformer internals',
    enabled: true,
    protocol: 'rss',
    connector: 'redwood_research',
    baseUrl: 'https://www.redwoodresearch.org/rss.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Redwood Research',
    region: 'Global',
    country: 'United States'
  },
  cais_safety: {
    id: 'cais_safety',
    name: 'Center for AI Safety (CAIS)',
    description: 'Frontier AI safety research, compute governance, catastrophic risk benchmarks, and technical safety frameworks',
    enabled: true,
    protocol: 'rss',
    connector: 'cais_safety',
    baseUrl: 'https://www.safe.ai/news/rss.xml',
    authType: 'none',
    categories: ['ai', 'research', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Center for AI Safety',
    region: 'Global',
    country: 'United States'
  },
  uk_aisi_research: {
    id: 'uk_aisi_research',
    name: 'AI Safety Institute (AISI)',
    description: 'Government-backed empirical testing of advanced AI models for societal harm, national security risks, and safeguard evasion',
    enabled: true,
    protocol: 'rss',
    connector: 'uk_aisi_research',
    baseUrl: 'https://www.aisi.gov.uk/feed.xml',
    authType: 'none',
    categories: ['ai', 'research', 'cybersecurity'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'UK AI Safety Institute',
    region: 'Europe',
    country: 'United Kingdom'
  },
  future_of_life_institute: {
    id: 'future_of_life_institute',
    name: 'Future of Life Institute (FLI)',
    description: 'Mitigating existential and global catastrophic risks from advanced artificial intelligence, biotechnology, and autonomous systems',
    enabled: true,
    protocol: 'rss',
    connector: 'future_of_life_institute',
    baseUrl: 'https://futureoflife.org/feed/',
    authType: 'none',
    categories: ['ai', 'technology', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Future of Life Institute',
    region: 'Global',
    country: 'United States'
  },
  transformer_circuits: {
    id: 'transformer_circuits',
    name: 'Transformer Circuits Thread',
    description: 'Anthropic mechanistic interpretability research, superposition, sparse autoencoders (SAEs), and feature visualization in LLMs',
    enabled: true,
    protocol: 'rss',
    connector: 'transformer_circuits',
    baseUrl: 'https://transformer-circuits.pub/rss.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Anthropic Interpretability Team',
    region: 'Global',
    country: 'United States'
  },
  lesswrong_ai: {
    id: 'lesswrong_ai',
    name: 'LessWrong AI Alignment',
    description: 'Community-driven research on AI alignment, decision theory, agent foundations, predictive processing, and rationality',
    enabled: true,
    protocol: 'rss',
    connector: 'lesswrong_ai',
    baseUrl: 'https://www.lesswrong.com/feed.xml?view=curated-rss',
    authType: 'none',
    categories: ['ai', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'LessWrong / Lightcone Infrastructure',
    region: 'Global',
    country: 'United States'
  },
  autogen_microsoft: {
    id: 'autogen_microsoft',
    name: 'Microsoft AutoGen Framework',
    description: 'Multi-agent conversation patterns, autonomous tool orchestration, code execution sandboxes, and human-in-the-loop workflows',
    enabled: true,
    protocol: 'rss',
    connector: 'autogen_microsoft',
    baseUrl: 'https://github.com/microsoft/autogen/releases.atom',
    authType: 'none',
    categories: ['ai', 'ai-agents', 'open-source-ai', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Microsoft Research',
    region: 'Global',
    country: 'United States'
  },
  crewai_blog: {
    id: 'crewai_blog',
    name: 'CrewAI Multi-Agent Systems',
    description: 'Role-playing autonomous AI agents, multi-agent collaboration frameworks, enterprise tools, and production task automation',
    enabled: true,
    protocol: 'rss',
    connector: 'crewai_blog',
    baseUrl: 'https://blog.crewai.com/rss/',
    authType: 'none',
    categories: ['ai', 'ai-agents', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'CrewAI Inc.',
    region: 'Global',
    country: 'United States'
  },
  dspy_stanford: {
    id: 'dspy_stanford',
    name: 'DSPy (Stanford NLP)',
    description: 'Programming—not prompting—foundation models: declarative LM pipelines, automatic prompt compilation, and metric optimization',
    enabled: true,
    protocol: 'rss',
    connector: 'dspy_stanford',
    baseUrl: 'https://github.com/stanfordnlp/dspy/releases.atom',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'programming', 'open-source-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Stanford NLP Group',
    region: 'Americas',
    country: 'United States'
  },

  // ==========================================
  // 2. Serverless AI, GPU Clouds & Inference Orchestration
  // ==========================================
  modal_labs_blog: {
    id: 'modal_labs_blog',
    name: 'Modal Labs Cloud & GPU',
    description: 'Serverless container platform for AI, instant GPU cold starts, distributed model fine-tuning, and Python infrastructure',
    enabled: true,
    protocol: 'rss',
    connector: 'modal_labs_blog',
    baseUrl: 'https://modal.com/blog/feed.xml',
    authType: 'none',
    categories: ['cloud', 'ai', 'ai-hardware', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Modal Labs',
    region: 'Global',
    country: 'United States'
  },
  runpod_blog: {
    id: 'runpod_blog',
    name: 'RunPod Serverless Cloud',
    description: 'Globally distributed GPU cloud, serverless vLLM endpoints, autoscaling inference workers, and high-performance computing',
    enabled: true,
    protocol: 'rss',
    connector: 'runpod_blog',
    baseUrl: 'https://blog.runpod.io/rss/',
    authType: 'none',
    categories: ['cloud', 'ai', 'ai-hardware', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'RunPod Inc.',
    region: 'Global',
    country: 'United States'
  },
  together_ai_blog: {
    id: 'together_ai_blog',
    name: 'Together AI Engineering',
    description: 'Fast open-source model inference engine, FlashAttention optimizations, custom LoRA fine-tuning, and RedPajama datasets',
    enabled: true,
    protocol: 'rss',
    connector: 'together_ai_blog',
    baseUrl: 'https://www.together.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'cloud', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Together AI',
    region: 'Global',
    country: 'United States'
  },
  fireworks_ai_blog: {
    id: 'fireworks_ai_blog',
    name: 'Fireworks AI Fast Inference',
    description: 'Sub-millisecond latency LLM serving, speculative decoding engines, FireFunction function-calling models, and enterprise API',
    enabled: true,
    protocol: 'rss',
    connector: 'fireworks_ai_blog',
    baseUrl: 'https://blog.fireworks.ai/feed',
    authType: 'none',
    categories: ['ai', 'cloud', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Fireworks AI',
    region: 'Global',
    country: 'United States'
  },
  anyscale_ray_blog: {
    id: 'anyscale_ray_blog',
    name: 'Anyscale & Ray Framework',
    description: 'Distributed computing for Python and AI, Ray Train, Ray Serve, Ray Data, and production LLM scaling architecture',
    enabled: true,
    protocol: 'rss',
    connector: 'anyscale_ray_blog',
    baseUrl: 'https://www.anyscale.com/blog/rss.xml',
    authType: 'none',
    categories: ['cloud', 'ai', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Anyscale Inc.',
    region: 'Global',
    country: 'United States'
  },
  hyperbolic_ai: {
    id: 'hyperbolic_ai',
    name: 'Hyperbolic Decentralized AI',
    description: 'Verifiable AI inference, decentralized heterogeneous GPU marketplace, Proof of Sampling (PoSP), and open compute clusters',
    enabled: true,
    protocol: 'rss',
    connector: 'hyperbolic_ai',
    baseUrl: 'https://hyperbolic.xyz/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'cloud', 'ai-hardware'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Hyperbolic Labs',
    region: 'Global',
    country: 'United States'
  },
  fal_ai_research: {
    id: 'fal_ai_research',
    name: 'fal.ai Generative Media Engine',
    description: 'Real-time diffusion inference, SDXL Lightning, Flux fast pipelines, camera trajectory rendering, and serverless media APIs',
    enabled: true,
    protocol: 'rss',
    connector: 'fal_ai_research',
    baseUrl: 'https://fal.ai/blog/feed.xml',
    authType: 'none',
    categories: ['ai', 'generative-ai', 'computer-vision', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'fal.ai',
    region: 'Global',
    country: 'United States'
  },
  bfl_flux_ai: {
    id: 'bfl_flux_ai',
    name: 'Black Forest Labs (FLUX.1)',
    description: 'FLUX.1 12B parameter rectified flow transformer models, text-to-image synthesis, visual quality, and model licensing',
    enabled: true,
    protocol: 'rss',
    connector: 'bfl_flux_ai',
    baseUrl: 'https://blackforestlabs.ai/feed/',
    authType: 'none',
    categories: ['ai', 'generative-ai', 'computer-vision', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Black Forest Labs',
    region: 'Europe',
    country: 'Germany'
  },
  replicate_changelog: {
    id: 'replicate_changelog',
    name: 'Replicate Platform & Changelog',
    description: 'Running open-source machine learning models via cloud APIs, Cog containerization, fast boot times, and model releases',
    enabled: true,
    protocol: 'rss',
    connector: 'replicate_changelog',
    baseUrl: 'https://replicate.com/blog/rss',
    authType: 'none',
    categories: ['cloud', 'ai', 'developer-tools', 'generative-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Replicate Inc.',
    region: 'Global',
    country: 'United States'
  },
  tigris_data: {
    id: 'tigris_data',
    name: 'Tigris Data Globally Distributed Storage',
    description: 'Global S3-compatible object storage, low-latency distributed caching, edge synchronization, and cloud storage architecture',
    enabled: true,
    protocol: 'rss',
    connector: 'tigris_data',
    baseUrl: 'https://www.tigrisdata.com/blog/rss.xml',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Tigris Data',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 3. Developer Intelligence & AI Code Editors
  // ==========================================
  cursor_ai_blog: {
    id: 'cursor_ai_blog',
    name: 'Cursor AI & Anysphere',
    description: 'AI-first code editor architecture, shadow workspace speculative edits, multi-file codebase indexing, and fast code diffs',
    enabled: true,
    protocol: 'rss',
    connector: 'cursor_ai_blog',
    baseUrl: 'https://www.cursor.com/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Anysphere Inc.',
    region: 'Global',
    country: 'United States'
  },
  zed_editor_blog: {
    id: 'zed_editor_blog',
    name: 'Zed High-Performance Editor',
    description: 'GPU-accelerated code editor written in Rust, CRDT-based real-time multiplayer, GPUI framework, and semantic language servers',
    enabled: true,
    protocol: 'rss',
    connector: 'zed_editor_blog',
    baseUrl: 'https://zed.dev/blog.rss',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'open-source-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Zed Industries',
    region: 'Global',
    country: 'United States'
  },
  continue_dev_blog: {
    id: 'continue_dev_blog',
    name: 'Continue Open-Source AI Coding',
    description: 'Modular open-source AI code assistant, custom LLM routing, codebase context providers, and VS Code/JetBrains integration',
    enabled: true,
    protocol: 'rss',
    connector: 'continue_dev_blog',
    baseUrl: 'https://blog.continue.dev/rss/',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'open-source-ai', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Continue Dev Inc.',
    region: 'Global',
    country: 'United States'
  },
  sourcegraph_cody: {
    id: 'sourcegraph_cody',
    name: 'Sourcegraph Cody & Code Intelligence',
    description: 'Enterprise code graph analysis, repository-wide context embeddings, AST parsing, and AI coding assistants',
    enabled: true,
    protocol: 'rss',
    connector: 'sourcegraph_cody',
    baseUrl: 'https://sourcegraph.com/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'ai', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Sourcegraph Inc.',
    region: 'Global',
    country: 'United States'
  },
  warp_terminal_blog: {
    id: 'warp_terminal_blog',
    name: 'Warp Modern Terminal',
    description: 'Modern Rust-powered terminal, AI command search, block-based output navigation, and cloud collaborative workflows',
    enabled: true,
    protocol: 'rss',
    connector: 'warp_terminal_blog',
    baseUrl: 'https://www.warp.dev/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Warp Technologies',
    region: 'Global',
    country: 'United States'
  },
  resend_blog: {
    id: 'resend_blog',
    name: 'Resend Developer Platform',
    description: 'Email API for developers, React Email components, deliverability infrastructure, and low-latency transactional messaging',
    enabled: true,
    protocol: 'rss',
    connector: 'resend_blog',
    baseUrl: 'https://resend.com/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'cloud'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Resend Inc.',
    region: 'Global',
    country: 'United States'
  },
  haystack_deepset: {
    id: 'haystack_deepset',
    name: 'Haystack by deepset',
    description: 'Modular open-source framework for building production RAG pipelines, neural search, and multi-component agentic flows',
    enabled: true,
    protocol: 'rss',
    connector: 'haystack_deepset',
    baseUrl: 'https://haystack.deepset.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'open-source-ai', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'deepset GmbH',
    region: 'Europe',
    country: 'Germany'
  },
  scale_ai_engineering: {
    id: 'scale_ai_engineering',
    name: 'Scale AI Engineering',
    description: 'RLHF data pipelines, expert red-teaming, enterprise LLM fine-tuning datasets, and synthetic ground-truth annotation',
    enabled: true,
    protocol: 'rss',
    connector: 'scale_ai_engineering',
    baseUrl: 'https://scale.com/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Scale AI',
    region: 'Global',
    country: 'United States'
  },
  snorkel_ai: {
    id: 'snorkel_ai',
    name: 'Snorkel AI Programmatic Data',
    description: 'Weak supervision, programmatic data labeling, foundation model adaptation, and enterprise dataset curation',
    enabled: true,
    protocol: 'rss',
    connector: 'snorkel_ai',
    baseUrl: 'https://snorkel.ai/feed/',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Snorkel AI',
    region: 'Global',
    country: 'United States'
  },
  cleanlab_ai: {
    id: 'cleanlab_ai',
    name: 'Cleanlab Data-Centric AI',
    description: 'Confident learning algorithms, automated label error detection in training datasets, and out-of-distribution evaluation',
    enabled: true,
    protocol: 'rss',
    connector: 'cleanlab_ai',
    baseUrl: 'https://cleanlab.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'open-source-ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cleanlab Inc.',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 4. Speech Synthesis & Audio AI
  // ==========================================
  elevenlabs_tech: {
    id: 'elevenlabs_tech',
    name: 'ElevenLabs Research & Audio AI',
    description: 'Neural speech synthesis, low-latency multilingual voice generation, emotion conditioning, and acoustic sound effect models',
    enabled: true,
    protocol: 'rss',
    connector: 'elevenlabs_tech',
    baseUrl: 'https://elevenlabs.io/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'generative-ai', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ElevenLabs Inc.',
    region: 'Global',
    country: 'United States'
  },
  suno_ai_research: {
    id: 'suno_ai_research',
    name: 'Suno AI Music Generation',
    description: 'Generative musical diffusion models, full-song vocal and instrumental synthesis, and audio representation learning',
    enabled: true,
    protocol: 'rss',
    connector: 'suno_ai_research',
    baseUrl: 'https://suno.com/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'generative-ai', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Suno Inc.',
    region: 'Global',
    country: 'United States'
  },
  cartesia_sonic: {
    id: 'cartesia_sonic',
    name: 'Cartesia Sonic Speech Engine',
    description: 'State Space Models (SSMs) for ultra-fast streaming speech, sub-150ms real-time audio latency, and voice generation',
    enabled: true,
    protocol: 'rss',
    connector: 'cartesia_sonic',
    baseUrl: 'https://cartesia.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'generative-ai', 'research', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cartesia AI',
    region: 'Global',
    country: 'United States'
  },
  kyutai_labs: {
    id: 'kyutai_labs',
    name: 'Kyutai Labs (Moshi Conversational AI)',
    description: 'Moshi multimodal voice-to-voice foundation model, open-weights conversational audio, and low-latency speech modeling',
    enabled: true,
    protocol: 'rss',
    connector: 'kyutai_labs',
    baseUrl: 'https://kyutai.org/feed.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'open-source-ai', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Kyutai Lab',
    region: 'Europe',
    country: 'France'
  },
  playht_ai: {
    id: 'playht_ai',
    name: 'PlayHT Voice Generation',
    description: 'PlayDialog multi-speaker conversational models, streaming TTS WebSockets, and voice cloning architectures',
    enabled: true,
    protocol: 'rss',
    connector: 'playht_ai',
    baseUrl: 'https://play.ht/blog/rss/',
    authType: 'none',
    categories: ['ai', 'generative-ai', 'developer-tools'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'PlayHT Inc.',
    region: 'Global',
    country: 'United States'
  },
  argilla_io: {
    id: 'argilla_io',
    name: 'Argilla Open Data Curation',
    description: 'Open-source feedback loops, human preference datasets for RLHF, synthetic data verification, and DPO alignment tools',
    enabled: true,
    protocol: 'rss',
    connector: 'argilla_io',
    baseUrl: 'https://argilla.io/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'open-source-ai', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Argilla Technologies',
    region: 'Europe',
    country: 'Spain'
  },

  // ==========================================
  // 5. Cloud Native, Service Mesh & eBPF Networking
  // ==========================================
  cncf_blog: {
    id: 'cncf_blog',
    name: 'Cloud Native Computing Foundation (CNCF)',
    description: 'Kubernetes graduated projects, cloud native landscape, Envoy, Helm, Jaeger, and microservice infrastructure standards',
    enabled: true,
    protocol: 'rss',
    connector: 'cncf_blog',
    baseUrl: 'https://www.cncf.io/feed/',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cloud Native Computing Foundation',
    region: 'Global',
    country: 'United States'
  },
  cilium_ebpf: {
    id: 'cilium_ebpf',
    name: 'Cilium & eBPF Project',
    description: 'Extended Berkeley Packet Filter (eBPF) Linux kernel programming, transparent network security, Tetragon, and Hubble observability',
    enabled: true,
    protocol: 'rss',
    connector: 'cilium_ebpf',
    baseUrl: 'https://cilium.io/blog/rss.xml',
    authType: 'none',
    categories: ['cloud', 'cybersecurity', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Isovalent / Cisco',
    region: 'Global',
    country: 'United States'
  },
  envoy_proxy: {
    id: 'envoy_proxy',
    name: 'Envoy Proxy Architecture',
    description: 'Cloud-native high-performance edge/middle/service proxy, dynamic xDS discovery API, and HTTP/3 service communication',
    enabled: true,
    protocol: 'rss',
    connector: 'envoy_proxy',
    baseUrl: 'https://blog.envoyproxy.io/feed',
    authType: 'none',
    categories: ['cloud', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Envoy Project Maintainers',
    region: 'Global',
    country: 'United States'
  },
  istio_mesh: {
    id: 'istio_mesh',
    name: 'Istio Service Mesh',
    description: 'Zero-trust workload mutual TLS (mTLS), ambient mesh sidecarless data plane, traffic routing, and policy enforcement',
    enabled: true,
    protocol: 'rss',
    connector: 'istio_mesh',
    baseUrl: 'https://istio.io/latest/blog/index.xml',
    authType: 'none',
    categories: ['cloud', 'cybersecurity', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Istio Project / CNCF',
    region: 'Global',
    country: 'United States'
  },
  hashicorp_eng: {
    id: 'hashicorp_eng',
    name: 'HashiCorp Engineering',
    description: 'Infrastructure as code, Terraform core design, Vault secrets management, Consul service networking, and Nomad scheduling',
    enabled: true,
    protocol: 'rss',
    connector: 'hashicorp_eng',
    baseUrl: 'https://www.hashicorp.com/blog/feed.xml',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'cybersecurity'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'HashiCorp (IBM)',
    region: 'Global',
    country: 'United States'
  },
  kong_gateway: {
    id: 'kong_gateway',
    name: 'Kong Cloud-Native API Gateway',
    description: 'High-performance OpenResty/Nginx API gateway, Kong Konnect platform, WebAssembly plugins, and microservice governance',
    enabled: true,
    protocol: 'rss',
    connector: 'kong_gateway',
    baseUrl: 'https://konghq.com/blog/feed',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Kong Inc.',
    region: 'Global',
    country: 'United States'
  },
  traefik_labs: {
    id: 'traefik_labs',
    name: 'Traefik Labs Ingress & Proxy',
    description: 'Cloud native reverse proxy, automatic Let\'s Encrypt SSL/TLS certificates, Traefik Hub, and Kubernetes Gateway API',
    enabled: true,
    protocol: 'rss',
    connector: 'traefik_labs',
    baseUrl: 'https://traefik.io/rss.xml',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Traefik Labs',
    region: 'Europe',
    country: 'France'
  },
  grafana_labs_blog: {
    id: 'grafana_labs_blog',
    name: 'Grafana Labs Observability',
    description: 'Unified dashboards, Loki log aggregation, Tempo distributed tracing, Mimir metrics scale, and OpenTelemetry integrations',
    enabled: true,
    protocol: 'rss',
    connector: 'grafana_labs_blog',
    baseUrl: 'https://grafana.com/blog/index.xml',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Grafana Labs',
    region: 'Global',
    country: 'United States'
  },
  prometheus_monitoring: {
    id: 'prometheus_monitoring',
    name: 'Prometheus Monitoring System',
    description: 'PromQL query language, multi-dimensional time series data model, service discovery, and Alertmanager routing',
    enabled: true,
    protocol: 'rss',
    connector: 'prometheus_monitoring',
    baseUrl: 'https://prometheus.io/feed.xml',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'open-source-ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Prometheus Project / CNCF',
    region: 'Global',
    country: 'Germany'
  },
  oxide_computer: {
    id: 'oxide_computer',
    name: 'Oxide Computer Company',
    description: 'Hardware-software co-design, commercial rack-scale computing, open-source Rust firmware (Hubris/Humility), and illumos hypervisors',
    enabled: true,
    protocol: 'rss',
    connector: 'oxide_computer',
    baseUrl: 'https://oxide.computer/blog/rss.xml',
    authType: 'none',
    categories: ['ai-hardware', 'cloud', 'programming', 'semiconductors'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Oxide Computer Company',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 6. Compilers, Language Runtimes & Low-Level Toolchains
  // ==========================================
  llvm_project_blog: {
    id: 'llvm_project_blog',
    name: 'LLVM Compiler Infrastructure',
    description: 'Intermediate representation (LLVM IR), Clang C/C++ compiler, MLIR multi-level intermediate representation, and backend codegen',
    enabled: true,
    protocol: 'rss',
    connector: 'llvm_project_blog',
    baseUrl: 'https://blog.llvm.org/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'LLVM Foundation',
    region: 'Global',
    country: 'United States'
  },
  bytecode_alliance_wasm: {
    id: 'bytecode_alliance_wasm',
    name: 'Bytecode Alliance (WebAssembly & Wasmtime)',
    description: 'Standardizing WebAssembly System Interface (WASI), Wasm component model, Cranelift code generator, and cross-language runtime security',
    enabled: true,
    protocol: 'rss',
    connector: 'bytecode_alliance_wasm',
    baseUrl: 'https://bytecodealliance.org/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'cybersecurity'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Bytecode Alliance',
    region: 'Global',
    country: 'United States'
  },
  rust_foundation_news: {
    id: 'rust_foundation_news',
    name: 'Rust Foundation News',
    description: 'Rust language stewardship, security initiatives, memory-safe systems software, and crates.io ecosystem grants',
    enabled: true,
    protocol: 'rss',
    connector: 'rust_foundation_news',
    baseUrl: 'https://rustfoundation.org/feed/',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'cybersecurity'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Rust Foundation',
    region: 'Global',
    country: 'United States'
  },
  go_dev_blog: {
    id: 'go_dev_blog',
    name: 'The Go Programming Language Blog',
    description: 'Go runtime scheduler, garbage collection latency optimizations, generics evolution, standard library security, and telemetry',
    enabled: true,
    protocol: 'rss',
    connector: 'go_dev_blog',
    baseUrl: 'https://go.dev/blog/feed.atom',
    authType: 'none',
    categories: ['programming', 'cloud', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Go Dev Team (Google)',
    region: 'Global',
    country: 'United States'
  },
  bun_sh_blog: {
    id: 'bun_sh_blog',
    name: 'Bun JavaScript Runtime',
    description: 'High-speed JavaScript/TypeScript runtime written in Zig, JavaScriptCore engine, native bundler, package manager, and test runner',
    enabled: true,
    protocol: 'rss',
    connector: 'bun_sh_blog',
    baseUrl: 'https://bun.sh/rss.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Oven / Bun Team',
    region: 'Global',
    country: 'United States'
  },
  nodejs_official: {
    id: 'nodejs_official',
    name: 'Node.js Official Releases & Security',
    description: 'Node.js LTS release announcements, V8 engine integration, performance benchmarks, and core security advisories',
    enabled: true,
    protocol: 'rss',
    connector: 'nodejs_official',
    baseUrl: 'https://nodejs.org/en/feed/blog.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'cybersecurity'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'OpenJS Foundation',
    region: 'Global',
    country: 'United States'
  },
  khronos_group: {
    id: 'khronos_group',
    name: 'The Khronos Group (Vulkan & Graphics)',
    description: 'Open industry standards for graphics: Vulkan API, glTF 3D transmission, WebGL, OpenCL compute, and SYCL programming',
    enabled: true,
    protocol: 'rss',
    connector: 'khronos_group',
    baseUrl: 'https://www.khronos.org/feeds/news.rss',
    authType: 'none',
    categories: ['programming', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Khronos Group',
    region: 'Global',
    country: 'United States'
  },
  openxr_chronicles: {
    id: 'openxr_chronicles',
    name: 'OpenXR Standards & Spatial Computing',
    description: 'Cross-platform VR and AR device abstraction, hand-tracking extensions, foveated rendering, and spatial hardware drivers',
    enabled: true,
    protocol: 'rss',
    connector: 'openxr_chronicles',
    baseUrl: 'https://www.khronos.org/feeds/openxr.rss',
    authType: 'none',
    categories: ['technology', 'programming', 'ai-hardware'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Khronos OpenXR Working Group',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 7. Custom ASICs, Wafer-Scale & Datacenter Microarchitecture
  // ==========================================
  servethehome_sth: {
    id: 'servethehome_sth',
    name: 'ServeTheHome (STH)',
    description: 'Deep teardowns of enterprise servers, liquid cooling datacenter racks, AI accelerators, NVLink interconnects, and DPUs',
    enabled: true,
    protocol: 'rss',
    connector: 'servethehome_sth',
    baseUrl: 'https://www.servethehome.com/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'cloud', 'semiconductors'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ServeTheHome',
    region: 'Global',
    country: 'United States'
  },
  chips_and_cheese: {
    id: 'chips_and_cheese',
    name: 'Chips and Cheese Microarchitecture',
    description: 'Instruction-level latency measurements, branch predictors, cache hierarchies, and comparative silicon architecture analysis',
    enabled: true,
    protocol: 'rss',
    connector: 'chips_and_cheese',
    baseUrl: 'https://chipsandcheese.com/feed/',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Chips and Cheese',
    region: 'Global',
    country: 'United States'
  },
  wikichip_fuse: {
    id: 'wikichip_fuse',
    name: 'WikiChip Fuse Semiconductor Analysis',
    description: 'Lithography node dimensions, finFET to GAA nanosheet transitions, backside power delivery (BSPDN), and packaging physics',
    enabled: true,
    protocol: 'rss',
    connector: 'wikichip_fuse',
    baseUrl: 'https://fuse.wikichip.org/feed/',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'WikiChip Foundation',
    region: 'Global',
    country: 'United States'
  },
  cerebras_systems: {
    id: 'cerebras_systems',
    name: 'Cerebras Systems Wafer-Scale AI',
    description: 'Wafer-Scale Engine (WSE-3), 900,000 AI cores on a single silicon wafer, 44GB on-chip SRAM, and CS-3 cluster supercomputers',
    enabled: true,
    protocol: 'rss',
    connector: 'cerebras_systems',
    baseUrl: 'https://cerebras.ai/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'ai', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cerebras Systems',
    region: 'Global',
    country: 'United States'
  },
  tenstorrent_ai: {
    id: 'tenstorrent_ai',
    name: 'Tenstorrent (Jim Keller RISC-V)',
    description: 'High-performance RISC-V CPU cores (Ascalon), Tensix AI processors, chiplet architecture, and open-source metal programming',
    enabled: true,
    protocol: 'rss',
    connector: 'tenstorrent_ai',
    baseUrl: 'https://tenstorrent.com/feed/',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'open-source-ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Tenstorrent Inc.',
    region: 'Americas',
    country: 'Canada'
  },
  groq_lpu: {
    id: 'groq_lpu',
    name: 'Groq LPU Inference Engine',
    description: 'Language Processing Unit (LPU) deterministic tensor streaming architecture, 500+ tokens/sec LLM execution, and compiler-first silicon',
    enabled: true,
    protocol: 'rss',
    connector: 'groq_lpu',
    baseUrl: 'https://groq.com/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'ai', 'semiconductors'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Groq Inc.',
    region: 'Global',
    country: 'United States'
  },
  sambanova_systems: {
    id: 'sambanova_systems',
    name: 'SambaNova Systems Dataflow',
    description: 'Reconfigurable Dataflow Units (RDU), SN40L enterprise AI chips, 3-tier memory systems, and full-stack model deployment',
    enabled: true,
    protocol: 'rss',
    connector: 'sambanova_systems',
    baseUrl: 'https://sambanova.ai/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'SambaNova Systems',
    region: 'Global',
    country: 'United States'
  },
  sifive_riscv: {
    id: 'sifive_riscv',
    name: 'SiFive RISC-V Compute IP',
    description: 'Commercial RISC-V processor IP cores, Performance P870 series, Intelligence vector engines, and custom domain-specific SoCs',
    enabled: true,
    protocol: 'rss',
    connector: 'sifive_riscv',
    baseUrl: 'https://www.sifive.com/blog/rss.xml',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'open-source-ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'SiFive Inc.',
    region: 'Global',
    country: 'United States'
  },
  epic_games_dev: {
    id: 'epic_games_dev',
    name: 'Unreal Engine Developer News',
    description: 'Unreal Engine 5 micro-polygon Nanite geometry, Lumen real-time global illumination, Substrate materials, and Chaos physics',
    enabled: true,
    protocol: 'rss',
    connector: 'epic_games_dev',
    baseUrl: 'https://www.unrealengine.com/en-US/feed',
    authType: 'none',
    categories: ['programming', 'technology', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Epic Games',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 8. Security Research & Exploit Analysis
  // ==========================================
  quarkslab_blog: {
    id: 'quarkslab_blog',
    name: 'Quarkslab Vulnerability Research',
    description: 'Deep reverse engineering, binary obfuscation, cryptographic protocol auditing, hypervisor vulnerabilities, and hardware attacks',
    enabled: true,
    protocol: 'rss',
    connector: 'quarkslab_blog',
    baseUrl: 'https://blog.quarkslab.com/feeds/all.rss.xml',
    authType: 'none',
    categories: ['cybersecurity', 'programming', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Quarkslab',
    region: 'Europe',
    country: 'France'
  },
  ncc_group_research: {
    id: 'ncc_group_research',
    name: 'NCC Group Security Research',
    description: 'Cryptographic vulnerabilities, side-channel attacks, zero-day CVE discoveries, cloud security architecture, and red teaming',
    enabled: true,
    protocol: 'rss',
    connector: 'ncc_group_research',
    baseUrl: 'https://research.nccgroup.com/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'research', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'NCC Group',
    region: 'Europe',
    country: 'United Kingdom'
  },
  krebs_on_security: {
    id: 'krebs_on_security',
    name: 'Krebs on Security',
    description: 'Investigative cybersecurity journalism uncovering transnational cybercrime syndicates, carding rings, and data breaches',
    enabled: true,
    protocol: 'rss',
    connector: 'krebs_on_security',
    baseUrl: 'https://krebsonsecurity.com/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Brian Krebs',
    region: 'Global',
    country: 'United States'
  },
  schneier_on_security: {
    id: 'schneier_on_security',
    name: 'Schneier on Security',
    description: 'Bruce Schneier on applied cryptography, security policy, surveillance capitalism, cryptographic primitives, and threat models',
    enabled: true,
    protocol: 'rss',
    connector: 'schneier_on_security',
    baseUrl: 'https://www.schneier.com/feed/atom/',
    authType: 'none',
    categories: ['cybersecurity', 'technology', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Bruce Schneier',
    region: 'Global',
    country: 'United States'
  },
  bleeping_computer: {
    id: 'bleeping_computer',
    name: 'BleepingComputer Enterprise Security',
    description: 'Breaking cybersecurity news, active ransomware campaigns, zero-day CVE advisories, malware reverse engineering, and threat actors',
    enabled: true,
    protocol: 'rss',
    connector: 'bleeping_computer',
    baseUrl: 'https://www.bleepingcomputer.com/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'technology'],
    fetchIntervalMinutes: 15,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'BleepingComputer LLC',
    region: 'Global',
    country: 'United States'
  },
  dark_reading_tech: {
    id: 'dark_reading_tech',
    name: 'Dark Reading Cyber Defense',
    description: 'Cybersecurity defense analysis, enterprise vulnerability management, perimeter security, and nation-state threat campaigns',
    enabled: true,
    protocol: 'rss',
    connector: 'dark_reading_tech',
    baseUrl: 'https://www.darkreading.com/rss.xml',
    authType: 'none',
    categories: ['cybersecurity', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Informa Tech',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 9. Neurotechnology & Brain-Computer Interfaces
  // ==========================================
  neuralink_progress: {
    id: 'neuralink_progress',
    name: 'Neuralink Neurotechnology',
    description: 'Fully implantable N1 Telepathy brain-computer interfaces, 1024-electrode thread insertion robots, and motor cortex decoding',
    enabled: true,
    protocol: 'rss',
    connector: 'neuralink_progress',
    baseUrl: 'https://neuralink.com/blog/feed.xml',
    authType: 'none',
    categories: ['ai-hardware', 'robotics', 'research', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Neuralink Corp.',
    region: 'Global',
    country: 'United States'
  },
  synchron_bci: {
    id: 'synchron_bci',
    name: 'Synchron Endovascular BCI',
    description: 'Stentrode motor neuroprosthesis implanted via the jugular vein, wireless cortical signal streaming, and assistive device control',
    enabled: true,
    protocol: 'rss',
    connector: 'synchron_bci',
    baseUrl: 'https://synchron.com/news/rss.xml',
    authType: 'none',
    categories: ['technology', 'research', 'ai-hardware'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Synchron Inc.',
    region: 'Global',
    country: 'United States'
  },
  precision_neuroscience: {
    id: 'precision_neuroscience',
    name: 'Precision Neuroscience (Layer 7)',
    description: 'Layer 7 cortical interface microelectrode film, high-density neural recording without brain tissue penetration, and clinical mapping',
    enabled: true,
    protocol: 'rss',
    connector: 'precision_neuroscience',
    baseUrl: 'https://precisionneuro.com/feed/',
    authType: 'none',
    categories: ['research', 'technology', 'ai-hardware'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Precision Neuroscience',
    region: 'Global',
    country: 'United States'
  },
  blackrock_neurotech: {
    id: 'blackrock_neurotech',
    name: 'Blackrock Neurotech Brain Interfaces',
    description: 'Utah Array high-channel neural implants, intracortical microelectrodes, neural decoding algorithms, and sensory restoration',
    enabled: true,
    protocol: 'rss',
    connector: 'blackrock_neurotech',
    baseUrl: 'https://blackrockneurotech.com/feed/',
    authType: 'none',
    categories: ['research', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Blackrock Neurotech',
    region: 'Global',
    country: 'United States'
  },
  mit_mcgovern_institute: {
    id: 'mit_mcgovern_institute',
    name: 'MIT McGovern Institute for Brain Research',
    description: 'Neural circuit architecture, optogenetics, computational neuroscience models, and neuroengineering breakthroughs',
    enabled: true,
    protocol: 'rss',
    connector: 'mit_mcgovern_institute',
    baseUrl: 'https://mcgovern.mit.edu/news/feed/',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'MIT McGovern Institute',
    region: 'Americas',
    country: 'United States'
  },

  // ==========================================
  // 10. Nuclear Fusion & Deep Clean Tech
  // ==========================================
  commonwealth_fusion: {
    id: 'commonwealth_fusion',
    name: 'Commonwealth Fusion Systems (CFS)',
    description: 'High-temperature superconducting (HTS) magnets, SPARC compact tokamak design, and commercial net energy fusion power',
    enabled: true,
    protocol: 'rss',
    connector: 'commonwealth_fusion',
    baseUrl: 'https://cfs.energy/news/rss.xml',
    authType: 'none',
    categories: ['technology', 'research'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Commonwealth Fusion Systems',
    region: 'Global',
    country: 'United States'
  },
  helion_energy: {
    id: 'helion_energy',
    name: 'Helion Energy Pulsed Fusion',
    description: 'Magneto-inertial fusion technology, direct inductive electricity recovery without steam turbines, and Polaris prototype progress',
    enabled: true,
    protocol: 'rss',
    connector: 'helion_energy',
    baseUrl: 'https://www.helionenergy.com/feed/',
    authType: 'none',
    categories: ['technology', 'research'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Helion Energy',
    region: 'Global',
    country: 'United States'
  },
  iter_fusion: {
    id: 'iter_fusion',
    name: 'ITER Organization International Fusion',
    description: 'World\'s largest magnetic confinement plasma physics experiment, 500MW tokamak reactor, and cryogenic magnet engineering',
    enabled: true,
    protocol: 'rss',
    connector: 'iter_fusion',
    baseUrl: 'https://www.iter.org/rss/news',
    authType: 'none',
    categories: ['research', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ITER Organization',
    region: 'Europe',
    country: 'France'
  },
  llnl_nif_ignition: {
    id: 'llnl_nif_ignition',
    name: 'Lawrence Livermore National Lab (NIF)',
    description: 'Inertial confinement fusion ignition, 192-laser megajoule target chamber experiments, and extreme density plasma physics',
    enabled: true,
    protocol: 'rss',
    connector: 'llnl_nif_ignition',
    baseUrl: 'https://lasers.llnl.gov/news/feed',
    authType: 'none',
    categories: ['research', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Lawrence Livermore National Laboratory',
    region: 'Americas',
    country: 'United States'
  },
  electrek_tech: {
    id: 'electrek_tech',
    name: 'Electrek Green Grid & EV Tech',
    description: 'Electric vehicle battery chemistries (LFP/solid-state), megawatt charging standards (MCS), and grid-scale battery storage',
    enabled: true,
    protocol: 'rss',
    connector: 'electrek_tech',
    baseUrl: 'https://electrek.co/feed/',
    authType: 'none',
    categories: ['technology', 'startups'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: '9to5 / Electrek',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 11. Autonomous Aerial Logistics & eVTOL Robotics
  // ==========================================
  zipline_tech: {
    id: 'zipline_tech',
    name: 'Zipline Autonomous Aerial Logistics',
    description: 'Autonomous fixed-wing drones, acoustic detect-and-avoid sensors, P2 tethered home delivery, and cold-chain medical routing',
    enabled: true,
    protocol: 'rss',
    connector: 'zipline_tech',
    baseUrl: 'https://flyzipline.com/blog/rss.xml',
    authType: 'none',
    categories: ['robotics', 'technology', 'startups'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Zipline International',
    region: 'Global',
    country: 'United States'
  },
  wing_aviation: {
    id: 'wing_aviation',
    name: 'Wing Autonomous Drone Delivery',
    description: 'Alphabet autonomous delivery drone network, UTM airspace management, low-noise multirotor flight physics, and logistics hubs',
    enabled: true,
    protocol: 'rss',
    connector: 'wing_aviation',
    baseUrl: 'https://wing.com/feed.xml',
    authType: 'none',
    categories: ['robotics', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Wing (Alphabet)',
    region: 'Global',
    country: 'United States'
  },
  joby_aviation: {
    id: 'joby_aviation',
    name: 'Joby Aviation eVTOL Air Mobility',
    description: 'Electric vertical takeoff and landing (eVTOL) aircraft, tilt-rotor aerodynamics, acoustic footprint reduction, and FAA certification',
    enabled: true,
    protocol: 'rss',
    connector: 'joby_aviation',
    baseUrl: 'https://www.jobyaviation.com/news/feed/',
    authType: 'none',
    categories: ['technology', 'robotics'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Joby Aviation',
    region: 'Global',
    country: 'United States'
  },
  archer_aviation: {
    id: 'archer_aviation',
    name: 'Archer Aviation Midnight eVTOL',
    description: 'Commercial urban air mobility aircraft, electric powertrain redundancy, composite aerostructures, and autonomous flight testing',
    enabled: true,
    protocol: 'rss',
    connector: 'archer_aviation',
    baseUrl: 'https://www.archer.com/news/feed.xml',
    authType: 'none',
    categories: ['technology', 'robotics'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Archer Aviation',
    region: 'Global',
    country: 'United States'
  },
  skydio_autonomy: {
    id: 'skydio_autonomy',
    name: 'Skydio Autonomous Drone Systems',
    description: '360-degree computer vision navigation, real-time 3D reconstruction, GPS-denied flight autonomy, and edge AI compute',
    enabled: true,
    protocol: 'rss',
    connector: 'skydio_autonomy',
    baseUrl: 'https://www.skydio.com/blog/rss.xml',
    authType: 'none',
    categories: ['robotics', 'computer-vision', 'ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Skydio Inc.',
    region: 'Global',
    country: 'United States'
  },
  anybotics_robotics: {
    id: 'anybotics_robotics',
    name: 'ANYbotics Industrial Quadruped',
    description: 'ANYmal quadrupedal robot locomotion, autonomous industrial facility inspection, LiDAR SLAM, and hazardous area navigation',
    enabled: true,
    protocol: 'rss',
    connector: 'anybotics_robotics',
    baseUrl: 'https://www.anybotics.com/feed/',
    authType: 'none',
    categories: ['robotics', 'computer-vision', 'ai'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ANYbotics AG',
    region: 'Europe',
    country: 'Switzerland'
  },

  // ==========================================
  // 12. Global Hyper-Growth & Multi-Continental Unicorns
  // ==========================================
  nubank_engineering: {
    id: 'nubank_engineering',
    name: 'Nubank Engineering',
    description: 'World\'s largest digital bank, immutable Datomic databases, Clojure functional programming at scale, and high-frequency transactions',
    enabled: true,
    protocol: 'rss',
    connector: 'nubank_engineering',
    baseUrl: 'https://building.nubank.com.br/feed/',
    authType: 'none',
    categories: ['cloud', 'programming', 'cybersecurity'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Nubank S.A.',
    region: 'Latin America',
    country: 'Brazil'
  },
  adyen_tech: {
    id: 'adyen_tech',
    name: 'Adyen Technology Blog',
    description: 'Global end-to-end payment processing infrastructure, merchant ledger resilience, machine learning fraud scoring, and low-latency APIs',
    enabled: true,
    protocol: 'rss',
    connector: 'adyen_tech',
    baseUrl: 'https://www.adyen.com/blog/rss',
    authType: 'none',
    categories: ['cloud', 'programming', 'cybersecurity'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Adyen N.V.',
    region: 'Europe',
    country: 'Netherlands'
  },
  mercari_engineering: {
    id: 'mercari_engineering',
    name: 'Mercari Engineering (Japan)',
    description: 'Japan\'s largest peer-to-peer marketplace, microservices on Google Cloud, Go language engineering, and image search AI',
    enabled: true,
    protocol: 'rss',
    connector: 'mercari_engineering',
    baseUrl: 'https://engineering.mercari.com/blog/feed.xml',
    authType: 'none',
    categories: ['cloud', 'programming', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Mercari Inc.',
    region: 'Asia',
    country: 'Japan'
  },
  line_engineering: {
    id: 'line_engineering',
    name: 'LINE Corporation Engineering',
    description: 'East Asia leading messaging super-app, distributed Kafka architecture, Apache HBase scale, and real-time VoIP protocols',
    enabled: true,
    protocol: 'rss',
    connector: 'line_engineering',
    baseUrl: 'https://engineering.linecorp.com/en/blog/rss2.xml',
    authType: 'none',
    categories: ['cloud', 'programming', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'LY Corporation (LINE Yahoo)',
    region: 'Asia',
    country: 'Japan'
  },
  naver_labs: {
    id: 'naver_labs',
    name: 'NAVER Labs Autonomous & Robotics',
    description: 'Digital twin mapping (ARC system), robotic spatial intelligence, cloud-connected autonomous driving, and computer vision',
    enabled: true,
    protocol: 'rss',
    connector: 'naver_labs',
    baseUrl: 'https://www.naverlabs.com/feed',
    authType: 'none',
    categories: ['robotics', 'computer-vision', 'ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'NAVER Corp.',
    region: 'Asia',
    country: 'South Korea'
  },
  delivery_hero_tech: {
    id: 'delivery_hero_tech',
    name: 'Delivery Hero Tech Collective',
    description: 'Global quick-commerce and delivery operations across 70+ countries, routing algorithms, multi-cloud infra, and real-time matching',
    enabled: true,
    protocol: 'rss',
    connector: 'delivery_hero_tech',
    baseUrl: 'https://tech.deliveryhero.com/feed/',
    authType: 'none',
    categories: ['cloud', 'programming', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Delivery Hero SE',
    region: 'Europe',
    country: 'Germany'
  },
  paystack_engineering: {
    id: 'paystack_engineering',
    name: 'Paystack Engineering',
    description: 'Modern payment gateways for Africa, resilient bank integration APIs, webhooks delivery guarantees, and high-volume billing',
    enabled: true,
    protocol: 'rss',
    connector: 'paystack_engineering',
    baseUrl: 'https://paystack.com/blog/engineering/feed',
    authType: 'none',
    categories: ['cloud', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Paystack (Stripe)',
    region: 'Africa',
    country: 'Nigeria'
  },
  flutterwave_tech: {
    id: 'flutterwave_tech',
    name: 'Flutterwave Tech',
    description: 'Pan-African cross-border payments infrastructure, currency settlement corridors, mobile money APIs, and fraud intelligence',
    enabled: true,
    protocol: 'rss',
    connector: 'flutterwave_tech',
    baseUrl: 'https://flutterwave.com/blog/feed/',
    authType: 'none',
    categories: ['cloud', 'programming', 'startups'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Flutterwave',
    region: 'Africa',
    country: 'Nigeria'
  },
  rappi_tech: {
    id: 'rappi_tech',
    name: 'Rappi Tech & Data Science',
    description: 'Latin America on-demand super-app, Turbo fresh deliveries in under 10 minutes, geospatial dispatch, and dynamic pricing models',
    enabled: true,
    protocol: 'rss',
    connector: 'rappi_tech',
    baseUrl: 'https://medium.com/feed/rappi-tech',
    authType: 'none',
    categories: ['cloud', 'programming', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Rappi Inc.',
    region: 'Latin America',
    country: 'Colombia'
  },

  // ==========================================
  // 13. Creative Code, Simulation & Embedded IoT
  // ==========================================
  blender_nation: {
    id: 'blender_nation',
    name: 'BlenderNation 3D & Graphics',
    description: 'Open-source 3D rendering breakthroughs, Geometry Nodes procedural asset pipelines, Cycles GPU engine, and VFX developments',
    enabled: true,
    protocol: 'rss',
    connector: 'blender_nation',
    baseUrl: 'https://www.blendernation.com/feed/',
    authType: 'none',
    categories: ['technology', 'programming', 'open-source-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'BlenderNation',
    region: 'Global',
    country: 'Netherlands'
  },
  shadertoy_community: {
    id: 'shadertoy_community',
    name: 'Shadertoy Graphics & Shaders',
    description: 'Mathematical graphics programming, GLSL pixel shaders, raymarching, Signed Distance Functions (SDFs), and procedural rendering',
    enabled: true,
    protocol: 'rss',
    connector: 'shadertoy_community',
    baseUrl: 'https://www.shadertoy.com/rss',
    authType: 'none',
    categories: ['programming', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Shadertoy Community',
    region: 'Global',
    country: 'United States'
  },
  espressif_systems: {
    id: 'espressif_systems',
    name: 'Espressif Systems (ESP32 IoT)',
    description: 'ESP32-S3, ESP32-P4 RISC-V microcontrollers, ESP-IDF framework, Matter smart home protocol, and edge neural processing',
    enabled: true,
    protocol: 'rss',
    connector: 'espressif_systems',
    baseUrl: 'https://blog.espressif.com/feed',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Espressif Systems',
    region: 'Asia',
    country: 'China'
  },
  raspberry_pi_news: {
    id: 'raspberry_pi_news',
    name: 'Raspberry Pi Foundation News',
    description: 'Raspberry Pi 5 computing, RP2350 dual-core ARM/RISC-V microcontroller, Camera Module 3 AI kits, and educational computing',
    enabled: true,
    protocol: 'rss',
    connector: 'raspberry_pi_news',
    baseUrl: 'https://www.raspberrypi.com/news/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Raspberry Pi Foundation',
    region: 'Europe',
    country: 'United Kingdom'
  },
  nordic_semi_tech: {
    id: 'nordic_semi_tech',
    name: 'Nordic Semiconductor Tech',
    description: 'Ultra-low power Bluetooth Low Energy (BLE), nRF54 series, cellular IoT (LTE-M/NB-IoT), Thread, Matter, and Wi-Fi 6 silicon',
    enabled: true,
    protocol: 'rss',
    connector: 'nordic_semi_tech',
    baseUrl: 'https://blog.nordicsemi.com/getconnected/rss.xml',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Nordic Semiconductor',
    region: 'Europe',
    country: 'Norway'
  },
  zephyr_rtos: {
    id: 'zephyr_rtos',
    name: 'Zephyr RTOS Project',
    description: 'Open-source real-time operating system for resource-constrained devices, multi-architecture hardware support, and POSIX compliance',
    enabled: true,
    protocol: 'rss',
    connector: 'zephyr_rtos',
    baseUrl: 'https://www.zephyrproject.org/feed/',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'open-source-ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Linux Foundation / Zephyr Project',
    region: 'Global',
    country: 'United States'
  }
};
