import { SourceDefinition } from '../../types.js';

export const FRONTIER_EXPANSION_SOURCES: Record<string, SourceDefinition> = {
  // === 1. TOP AI RESEARCH LABS & UNIVERSITIES ===
  max_planck_is: {
    id: 'max_planck_is',
    name: 'Max Planck Institute for Intelligent Systems',
    description: 'Fundamental research in machine learning, autonomous systems, haptics, and bio-inspired robotics',
    enabled: true,
    protocol: 'rss',
    connector: 'max_planck_is',
    baseUrl: 'https://is.mpg.de/en/news-events/news.rss',
    authType: 'none',
    categories: ['research', 'ai', 'robotics'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Max Planck Institute for Intelligent Systems',
    region: 'Europe',
    country: 'Germany'
  },
  vector_institute: {
    id: 'vector_institute',
    name: 'Vector Institute for Artificial Intelligence',
    description: 'Breakthrough deep learning and machine learning research advancing Canadian and global AI',
    enabled: true,
    protocol: 'rss',
    connector: 'vector_institute',
    baseUrl: 'https://vectorinstitute.ai/feed/',
    authType: 'none',
    categories: ['research', 'ai', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Vector Institute (Toronto)',
    region: 'North America',
    country: 'Canada'
  },
  mila_quebec: {
    id: 'mila_quebec',
    name: 'Mila - Quebec AI Institute',
    description: 'World-renowned research center in deep learning founded by Yoshua Bengio focusing on AI safety and science',
    enabled: true,
    protocol: 'rss',
    connector: 'mila_quebec',
    baseUrl: 'https://mila.quebec/en/feed/',
    authType: 'none',
    categories: ['research', 'ai', 'ai-safety'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Mila Quebec AI Institute',
    region: 'North America',
    country: 'Canada'
  },
  alan_turing_inst: {
    id: 'alan_turing_inst',
    name: 'The Alan Turing Institute',
    description: 'The UK national institute for data science and artificial intelligence',
    enabled: true,
    protocol: 'rss',
    connector: 'alan_turing_inst',
    baseUrl: 'https://www.turing.ac.uk/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'ethics'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'The Alan Turing Institute (London)',
    region: 'Europe',
    country: 'United Kingdom'
  },
  dfki_ai: {
    id: 'dfki_ai',
    name: 'DFKI - German Research Center for AI',
    description: 'Human-centric AI, cyber-physical systems, knowledge architectures, and intelligent industrial robotics',
    enabled: true,
    protocol: 'rss',
    connector: 'dfki_ai',
    baseUrl: 'https://www.dfki.de/en/web/news/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'robotics'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'DFKI GmbH (Germany)',
    region: 'Europe',
    country: 'Germany'
  },
  inria_ai: {
    id: 'inria_ai',
    name: 'INRIA Research in Digital Science & AI',
    description: 'French national research institute in digital science, scientific computing, algorithms, and artificial intelligence',
    enabled: true,
    protocol: 'rss',
    connector: 'inria_ai',
    baseUrl: 'https://www.inria.fr/en/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'programming'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'INRIA (France)',
    region: 'Europe',
    country: 'France'
  },
  cmu_scs: {
    id: 'cmu_scs',
    name: 'Carnegie Mellon School of Computer Science',
    description: 'Groundbreaking computer science, language technologies, robotics, and machine learning research',
    enabled: true,
    protocol: 'rss',
    connector: 'cmu_scs',
    baseUrl: 'https://www.cs.cmu.edu/news/feed',
    authType: 'none',
    categories: ['research', 'ai', 'robotics'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Carnegie Mellon University',
    region: 'North America',
    country: 'United States'
  },
  eth_zurich_ai: {
    id: 'eth_zurich_ai',
    name: 'ETH Zurich Computer Science & AI',
    description: 'European frontier research in neural processing, quantum computing, computer vision, and systems architecture',
    enabled: true,
    protocol: 'rss',
    connector: 'eth_zurich_ai',
    baseUrl: 'https://inf.ethz.ch/news-and-events/news.rss',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ETH Zurich (Switzerland)',
    region: 'Europe',
    country: 'Switzerland'
  },
  epfl_ai: {
    id: 'epfl_ai',
    name: 'EPFL Computer Science & AI Center',
    description: 'Swiss Federal Institute of Technology research in intelligence, neural networks, and privacy-preserving machine learning',
    enabled: true,
    protocol: 'rss',
    connector: 'epfl_ai',
    baseUrl: 'https://actu.epfl.ch/feeds/rss/ic/en/',
    authType: 'none',
    categories: ['research', 'ai', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'EPFL (Lausanne, Switzerland)',
    region: 'Europe',
    country: 'Switzerland'
  },
  cambridge_ai: {
    id: 'cambridge_ai',
    name: 'Cambridge Computer Science & AI',
    description: 'University of Cambridge Department of Computer Science and Technology research breakthroughs',
    enabled: true,
    protocol: 'rss',
    connector: 'cambridge_ai',
    baseUrl: 'https://www.cst.cam.ac.uk/news/rss',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'University of Cambridge',
    region: 'Europe',
    country: 'United Kingdom'
  },
  oxford_ai: {
    id: 'oxford_ai',
    name: 'Oxford Computer Science & AI Lab',
    description: 'University of Oxford Department of Computer Science research into automated reasoning, ML, and algorithms',
    enabled: true,
    protocol: 'rss',
    connector: 'oxford_ai',
    baseUrl: 'https://www.cs.ox.ac.uk/feeds/News-all.xml',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'University of Oxford',
    region: 'Europe',
    country: 'United Kingdom'
  },

  // === 2. OPEN SOURCE AI, CODING AGENTS & RUNTIMES ===
  cursor_ai: {
    id: 'cursor_ai',
    name: 'Cursor AI & Anysphere Changelog',
    description: 'AI-first code editor innovations, agentic codebase indexers, and autonomous coding tools',
    enabled: true,
    protocol: 'rss',
    connector: 'cursor_ai',
    baseUrl: 'https://www.cursor.com/changelog/rss.xml',
    authType: 'none',
    categories: ['ai-agents', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cursor (Anysphere)',
    region: 'North America',
    country: 'United States'
  },
  windsurf_ai: {
    id: 'windsurf_ai',
    name: 'Windsurf & Codeium AI Blog',
    description: 'Cascade coding flows, enterprise codebase contextualization, and next-generation developer tooling',
    enabled: true,
    protocol: 'rss',
    connector: 'windsurf_ai',
    baseUrl: 'https://codeium.com/blog/rss.xml',
    authType: 'none',
    categories: ['ai-agents', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Codeium / Windsurf',
    region: 'North America',
    country: 'United States'
  },
  vllm_project: {
    id: 'vllm_project',
    name: 'vLLM Project Blog',
    description: 'High-throughput and memory-efficient LLM inference and serving engine powered by PagedAttention',
    enabled: true,
    protocol: 'rss',
    connector: 'vllm_project',
    baseUrl: 'https://blog.vllm.ai/feed.xml',
    authType: 'none',
    categories: ['open-source-ai', 'developer-tools', 'llms'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'vLLM Project (UC Berkeley)',
    region: 'Global',
    country: 'United States'
  },
  ollama_ai: {
    id: 'ollama_ai',
    name: 'Ollama Blog & Local Models',
    description: 'Get up and running with Llama, Mistral, Gemma, and DeepSeek locally on macOS, Linux, and Windows',
    enabled: true,
    protocol: 'rss',
    connector: 'ollama_ai',
    baseUrl: 'https://ollama.com/blog/rss.xml',
    authType: 'none',
    categories: ['open-source-ai', 'developer-tools', 'llms'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Ollama',
    region: 'Global',
    country: 'United States'
  },
  unsloth_ai: {
    id: 'unsloth_ai',
    name: 'Unsloth AI Optimization',
    description: 'Ultra-fast LLM fine-tuning, manual backpropagation derivations, 80% memory reduction, and open weights',
    enabled: true,
    protocol: 'rss',
    connector: 'unsloth_ai',
    baseUrl: 'https://unsloth.ai/feed.xml',
    authType: 'none',
    categories: ['open-source-ai', 'machine-learning', 'llms'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Unsloth AI',
    region: 'Global',
    country: 'United States'
  },
  cohere_for_ai: {
    id: 'cohere_for_ai',
    name: 'Cohere For AI Research',
    description: 'Open scientific research lab exploring fundamental machine learning, multilingual NLP, and evaluation',
    enabled: true,
    protocol: 'rss',
    connector: 'cohere_for_ai',
    baseUrl: 'https://cohere.com/blog/rss',
    authType: 'none',
    categories: ['research', 'ai', 'llms'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cohere & Cohere For AI',
    region: 'North America',
    country: 'Canada'
  },
  elevenlabs_ai: {
    id: 'elevenlabs_ai',
    name: 'ElevenLabs Voice & Audio AI',
    description: 'Generative audio research, emotional voice synthesis, real-time conversational agents, and sound design',
    enabled: true,
    protocol: 'rss',
    connector: 'elevenlabs_ai',
    baseUrl: 'https://elevenlabs.io/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'developer-tools', 'generative-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ElevenLabs',
    region: 'Global',
    country: 'United States'
  },
  baseten_ai: {
    id: 'baseten_ai',
    name: 'Baseten Model Infrastructure',
    description: 'Low-latency model serving, autoscaling GPU infrastructure, and Truss packaging for production ML',
    enabled: true,
    protocol: 'rss',
    connector: 'baseten_ai',
    baseUrl: 'https://www.baseten.co/blog/rss.xml',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'ai-hardware'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Baseten',
    region: 'North America',
    country: 'United States'
  },
  modal_labs: {
    id: 'modal_labs',
    name: 'Modal Labs Distributed AI',
    description: 'Run Python code in the cloud with instant GPU provisioning, container virtualization, and serverless AI',
    enabled: true,
    protocol: 'rss',
    connector: 'modal_labs',
    baseUrl: 'https://modal.com/blog/feed.xml',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Modal Labs',
    region: 'North America',
    country: 'United States'
  },
  anyscale_ray: {
    id: 'anyscale_ray',
    name: 'Anyscale & Ray AI Compute',
    description: 'Distributed AI workloads, Ray Core, Ray Train, Ray Serve, and large scale distributed RL training',
    enabled: true,
    protocol: 'rss',
    connector: 'anyscale_ray',
    baseUrl: 'https://www.anyscale.com/blog/rss.xml',
    authType: 'none',
    categories: ['cloud', 'machine-learning', 'open-source-ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Anyscale / Ray',
    region: 'North America',
    country: 'United States'
  },

  // === 3. AI HARDWARE, SILICON & PHOTONICS ===
  groq_lpu: {
    id: 'groq_lpu',
    name: 'Groq LPUs & Deterministic Inference',
    description: 'Language Processing Units (LPUs) delivering hundreds of tokens per second for real-time generative AI',
    enabled: true,
    protocol: 'rss',
    connector: 'groq_lpu',
    baseUrl: 'https://groq.com/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'llms'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Groq Inc.',
    region: 'North America',
    country: 'United States'
  },
  cerebras_systems: {
    id: 'cerebras_systems',
    name: 'Cerebras Systems Wafer-Scale AI',
    description: 'Wafer Scale Engine (WSE-3) supercomputing clusters and trillion-parameter model training architectures',
    enabled: true,
    protocol: 'rss',
    connector: 'cerebras_systems',
    baseUrl: 'https://cerebras.ai/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cerebras Systems',
    region: 'North America',
    country: 'United States'
  },
  sambanova_ai: {
    id: 'sambanova_ai',
    name: 'SambaNova Systems Reconfigurable Dataflow',
    description: 'Reconfigurable Dataflow Units (RDUs) and enterprise full-stack generative AI accelerators',
    enabled: true,
    protocol: 'rss',
    connector: 'sambanova_ai',
    baseUrl: 'https://sambanova.ai/feed',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'SambaNova Systems',
    region: 'North America',
    country: 'United States'
  },
  tenstorrent_ai: {
    id: 'tenstorrent_ai',
    name: 'Tenstorrent RISC-V AI Processors',
    description: 'Jim Keller-led open hardware company building RISC-V CPUs, Tensix AI accelerators, and Chiplets',
    enabled: true,
    protocol: 'rss',
    connector: 'tenstorrent_ai',
    baseUrl: 'https://tenstorrent.com/feed',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'open-source-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Tenstorrent Inc.',
    region: 'North America',
    country: 'United States'
  },
  d_matrix_ai: {
    id: 'd_matrix_ai',
    name: 'd-Matrix Digital In-Memory Computing',
    description: 'Digital in-memory computing (DIMC) architecture designed specifically for high-efficiency LLM inference',
    enabled: true,
    protocol: 'rss',
    connector: 'd_matrix_ai',
    baseUrl: 'https://www.d-matrix.ai/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'd-Matrix',
    region: 'North America',
    country: 'United States'
  },
  lightmatter_ai: {
    id: 'lightmatter_ai',
    name: 'Lightmatter Photonic Supercomputing',
    description: 'Photonic computing and Passage optical interconnect fabric scaling datacenters for trillion-parameter AI',
    enabled: true,
    protocol: 'rss',
    connector: 'lightmatter_ai',
    baseUrl: 'https://lightmatter.co/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Lightmatter',
    region: 'North America',
    country: 'United States'
  },
  graphcore_ai: {
    id: 'graphcore_ai',
    name: 'Graphcore IPU Intelligence Processing',
    description: 'Intelligence Processing Units (IPUs) with fine-grained parallelism for next-generation machine intelligence',
    enabled: true,
    protocol: 'rss',
    connector: 'graphcore_ai',
    baseUrl: 'https://www.graphcore.ai/posts/rss.xml',
    authType: 'none',
    categories: ['ai-hardware', 'semiconductors', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Graphcore (SoftBank Group)',
    region: 'Europe',
    country: 'United Kingdom'
  },

  // === 4. ROBOTICS, HUMANOIDS & AUTONOMOUS MOBILITY ===
  figure_robotics: {
    id: 'figure_robotics',
    name: 'Figure AI Humanoid Robotics',
    description: 'Commercially viable autonomous general-purpose humanoid robots (Figure 01 & 02) integrated with vision-language models',
    enabled: true,
    protocol: 'rss',
    connector: 'figure_robotics',
    baseUrl: 'https://www.figure.ai/rss.xml',
    authType: 'none',
    categories: ['robotics', 'ai', 'ai-hardware'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Figure AI',
    region: 'North America',
    country: 'United States'
  },
  onex_technologies: {
    id: 'onex_technologies',
    name: '1X Technologies Android Robotics',
    description: 'Safe androids (EVE & NEO) designed to meet global labor demand and work alongside humans in homes and factories',
    enabled: true,
    protocol: 'rss',
    connector: 'onex_technologies',
    baseUrl: 'https://www.1x.tech/blog/rss.xml',
    authType: 'none',
    categories: ['robotics', 'ai', 'ai-hardware'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: '1X Technologies',
    region: 'Europe',
    country: 'Norway'
  },
  sanctuary_ai: {
    id: 'sanctuary_ai',
    name: 'Sanctuary AI General Purpose Robots',
    description: 'Creating the world’s first human-like intelligence in general-purpose robots (Phoenix) with Carbon AI control system',
    enabled: true,
    protocol: 'rss',
    connector: 'sanctuary_ai',
    baseUrl: 'https://www.sanctuary.ai/feed/',
    authType: 'none',
    categories: ['robotics', 'ai', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Sanctuary AI',
    region: 'North America',
    country: 'Canada'
  },
  apptronik_robotics: {
    id: 'apptronik_robotics',
    name: 'Apptronik Apollo Humanoid Robotics',
    description: 'Apollo general-purpose humanoid robot engineered for friendly human interaction and industrial logistics automation',
    enabled: true,
    protocol: 'rss',
    connector: 'apptronik_robotics',
    baseUrl: 'https://apptronik.com/feed/',
    authType: 'none',
    categories: ['robotics', 'ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Apptronik',
    region: 'North America',
    country: 'United States'
  },
  skydio_autonomy: {
    id: 'skydio_autonomy',
    name: 'Skydio Autonomous Drones & Vision AI',
    description: 'Autonomous flight, real-time 3D reconstruction, computer vision obstacle avoidance, and robotic aerial inspections',
    enabled: true,
    protocol: 'rss',
    connector: 'skydio_autonomy',
    baseUrl: 'https://www.skydio.com/blog/rss.xml',
    authType: 'none',
    categories: ['robotics', 'computer-vision', 'ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Skydio Inc.',
    region: 'North America',
    country: 'United States'
  },
  waymo_ai: {
    id: 'waymo_ai',
    name: 'Waymo Autonomous Driving & World Models',
    description: 'The Waymo Driver, fully autonomous ride-hailing systems, multimodal sensor fusion, and foundational driving models',
    enabled: true,
    protocol: 'rss',
    connector: 'waymo_ai',
    baseUrl: 'https://waymo.com/blog/feed.xml',
    authType: 'none',
    categories: ['robotics', 'ai', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Waymo (Alphabet)',
    region: 'North America',
    country: 'United States'
  },
  zoox_autonomy: {
    id: 'zoox_autonomy',
    name: 'Zoox Autonomous Mobility Systems',
    description: 'Ground-up purpose-built bidirectional autonomous robotaxis navigating dense urban environments',
    enabled: true,
    protocol: 'rss',
    connector: 'zoox_autonomy',
    baseUrl: 'https://zoox.com/feed',
    authType: 'none',
    categories: ['robotics', 'ai', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Zoox (Amazon)',
    region: 'North America',
    country: 'United States'
  },
  waabi_ai: {
    id: 'waabi_ai',
    name: 'Waabi Generative AI for Autonomy',
    description: 'AI-first approach to commercial autonomous trucking using generative AI, world models, and physics-informed simulators',
    enabled: true,
    protocol: 'rss',
    connector: 'waabi_ai',
    baseUrl: 'https://waabi.ai/feed/',
    authType: 'none',
    categories: ['robotics', 'ai', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Waabi (Raquel Urtasun)',
    region: 'North America',
    country: 'Canada'
  },

  // === 5. AI SAFETY, STANDARDS & FOUNDATIONS ===
  nist_ai_safety: {
    id: 'nist_ai_safety',
    name: 'NIST Artificial Intelligence & Safety',
    description: 'National Institute of Standards and Technology AI Risk Management Framework and safety evaluations',
    enabled: true,
    protocol: 'rss',
    connector: 'nist_ai_safety',
    baseUrl: 'https://www.nist.gov/news-events/news/rss.xml',
    authType: 'none',
    categories: ['ai-safety', 'policy', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'NIST (United States Department of Commerce)',
    region: 'North America',
    country: 'United States'
  },
  mlcommons_benchmarks: {
    id: 'mlcommons_benchmarks',
    name: 'MLCommons Standards & MLPerf',
    description: 'Open engineering consortium establishing MLPerf training, inference, mobile benchmarks, and safety benchmarks',
    enabled: true,
    protocol: 'rss',
    connector: 'mlcommons_benchmarks',
    baseUrl: 'https://mlcommons.org/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'open-source-ai', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'MLCommons',
    region: 'Global',
    country: 'United States'
  },
  linux_foundation_ai: {
    id: 'linux_foundation_ai',
    name: 'LF AI & Data Foundation',
    description: 'Open source innovation in artificial intelligence, machine learning, and data ecosystems under Linux Foundation',
    enabled: true,
    protocol: 'rss',
    connector: 'linux_foundation_ai',
    baseUrl: 'https://lfaidata.foundation/feed/',
    authType: 'none',
    categories: ['open-source-ai', 'developer-tools', 'cloud'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'The Linux Foundation',
    region: 'Global',
    country: 'United States'
  },
  cncf_ai_wg: {
    id: 'cncf_ai_wg',
    name: 'CNCF Cloud Native AI & ML',
    description: 'Cloud Native Computing Foundation architectures for orchestrating AI workloads, Kubeflow, vLLM on Kubernetes',
    enabled: true,
    protocol: 'rss',
    connector: 'cncf_ai_wg',
    baseUrl: 'https://www.cncf.io/feed/',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'open-source-ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cloud Native Computing Foundation',
    region: 'Global',
    country: 'United States'
  },

  // === 6. PREMIER SCIENCE, QUANTUM & MATHEMATICAL JOURNALS ===
  quanta_ai: {
    id: 'quanta_ai',
    name: 'Quanta Magazine Computer Science & AI',
    description: 'Illuminating mathematics, theoretical computer science, neural network theory, and algorithmic discovery',
    enabled: true,
    protocol: 'rss',
    connector: 'quanta_ai',
    baseUrl: 'https://api.quantamagazine.org/feed/',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Quanta Magazine (Simons Foundation)',
    region: 'North America',
    country: 'United States'
  },
  nature_electronics: {
    id: 'nature_electronics',
    name: 'Nature Electronics & Neuromorphics',
    description: 'Fundamental research across commercial electronics, optical compute, 2D semiconductors, and memristors',
    enabled: true,
    protocol: 'rss',
    connector: 'nature_electronics',
    baseUrl: 'https://www.nature.com/natelectron.rss',
    authType: 'none',
    categories: ['research', 'ai-hardware', 'semiconductors'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Nature Publishing Group',
    region: 'Global',
    country: 'United Kingdom'
  },
  science_robotics: {
    id: 'science_robotics',
    name: 'Science Robotics & Autonomous Systems',
    description: 'The premier scientific journal for robotics research, biomechanics, micro-robotics, and intelligent control',
    enabled: true,
    protocol: 'rss',
    connector: 'science_robotics',
    baseUrl: 'https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=scirobotics',
    authType: 'none',
    categories: ['research', 'robotics', 'ai'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Science (AAAS)',
    region: 'North America',
    country: 'United States'
  },
  acm_technews: {
    id: 'acm_technews',
    name: 'ACM TechNews (Computing Machinery)',
    description: 'Comprehensive global computing and computer engineering news curated by the Association for Computing Machinery',
    enabled: true,
    protocol: 'rss',
    connector: 'acm_technews',
    baseUrl: 'https://technews.acm.org/rss.xml',
    authType: 'none',
    categories: ['research', 'technology', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Association for Computing Machinery (ACM)',
    region: 'Global',
    country: 'United States'
  },
  siam_news: {
    id: 'siam_news',
    name: 'SIAM News (Applied Mathematics & AI)',
    description: 'Society for Industrial and Applied Mathematics news on optimization, numerical analysis, and deep neural theory',
    enabled: true,
    protocol: 'rss',
    connector: 'siam_news',
    baseUrl: 'https://sinews.siam.org/rss',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Society for Industrial and Applied Mathematics',
    region: 'North America',
    country: 'United States'
  }
};
