import { ExtendedSourceDef } from './extended_sources.js';

export const HYPER_SOURCES: Record<string, ExtendedSourceDef> = {
  kernel_org_releases: {
    id: 'kernel_org_releases',
    name: "Linux Kernel Releases (Kernel.org)",
    description: "Official Linux kernel release tracking, mainline tree updates, and long-term support branches",
    enabled: true,
    protocol: 'rss',
    connector: 'kernel_org_releases',
    baseUrl: 'https://www.kernel.org/feeds/kdist.xml',
    authType: 'none',
    categories: ["systems","open-source","programming"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Linux Kernel Organization",
    region: 'Global',
    country: 'United States'
  },
  prometheus_io_blog: {
    id: 'prometheus_io_blog',
    name: "Prometheus Monitoring Blog",
    description: "Cloud native systems monitoring, time-series data collection, alertmanager architectures, and PromQL",
    enabled: true,
    protocol: 'rss',
    connector: 'prometheus_io_blog',
    baseUrl: 'https://prometheus.io/blog/feed.xml',
    authType: 'none',
    categories: ["cloud","devops","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Prometheus (CNCF)",
    region: 'Global',
    country: 'United States'
  },
  gentoo_linux_announcements: {
    id: 'gentoo_linux_announcements',
    name: "Gentoo Linux Official News",
    description: "Rolling-release source-based distribution engineering, Portage package management, and GCC optimizations",
    enabled: true,
    protocol: 'rss',
    connector: 'gentoo_linux_announcements',
    baseUrl: 'https://www.gentoo.org/news/feed.xml',
    authType: 'none',
    categories: ["systems","open-source"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Gentoo Foundation",
    region: 'Global',
    country: 'United States'
  },
  planet_freedesktop_graphics: {
    id: 'planet_freedesktop_graphics',
    name: "Planet Freedesktop Graphics & Wayland",
    description: "Mesa 3D graphics drivers, Wayland display protocols, Vulkan compute, and Linux desktop infrastructure",
    enabled: true,
    protocol: 'atom',
    connector: 'planet_freedesktop_graphics',
    baseUrl: 'https://planet.freedesktop.org/atom.xml',
    authType: 'none',
    categories: ["systems","open-source","hardware"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Freedesktop.org",
    region: 'Global',
    country: 'United States'
  },
  planet_kde_community: {
    id: 'planet_kde_community',
    name: "Planet KDE Desktop & Qt",
    description: "KDE Plasma desktop environment, modern Qt6 development, Kirigami frameworks, and Linux apps",
    enabled: true,
    protocol: 'rss',
    connector: 'planet_kde_community',
    baseUrl: 'https://planet.kde.org/rss20.xml',
    authType: 'none',
    categories: ["systems","open-source"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "KDE e.V.",
    region: 'Global',
    country: 'United States'
  },
  kernel_planet_subsystems: {
    id: 'kernel_planet_subsystems',
    name: "Planet Linux Kernel Maintainers",
    description: "Subsystem maintainer dispatches on eBPF, memory management, scheduler patches, and block layer IO",
    enabled: true,
    protocol: 'rss',
    connector: 'kernel_planet_subsystems',
    baseUrl: 'https://planet.kernel.org/rss20.xml',
    authType: 'none',
    categories: ["systems","open-source"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Planet Kernel",
    region: 'Global',
    country: 'United States'
  },
  qemu_devel_announcements: {
    id: 'qemu_devel_announcements',
    name: "QEMU Machine Emulator and Virtualizer",
    description: "Hardware virtualization, KVM hypervisor integration, TCG dynamic binary translation, and guest CPU support",
    enabled: true,
    protocol: 'rss',
    connector: 'qemu_devel_announcements',
    baseUrl: 'https://www.qemu.org/feed.xml',
    authType: 'none',
    categories: ["systems","virtualization","hardware"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "QEMU Project",
    region: 'Global',
    country: 'United States'
  },
  klara_systems_zfs: {
    id: 'klara_systems_zfs',
    name: "Klara Systems ZFS & FreeBSD Kernel",
    description: "OpenZFS file system internals, FreeBSD kernel performance, memory allocators, and enterprise storage",
    enabled: true,
    protocol: 'rss',
    connector: 'klara_systems_zfs',
    baseUrl: 'https://klarasystems.com/articles/feed/',
    authType: 'none',
    categories: ["systems","cloud"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Klara Systems",
    region: 'Global',
    country: 'United States'
  },
  brendangregg_bpf_perf: {
    id: 'brendangregg_bpf_perf',
    name: "Brendan Gregg Systems Performance & eBPF",
    description: "Systems performance analysis, flame graphs, eBPF observability, and operating system latency profiling",
    enabled: true,
    protocol: 'rss',
    connector: 'brendangregg_bpf_perf',
    baseUrl: 'https://www.brendangregg.com/blog/rss.xml',
    authType: 'none',
    categories: ["systems","cloud","devops"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Brendan Gregg",
    region: 'Global',
    country: 'United States'
  },
  rachel_by_the_bay_sysadmin: {
    id: 'rachel_by_the_bay_sysadmin',
    name: "Rachel by the Bay (Systems Debugging)",
    description: "Hard-won unix debugging stories, catastrophic edge cases, disk corruption analysis, and network packet leaks",
    enabled: true,
    protocol: 'atom',
    connector: 'rachel_by_the_bay_sysadmin',
    baseUrl: 'https://rachelbythebay.com/w/atom.xml',
    authType: 'none',
    categories: ["systems","devops"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Rachel Kroll",
    region: 'Global',
    country: 'United States'
  },
  the_register_hpc_datacenter: {
    id: 'the_register_hpc_datacenter',
    name: "The Register Supercomputing & Hyperscale",
    description: "Supercomputing clusters, TOP500 architectures, exascale computing, and datacenter cooling innovations",
    enabled: true,
    protocol: 'atom',
    connector: 'the_register_hpc_datacenter',
    baseUrl: 'https://www.theregister.com/data_centre/hpc/headlines.atom',
    authType: 'none',
    categories: ["systems","cloud","ai-hardware"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "The Register",
    region: 'United Kingdom',
    country: 'United States'
  },
  networkworld_datacenter_sdn: {
    id: 'networkworld_datacenter_sdn',
    name: "Network World Datacenter SDN & Switching",
    description: "Software-defined networking, 800G Ethernet switching, optical transceivers, and hyperscale fabric design",
    enabled: true,
    protocol: 'rss',
    connector: 'networkworld_datacenter_sdn',
    baseUrl: 'https://www.networkworld.com/category/data-center/index.rss',
    authType: 'none',
    categories: ["cloud","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Network World / Foundry",
    region: 'United States',
    country: 'United States'
  },
  open_compute_datacenter: {
    id: 'open_compute_datacenter',
    name: "Open Compute Project (OCP) Hyperscale Hardware",
    description: "Open standard datacenter server chassis, 48V power distribution, direct liquid cooling, and open racks",
    enabled: true,
    protocol: 'rss',
    connector: 'open_compute_datacenter',
    baseUrl: 'https://www.opencompute.org/feed',
    authType: 'none',
    categories: ["hardware","cloud","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Open Compute Project Foundation",
    region: 'Global',
    country: 'United States'
  },
  cpp_isocpp_foundation: {
    id: 'cpp_isocpp_foundation',
    name: "Standard C++ Foundation (isocpp.org)",
    description: "ISO C++ committee updates, C++26 language specifications, contracts, reflection, and safety profiles",
    enabled: true,
    protocol: 'rss',
    connector: 'cpp_isocpp_foundation',
    baseUrl: 'https://isocpp.org/blog/rss',
    authType: 'none',
    categories: ["programming"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Standard C++ Foundation",
    region: 'Global',
    country: 'United States'
  },
  clojure_org_official: {
    id: 'clojure_org_official',
    name: "Clojure Programming Language News",
    description: "Rich Hickey functional programming philosophy, persistent data structures, ClojureScript, and JVM concurrency",
    enabled: true,
    protocol: 'rss',
    connector: 'clojure_org_official',
    baseUrl: 'https://clojure.org/news/news.xml',
    authType: 'none',
    categories: ["programming"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Clojure.org / Cognitect",
    region: 'Global',
    country: 'United States'
  },
  llvm_weekly_compilers: {
    id: 'llvm_weekly_compilers',
    name: "LLVM Weekly Compilers & Code Generation",
    description: "LLVM backend optimizations, Clang compiler diagnostics, MLIR representation, and code generators",
    enabled: true,
    protocol: 'rss',
    connector: 'llvm_weekly_compilers',
    baseUrl: 'https://llvmweekly.org/rss.xml',
    authType: 'none',
    categories: ["programming","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "LLVM Weekly",
    region: 'Global',
    country: 'United States'
  },
  ruby_weekly_ecosystem: {
    id: 'ruby_weekly_ecosystem',
    name: "Ruby Weekly Language & Rails News",
    description: "Ruby 3.3 YJIT compiler optimizations, Ruby on Rails full-stack architecture, and gem security",
    enabled: true,
    protocol: 'rss',
    connector: 'ruby_weekly_ecosystem',
    baseUrl: 'https://cprss.s3.amazonaws.com/rubyweekly.com.xml',
    authType: 'none',
    categories: ["programming","web"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Cooperpress / Ruby Weekly",
    region: 'Global',
    country: 'United States'
  },
  python_weekly_engineering: {
    id: 'python_weekly_engineering',
    name: "Python Weekly Curated Data & Engineering",
    description: "Curated weekly releases in Python asyncio, data structures, scientific computing, and typing systems",
    enabled: true,
    protocol: 'rss',
    connector: 'python_weekly_engineering',
    baseUrl: 'https://www.pythonweekly.com/archive/rss.xml',
    authType: 'none',
    categories: ["programming","ai"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Python Weekly",
    region: 'Global',
    country: 'United States'
  },
  matt_might_cs_compilers: {
    id: 'matt_might_cs_compilers',
    name: "Matt Might Computer Science & Parsing",
    description: "Derivative parsing algorithms, control flow analysis, compiler architecture, and algorithmic design",
    enabled: true,
    protocol: 'rss',
    connector: 'matt_might_cs_compilers',
    baseUrl: 'https://matt.might.net/articles/feed.rss',
    authType: 'none',
    categories: ["programming","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Matt Might",
    region: 'United States',
    country: 'United States'
  },
  rust_foundation_org: {
    id: 'rust_foundation_org',
    name: "Rust Foundation Grants & Security",
    description: "Rust programming language ecosystem grants, safety audits, infrastructure support, and governance",
    enabled: true,
    protocol: 'rss',
    connector: 'rust_foundation_org',
    baseUrl: 'https://rustfoundation.org/news/feed/',
    authType: 'none',
    categories: ["programming","open-source"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Rust Foundation",
    region: 'Global',
    country: 'United States'
  },
  eclipse_foundation_news: {
    id: 'eclipse_foundation_news',
    name: "Eclipse Foundation Enterprise Java & IDEs",
    description: "Jakarta EE specifications, cloud native IDE development (Theia), and open source developer tooling",
    enabled: true,
    protocol: 'rss',
    connector: 'eclipse_foundation_news',
    baseUrl: 'https://newsroom.eclipse.org/rss/news',
    authType: 'none',
    categories: ["open-source","programming","cloud"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Eclipse Foundation",
    region: 'Global',
    country: 'United States'
  },
  neo4j_graph_database: {
    id: 'neo4j_graph_database',
    name: "Neo4j Graph Database Engineering",
    description: "Graph theory algorithms, property graphs, Cypher query optimization, and GraphRAG knowledge structures",
    enabled: true,
    protocol: 'rss',
    connector: 'neo4j_graph_database',
    baseUrl: 'https://neo4j.com/blog/rss/',
    authType: 'none',
    categories: ["databases","systems","ai"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Neo4j",
    region: 'Global',
    country: 'United States'
  },
  kafka_apache_streaming: {
    id: 'kafka_apache_streaming',
    name: "Apache Kafka Event Streaming",
    description: "Distributed commit log architecture, KRaft consensus, stream processing with Kafka Streams, and connectors",
    enabled: true,
    protocol: 'rss',
    connector: 'kafka_apache_streaming',
    baseUrl: 'https://kafka.apache.org/rss/',
    authType: 'none',
    categories: ["databases","cloud","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Apache Software Foundation",
    region: 'Global',
    country: 'United States'
  },
  couchbase_nosql_db: {
    id: 'couchbase_nosql_db',
    name: "Couchbase Distributed NoSQL & Memory-First",
    description: "Memory-first document database, N1QL SQL-for-JSON engine, mobile edge synchronization, and vector indexes",
    enabled: true,
    protocol: 'rss',
    connector: 'couchbase_nosql_db',
    baseUrl: 'https://www.couchbase.com/blog/feed/',
    authType: 'none',
    categories: ["databases","cloud"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Couchbase",
    region: 'Global',
    country: 'United States'
  },
  influxdata_time_series: {
    id: 'influxdata_time_series',
    name: "InfluxData Time-Series Engine (InfluxDB 3.0)",
    description: "Apache Arrow DataFusion and Parquet-powered columnar time-series storage engine for metrics and IoT",
    enabled: true,
    protocol: 'rss',
    connector: 'influxdata_time_series',
    baseUrl: 'https://www.influxdata.com/feed/',
    authType: 'none',
    categories: ["databases","cloud","devops"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "InfluxData",
    region: 'United States',
    country: 'United States'
  },
  minio_high_perf_s3: {
    id: 'minio_high_perf_s3',
    name: "MinIO High Performance S3 Object Storage",
    description: "Kubernetes-native high throughput S3 compatible object storage, SIMD acceleration, and erasure coding",
    enabled: true,
    protocol: 'rss',
    connector: 'minio_high_perf_s3',
    baseUrl: 'https://blog.min.io/rss/',
    authType: 'none',
    categories: ["cloud","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "MinIO Inc.",
    region: 'United States',
    country: 'United States'
  },
  opensearch_distributed: {
    id: 'opensearch_distributed',
    name: "OpenSearch Distributed Search & Analytics",
    description: "Community-driven open search engine, Lucene vector indexes, neural search, and distributed clustering",
    enabled: true,
    protocol: 'rss',
    connector: 'opensearch_distributed',
    baseUrl: 'https://opensearch.org/feed.xml',
    authType: 'none',
    categories: ["databases","cloud","ai"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "OpenSearch Project (Linux Foundation)",
    region: 'Global',
    country: 'United States'
  },
  apache_spark_analytics: {
    id: 'apache_spark_analytics',
    name: "Apache Spark Large-Scale Analytics",
    description: "Unified computing engine and set of libraries for parallel data processing on computer clusters",
    enabled: true,
    protocol: 'rss',
    connector: 'apache_spark_analytics',
    baseUrl: 'https://spark.apache.org/rss/spark.xml',
    authType: 'none',
    categories: ["databases","cloud","data-science"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Apache Software Foundation",
    region: 'Global',
    country: 'United States'
  },
  apache_iceberg_lakehouse: {
    id: 'apache_iceberg_lakehouse',
    name: "Apache Iceberg Open Table Format",
    description: "High-performance format for huge analytic tables, ACID transactions, and hidden partitioning",
    enabled: true,
    protocol: 'rss',
    connector: 'apache_iceberg_lakehouse',
    baseUrl: 'https://iceberg.apache.org/feed.xml',
    authType: 'none',
    categories: ["databases","cloud"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Apache Software Foundation",
    region: 'Global',
    country: 'United States'
  },
  apache_hudi_lakehouse: {
    id: 'apache_hudi_lakehouse',
    name: "Apache Hudi Streaming Data Lakehouse",
    description: "Streaming data lake platform bringing database and data warehouse core capabilities to data lakes",
    enabled: true,
    protocol: 'rss',
    connector: 'apache_hudi_lakehouse',
    baseUrl: 'https://hudi.apache.org/feed.xml',
    authType: 'none',
    categories: ["databases","cloud"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Apache Software Foundation",
    region: 'Global',
    country: 'United States'
  },
  delta_lake_open_storage: {
    id: 'delta_lake_open_storage',
    name: "Delta Lake ACID Lakehouse Storage",
    description: "Open-source storage framework that enables building a lakehouse architecture on top of data lakes",
    enabled: true,
    protocol: 'rss',
    connector: 'delta_lake_open_storage',
    baseUrl: 'https://delta.io/feed.xml',
    authType: 'none',
    categories: ["databases","cloud"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Linux Foundation / Delta Lake",
    region: 'Global',
    country: 'United States'
  },
  qdrant_vector_similarity: {
    id: 'qdrant_vector_similarity',
    name: "Qdrant Rust Vector Similarity Engine",
    description: "High-performance vector search engine written in Rust with payload filtering, quantization, and HNSW",
    enabled: true,
    protocol: 'rss',
    connector: 'qdrant_vector_similarity',
    baseUrl: 'https://qdrant.tech/articles_rss.xml',
    authType: 'none',
    categories: ["ai","databases","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Qdrant Solutions",
    region: 'Germany',
    country: 'United States'
  },
  eleuther_ai_open_research: {
    id: 'eleuther_ai_open_research',
    name: "EleutherAI Open Science Research",
    description: "Non-profit AI research lab focusing on interpretability, alignment, and open foundation model training",
    enabled: true,
    protocol: 'rss',
    connector: 'eleuther_ai_open_research',
    baseUrl: 'https://blog.eleuther.ai/index.xml',
    authType: 'none',
    categories: ["ai","research","machine-learning"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "EleutherAI",
    region: 'Global',
    country: 'United States'
  },
  fast_ai_deeplearning: {
    id: 'fast_ai_deeplearning',
    name: "fast.ai Practical Machine Learning",
    description: "Making neural networks accessible, practical deep learning architectures, and open PyTorch education",
    enabled: true,
    protocol: 'atom',
    connector: 'fast_ai_deeplearning',
    baseUrl: 'https://www.fast.ai/atom.xml',
    authType: 'none',
    categories: ["ai","machine-learning"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "fast.ai (Jeremy Howard)",
    region: 'Global',
    country: 'United States'
  },
  distill_pub_research: {
    id: 'distill_pub_research',
    name: "Distill ML Visual Research Journal",
    description: "Pioneering clarity in machine learning research through interactive visual essays and neural explorations",
    enabled: true,
    protocol: 'rss',
    connector: 'distill_pub_research',
    baseUrl: 'https://distill.pub/rss.xml',
    authType: 'none',
    categories: ["ai","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Distill Working Group",
    region: 'Global',
    country: 'United States'
  },
  mit_csail_research_wire: {
    id: 'mit_csail_research_wire',
    name: "MIT CSAIL Computer Science Wire",
    description: "Massachusetts Institute of Technology Computer Science and Artificial Intelligence Laboratory breakthroughs",
    enabled: true,
    protocol: 'rss',
    connector: 'mit_csail_research_wire',
    baseUrl: 'https://www.csail.mit.edu/news/rss.xml',
    authType: 'none',
    categories: ["ai","research","robotics"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "MIT CSAIL",
    region: 'United States',
    country: 'United States'
  },
  oreilly_radar_insights: {
    id: 'oreilly_radar_insights',
    name: "O'Reilly Radar Technology Insights",
    description: "Analyzing emerging technology trends, autonomous developer workflows, and architecture shifts",
    enabled: true,
    protocol: 'rss',
    connector: 'oreilly_radar_insights',
    baseUrl: 'https://www.oreilly.com/radar/feed/',
    authType: 'none',
    categories: ["ai","programming","technology"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "O'Reilly Media",
    region: 'United States',
    country: 'United States'
  },
  arxiv_cs_ai_daily: {
    id: 'arxiv_cs_ai_daily',
    name: "ArXiv cs.AI Artificial Intelligence Daily",
    description: "Cornell University daily preprint submissions in generalized artificial intelligence and cognitive reasoning",
    enabled: true,
    protocol: 'rss',
    connector: 'arxiv_cs_ai_daily',
    baseUrl: 'https://arxiv.org/rss/cs.AI',
    authType: 'none',
    categories: ["ai","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "arXiv.org (Cornell University)",
    region: 'Global',
    country: 'United States'
  },
  arxiv_cs_lg_daily: {
    id: 'arxiv_cs_lg_daily',
    name: "ArXiv cs.LG Learning & Neural Nets Daily",
    description: "Machine learning preprints, optimization objectives, Transformer architectures, and loss surfaces",
    enabled: true,
    protocol: 'rss',
    connector: 'arxiv_cs_lg_daily',
    baseUrl: 'https://arxiv.org/rss/cs.LG',
    authType: 'none',
    categories: ["ai","machine-learning","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "arXiv.org (Cornell University)",
    region: 'Global',
    country: 'United States'
  },
  arxiv_cs_cl_daily: {
    id: 'arxiv_cs_cl_daily',
    name: "ArXiv cs.CL Computation and Language Daily",
    description: "Computational linguistics preprints, large language model alignment, grammar parsing, and tokenization",
    enabled: true,
    protocol: 'rss',
    connector: 'arxiv_cs_cl_daily',
    baseUrl: 'https://arxiv.org/rss/cs.CL',
    authType: 'none',
    categories: ["ai","nlp","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "arXiv.org (Cornell University)",
    region: 'Global',
    country: 'United States'
  },
  arxiv_cs_cv_daily: {
    id: 'arxiv_cs_cv_daily',
    name: "ArXiv cs.CV Computer Vision Daily",
    description: "Computer vision preprints, 3D Gaussian splatting, generative diffusion, segmentation, and NeRF models",
    enabled: true,
    protocol: 'rss',
    connector: 'arxiv_cs_cv_daily',
    baseUrl: 'https://arxiv.org/rss/cs.CV',
    authType: 'none',
    categories: ["ai","computer-vision","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "arXiv.org (Cornell University)",
    region: 'Global',
    country: 'United States'
  },
  arxiv_cs_ro_daily: {
    id: 'arxiv_cs_ro_daily',
    name: "ArXiv cs.RO Robotics & Control Daily",
    description: "Robotic manipulation preprints, humanoid locomotion, vision-language-action (VLA) models, and trajectory planning",
    enabled: true,
    protocol: 'rss',
    connector: 'arxiv_cs_ro_daily',
    baseUrl: 'https://arxiv.org/rss/cs.RO',
    authType: 'none',
    categories: ["robotics","ai","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "arXiv.org (Cornell University)",
    region: 'Global',
    country: 'United States'
  },
  arxiv_cs_cr_daily: {
    id: 'arxiv_cs_cr_daily',
    name: "ArXiv cs.CR Cryptography and Security Daily",
    description: "Post-quantum cryptography, zero-knowledge proofs, side-channel attacks, and cryptographic hardware verification",
    enabled: true,
    protocol: 'rss',
    connector: 'arxiv_cs_cr_daily',
    baseUrl: 'https://arxiv.org/rss/cs.CR',
    authType: 'none',
    categories: ["security","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "arXiv.org (Cornell University)",
    region: 'Global',
    country: 'United States'
  },
  arxiv_cs_se_daily: {
    id: 'arxiv_cs_se_daily',
    name: "ArXiv cs.SE Software Engineering Daily",
    description: "Automated software synthesis preprints, static code analysis, fault localization, and test suite generation",
    enabled: true,
    protocol: 'rss',
    connector: 'arxiv_cs_se_daily',
    baseUrl: 'https://arxiv.org/rss/cs.SE',
    authType: 'none',
    categories: ["programming","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "arXiv.org (Cornell University)",
    region: 'Global',
    country: 'United States'
  },
  arxiv_cs_dc_daily: {
    id: 'arxiv_cs_dc_daily',
    name: "ArXiv cs.DC Distributed Computing Daily",
    description: "Cluster architectures, consensus protocols, pipeline parallelism, and distributed model training schedules",
    enabled: true,
    protocol: 'rss',
    connector: 'arxiv_cs_dc_daily',
    baseUrl: 'https://arxiv.org/rss/cs.DC',
    authType: 'none',
    categories: ["systems","cloud","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "arXiv.org (Cornell University)",
    region: 'Global',
    country: 'United States'
  },
  arxiv_cs_ne_daily: {
    id: 'arxiv_cs_ne_daily',
    name: "ArXiv cs.NE Neural and Evolutionary Computing",
    description: "Neuromorphic architectures, spiking neural nets, evolutionary algorithms, and bio-inspired computing",
    enabled: true,
    protocol: 'rss',
    connector: 'arxiv_cs_ne_daily',
    baseUrl: 'https://arxiv.org/rss/cs.NE',
    authType: 'none',
    categories: ["ai","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "arXiv.org (Cornell University)",
    region: 'Global',
    country: 'United States'
  },
  arxiv_cs_ar_daily: {
    id: 'arxiv_cs_ar_daily',
    name: "ArXiv cs.AR Hardware Architecture Daily",
    description: "Processor microarchitecture, high-bandwidth memory (HBM) interconnects, systolic arrays, and accelerator chips",
    enabled: true,
    protocol: 'rss',
    connector: 'arxiv_cs_ar_daily',
    baseUrl: 'https://arxiv.org/rss/cs.AR',
    authType: 'none',
    categories: ["hardware","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "arXiv.org (Cornell University)",
    region: 'Global',
    country: 'United States'
  },
  swyx_latent_space_notes: {
    id: 'swyx_latent_space_notes',
    name: "Swyx Latent Thoughts & AI Engineering",
    description: "Essays by Shawn Wang (swyx) on AI engineer skillsets, autonomous agent architectures, and LLM evaluations",
    enabled: true,
    protocol: 'rss',
    connector: 'swyx_latent_space_notes',
    baseUrl: 'https://www.swyx.io/rss.xml',
    authType: 'none',
    categories: ["ai","programming"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Swyx (Shawn Wang)",
    region: 'United States',
    country: 'United States'
  },
  eugeneyan_applied_machine_learning: {
    id: 'eugeneyan_applied_machine_learning',
    name: "Eugene Yan Applied ML Systems",
    description: "Practical patterns for machine learning in production, real-time recommendation engines, and LLM evaluations",
    enabled: true,
    protocol: 'rss',
    connector: 'eugeneyan_applied_machine_learning',
    baseUrl: 'https://eugeneyan.com/rss/',
    authType: 'none',
    categories: ["ai","machine-learning","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Eugene Yan",
    region: 'United States',
    country: 'United States'
  },
  colah_neural_networks_blog: {
    id: 'colah_neural_networks_blog',
    name: "Christopher Olah Neural Network Interpretability",
    description: "Foundational visual essays on understanding neural representations, attention heads, and circuits",
    enabled: true,
    protocol: 'rss',
    connector: 'colah_neural_networks_blog',
    baseUrl: 'https://colah.github.io/rss.xml',
    authType: 'none',
    categories: ["ai","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Christopher Olah (Anthropic)",
    region: 'United States',
    country: 'United States'
  },
  astralcodexten_rationality: {
    id: 'astralcodexten_rationality',
    name: "Astral Codex Ten (Scott Alexander)",
    description: "Long-form rationalist analysis of artificial intelligence trajectory, cognitive science, and forecasting",
    enabled: true,
    protocol: 'rss',
    connector: 'astralcodexten_rationality',
    baseUrl: 'https://www.astralcodexten.com/feed',
    authType: 'none',
    categories: ["ai","research","technology"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Scott Alexander",
    region: 'United States',
    country: 'United States'
  },
  nature_electronics_journal: {
    id: 'nature_electronics_journal',
    name: "Nature Electronics Microdevices & Silicon",
    description: "Peer-reviewed research in microelectronics, memristors, 2D semiconductors, and neuromorphic chips",
    enabled: true,
    protocol: 'rss',
    connector: 'nature_electronics_journal',
    baseUrl: 'https://www.nature.com/natelectron.rss',
    authType: 'none',
    categories: ["hardware","semiconductors","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Nature Publishing Group",
    region: 'Global',
    country: 'United States'
  },
  nature_computational_science: {
    id: 'nature_computational_science',
    name: "Nature Computational Science High Performance Algorithms",
    description: "Peer-reviewed research in high-performance computing, scientific ML, multiscale simulations, and solvers",
    enabled: true,
    protocol: 'rss',
    connector: 'nature_computational_science',
    baseUrl: 'https://www.nature.com/natcomputsci.rss',
    authType: 'none',
    categories: ["research","ai","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Nature Publishing Group",
    region: 'Global',
    country: 'United States'
  },
  cern_physics_computing: {
    id: 'cern_physics_computing',
    name: "CERN High Energy Physics & Grid Computing",
    description: "Large Hadron Collider scientific computing grid, petabyte data acquisition pipelines, and sensor electronics",
    enabled: true,
    protocol: 'rss',
    connector: 'cern_physics_computing',
    baseUrl: 'https://home.cern/rss/news.xml',
    authType: 'none',
    categories: ["research","systems","hardware"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "CERN (European Organization for Nuclear Research)",
    region: 'Switzerland',
    country: 'United States'
  },
  bair_berkeley_ai_lab: {
    id: 'bair_berkeley_ai_lab',
    name: "Berkeley Artificial Intelligence Research (BAIR)",
    description: "UC Berkeley research dispatches on reinforcement learning, robot learning, multi-modal reasoning, and open models",
    enabled: true,
    protocol: 'rss',
    connector: 'bair_berkeley_ai_lab',
    baseUrl: 'https://bair.berkeley.edu/blog/feed.xml',
    authType: 'none',
    categories: ["ai","research","robotics"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "UC Berkeley AI Research",
    region: 'United States',
    country: 'United States'
  },
  deepmind_safety_research_team: {
    id: 'deepmind_safety_research_team',
    name: "Google DeepMind Alignment & Model Safety",
    description: "Technical investigations into neural red teaming, scalable oversight, specification gaming, and mechanistic interpretability",
    enabled: true,
    protocol: 'rss',
    connector: 'deepmind_safety_research_team',
    baseUrl: 'https://deepmindsafetyresearch.medium.com/feed',
    authType: 'none',
    categories: ["ai","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Google DeepMind Safety",
    region: 'United Kingdom',
    country: 'United States'
  },
  scikit_learn_ml_blog: {
    id: 'scikit_learn_ml_blog',
    name: "Scikit-Learn Machine Learning in Python",
    description: "Official development updates for the standard Python machine learning library, Cython optimizations, and estimators",
    enabled: true,
    protocol: 'rss',
    connector: 'scikit_learn_ml_blog',
    baseUrl: 'https://blog.scikit-learn.org/feed.xml',
    authType: 'none',
    categories: ["ai","machine-learning","programming"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Scikit-Learn Consortium",
    region: 'France',
    country: 'United States'
  },
  rapid7_threat_analysis: {
    id: 'rapid7_threat_analysis',
    name: "Rapid7 Vulnerability & Threat Research",
    description: "Emergent threat advisories, Metasploit modules, vulnerability exploitation vectors, and incident telemetry",
    enabled: true,
    protocol: 'rss',
    connector: 'rapid7_threat_analysis',
    baseUrl: 'https://www.rapid7.com/blog/feed/',
    authType: 'none',
    categories: ["cybersecurity"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Rapid7 Labs",
    region: 'United States',
    country: 'United States'
  },
  packet_storm_security: {
    id: 'packet_storm_security',
    name: "Packet Storm Security Exploits & Advisories",
    description: "Public disclosures of security vulnerabilities, proof-of-concept exploits, CVE references, and advisories",
    enabled: true,
    protocol: 'rss',
    connector: 'packet_storm_security',
    baseUrl: 'https://rss.packetstormsecurity.com/news/',
    authType: 'none',
    categories: ["cybersecurity"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Packet Storm Security",
    region: 'Global',
    country: 'United States'
  },
  darknet_ethical_hacking: {
    id: 'darknet_ethical_hacking',
    name: "Darknet Ethical Hacking & Pen Testing",
    description: "Penetration testing utilities, wireless security, reverse engineering tools, and network auditing frameworks",
    enabled: true,
    protocol: 'rss',
    connector: 'darknet_ethical_hacking',
    baseUrl: 'https://www.darknet.org.uk/feed/',
    authType: 'none',
    categories: ["cybersecurity"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Darknet Hacker Tools",
    region: 'United Kingdom',
    country: 'United States'
  },
  seclists_bugtraq_full: {
    id: 'seclists_bugtraq_full',
    name: "SecLists Full Disclosure Vulnerability Feed",
    description: "Real-time mailing list archives of zero-day vulnerabilities, vendor bug disclosures, and security audits",
    enabled: true,
    protocol: 'rss',
    connector: 'seclists_bugtraq_full',
    baseUrl: 'https://seclists.org/rss/fulldisclosure.rss',
    authType: 'none',
    categories: ["cybersecurity"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "SecLists (Fyodor / Insecure.Org)",
    region: 'Global',
    country: 'United States'
  },
  tarsnap_security_notes: {
    id: 'tarsnap_security_notes',
    name: "Colin Percival (Tarsnap Secure Cryptography)",
    description: "Scrypt key derivation function, provably secure cloud backups, FreeBSD security officer retrospectives",
    enabled: true,
    protocol: 'rss',
    connector: 'tarsnap_security_notes',
    baseUrl: 'https://www.daemonology.net/blog/index.rss',
    authType: 'none',
    categories: ["cybersecurity","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Colin Percival",
    region: 'Canada',
    country: 'United States'
  },
  the_register_security_wire: {
    id: 'the_register_security_wire',
    name: "The Register Security, Malware & Exploits",
    description: "Critical cyber threat coverage, state-sponsored cyber espionage, ransomware syndicates, and hardware flaws",
    enabled: true,
    protocol: 'atom',
    connector: 'the_register_security_wire',
    baseUrl: 'https://www.theregister.com/security/headlines.atom',
    authType: 'none',
    categories: ["cybersecurity"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "The Register",
    region: 'United Kingdom',
    country: 'United States'
  },
  moxie_signal_cryptography: {
    id: 'moxie_signal_cryptography',
    name: "Moxie Marlinspike Cryptography & Privacy",
    description: "Signal protocol architectures, double ratchet end-to-end encryption, and decentralization critiques",
    enabled: true,
    protocol: 'rss',
    connector: 'moxie_signal_cryptography',
    baseUrl: 'https://moxie.org/feed.xml',
    authType: 'none',
    categories: ["cybersecurity","programming"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Moxie Marlinspike",
    region: 'United States',
    country: 'United States'
  },
  sparkfun_electronics_diy: {
    id: 'sparkfun_electronics_diy',
    name: "SparkFun Electronics Open Hardware",
    description: "Microcontroller tutorials (ESP32, RP2040), I2C sensors, KiCad PCB layout tips, and open hardware electronics",
    enabled: true,
    protocol: 'rss',
    connector: 'sparkfun_electronics_diy',
    baseUrl: 'https://www.sparkfun.com/news/rss',
    authType: 'none',
    categories: ["hardware"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "SparkFun Electronics",
    region: 'United States',
    country: 'United States'
  },
  bunnie_studios_hardware: {
    id: 'bunnie_studios_hardware',
    name: "Bunnie Huang (Bunnie Studios Hardware)",
    description: "Silicon supply chain transparency, Precursor open hardware trust, FPGA emulation, and factory teardowns",
    enabled: true,
    protocol: 'rss',
    connector: 'bunnie_studios_hardware',
    baseUrl: 'https://www.bunniestudios.com/blog/?feed=rss2',
    authType: 'none',
    categories: ["hardware","semiconductors"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Andrew 'bunnie' Huang",
    region: 'Singapore',
    country: 'United States'
  },
  toms_hardware_global_wire: {
    id: 'toms_hardware_global_wire',
    name: "Tom's Hardware Global Technology Wire",
    description: "Hardware teardowns, CPU and GPU silicon benchmark charts, memory timings, and overclocking records",
    enabled: true,
    protocol: 'rss',
    connector: 'toms_hardware_global_wire',
    baseUrl: 'https://www.tomshardware.com/feeds/rss/news',
    authType: 'none',
    categories: ["hardware","ai-hardware"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Tom's Hardware",
    region: 'United States',
    country: 'United States'
  },
  overclock3d_silicon_news: {
    id: 'overclock3d_silicon_news',
    name: "OC3D Overclock3D Hardware & Silicon",
    description: "PC hardware benchmarks, architectural comparisons, cooling reviews, and graphics card engineering analysis",
    enabled: true,
    protocol: 'rss',
    connector: 'overclock3d_silicon_news',
    baseUrl: 'https://www.overclock3d.net/news/rss/',
    authType: 'none',
    categories: ["hardware","semiconductors"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Overclock3D",
    region: 'United Kingdom',
    country: 'United States'
  },
  phys_org_technology_nanotech: {
    id: 'phys_org_technology_nanotech',
    name: "Phys.org Nanotechnology & Quantum Tech",
    description: "Breakthrough physics research in quantum dots, topological insulators, superconductor fabrication, and optics",
    enabled: true,
    protocol: 'rss',
    connector: 'phys_org_technology_nanotech',
    baseUrl: 'https://phys.org/rss-feed/technology-news/',
    authType: 'none',
    categories: ["hardware","quantum-computing","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Phys.org / Science X Network",
    region: 'Global',
    country: 'United States'
  },
  cnx_software_embedded_sbc: {
    id: 'cnx_software_embedded_sbc',
    name: "CNX Software Embedded Systems & ARM",
    description: "Single board computers (Raspberry Pi, Orange Pi, Rockchip), RISC-V development boards, and embedded Linux",
    enabled: true,
    protocol: 'rss',
    connector: 'cnx_software_embedded_sbc',
    baseUrl: 'https://www.cnx-software.com/feed/',
    authType: 'none',
    categories: ["hardware","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "CNX Software",
    region: 'Global',
    country: 'United States'
  },
  linux_gizmos_embedded_iot: {
    id: 'linux_gizmos_embedded_iot',
    name: "LinuxGizmos Embedded Linux & IoT",
    description: "Industrial computer-on-modules (COMs), ARM Cortex-A system-on-chips, and open hardware development kits",
    enabled: true,
    protocol: 'rss',
    connector: 'linux_gizmos_embedded_iot',
    baseUrl: 'https://linuxgizmos.com/feed/',
    authType: 'none',
    categories: ["hardware","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "LinuxGizmos",
    region: 'United States',
    country: 'United States'
  },
  mit_news_quantum_photonics: {
    id: 'mit_news_quantum_photonics',
    name: "MIT News Quantum Science & Superconductors",
    description: "MIT research in superconducting qubits, photonic quantum computation, and diamond nitrogen-vacancy centers",
    enabled: true,
    protocol: 'rss',
    connector: 'mit_news_quantum_photonics',
    baseUrl: 'https://news.mit.edu/rss/topic/quantum-science-and-engineering',
    authType: 'none',
    categories: ["quantum-computing","hardware","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "MIT News Office",
    region: 'United States',
    country: 'United States'
  },
  mit_news_robotics_autonomy: {
    id: 'mit_news_robotics_autonomy',
    name: "MIT News Robotics, Humanoids & Autonomy",
    description: "MIT research in soft robotics, quadruped locomotion, tactile sensing fingers, and autonomous drones",
    enabled: true,
    protocol: 'rss',
    connector: 'mit_news_robotics_autonomy',
    baseUrl: 'https://news.mit.edu/rss/topic/robotics',
    authType: 'none',
    categories: ["robotics","ai","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "MIT News Office",
    region: 'United States',
    country: 'United States'
  },
  mit_news_materials_nano: {
    id: 'mit_news_materials_nano',
    name: "MIT News Advanced Materials & Photonics",
    description: "MIT research in two-dimensional graphene lattices, ultra-dense battery anodes, and photonic crystal waveguides",
    enabled: true,
    protocol: 'rss',
    connector: 'mit_news_materials_nano',
    baseUrl: 'https://news.mit.edu/rss/topic/materials-science-and-engineering',
    authType: 'none',
    categories: ["hardware","research"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "MIT News Office",
    region: 'United States',
    country: 'United States'
  },
  arm_community_silicon_arch: {
    id: 'arm_community_silicon_arch',
    name: "Arm Community Microarchitecture & Neoverse",
    description: "Armv9 instruction set features, SVE2 vector extensions, Neoverse server cores, and confidential compute",
    enabled: true,
    protocol: 'rss',
    connector: 'arm_community_silicon_arch',
    baseUrl: 'https://community.arm.com/arm-community-blogs/b/architectures-and-processors-blog/rss',
    authType: 'none',
    categories: ["hardware","semiconductors"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Arm Ltd.",
    region: 'United Kingdom',
    country: 'United States'
  },
  lowrisc_opentitan_silicon: {
    id: 'lowrisc_opentitan_silicon',
    name: "lowRISC Open Source Silicon & OpenTitan",
    description: "Open source silicon design, OpenTitan commercial root of trust, and Ibex RISC-V core verification",
    enabled: true,
    protocol: 'rss',
    connector: 'lowrisc_opentitan_silicon',
    baseUrl: 'https://www.lowrisc.org/feed.xml',
    authType: 'none',
    categories: ["hardware","security","open-source"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "lowRISC CIC",
    region: 'United Kingdom',
    country: 'United States'
  },
  chips_alliance_open_eda: {
    id: 'chips_alliance_open_eda',
    name: "CHIPS Alliance Open Source EDA Tools",
    description: "Open source silicon design verification, Verilator simulation, Chisel HDL, and open interconnect specifications",
    enabled: true,
    protocol: 'rss',
    connector: 'chips_alliance_open_eda',
    baseUrl: 'https://chipsalliance.org/feed/',
    authType: 'none',
    categories: ["hardware","open-source","semiconductors"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "CHIPS Alliance (Linux Foundation)",
    region: 'Global',
    country: 'United States'
  },
  youtube_ml_street_talk_channel: {
    id: 'youtube_ml_street_talk_channel',
    name: "Machine Learning Street Talk (YouTube)",
    description: "Tim Scarfe deep academic dialogues on mechanistic interpretability, category theory in ML, and neurosymbolic AI",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_ml_street_talk_channel',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCMLtBahI5DMrt0NPvDSoIRQ',
    authType: 'none',
    categories: ["ai","research","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Machine Learning Street Talk",
    region: 'Global',
    country: 'United States'
  },
  youtube_matthew_berman_llm: {
    id: 'youtube_matthew_berman_llm',
    name: "Matthew Berman AI & Local LLMs (YouTube)",
    description: "Hands-on benchmarking of local open-weights LLMs, Ollama, vLLM setups, fine-tuning, and AI agent frameworks",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_matthew_berman_llm',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCaw1fl2WqNlDOslp4p_mP0w',
    authType: 'none',
    categories: ["ai","developer-tools","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Matthew Berman",
    region: 'United States',
    country: 'United States'
  },
  youtube_david_shapiro_agi: {
    id: 'youtube_david_shapiro_agi',
    name: "David Shapiro Cognitive Architecture (YouTube)",
    description: "Autonomous agent frameworks, cognitive architectures, AGI milestones, and post-labor economics",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_david_shapiro_agi',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC6z9pwhWwU6gQ7b-Yk9f39g',
    authType: 'none',
    categories: ["ai","ai-agents","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "David Shapiro",
    region: 'United States',
    country: 'United States'
  },
  youtube_all_in_podcast_tech: {
    id: 'youtube_all_in_podcast_tech',
    name: "All-In Podcast Tech & Macro (YouTube)",
    description: "Chamath Palihapitiya, Jason Calacanis, David Sacks, and David Friedberg on AI capex, venture capital, and macro tech",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_all_in_podcast_tech',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCESLZhusAkFfsNsApnjF_Cg',
    authType: 'none',
    categories: ["technology","startups","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "All-In Podcast",
    region: 'United States',
    country: 'United States'
  },
  youtube_no_priors_ai_podcast: {
    id: 'youtube_no_priors_ai_podcast',
    name: "No Priors AI & Frontier Founders (YouTube)",
    description: "Elad Gil and Sarah Guo interviewing top AI researchers, frontier lab founders, and autonomous system builders",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_no_priors_ai_podcast',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCa7U401rM9VfFpQ8p7gK4kg',
    authType: 'none',
    categories: ["ai","startups","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "No Priors Podcast",
    region: 'United States',
    country: 'United States'
  },
  youtube_dwarkesh_patel_interviews: {
    id: 'youtube_dwarkesh_patel_interviews',
    name: "Dwarkesh Patel Frontier Podcasts (YouTube)",
    description: "Deep multi-hour dialogues with leading scientists on AI scaling laws, semiconductor supply chains, and superintelligence",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_dwarkesh_patel_interviews',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC8tZ9Vv9oA_lGZtEa85Xv7Q',
    authType: 'none',
    categories: ["ai","research","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Dwarkesh Patel",
    region: 'United States',
    country: 'United States'
  },
  youtube_the_primeagen_show: {
    id: 'youtube_the_primeagen_show',
    name: "ThePrimeTime Developer News (YouTube)",
    description: "Fast-paced software engineering reactions, terminal workflows, Neovim configs, and systems programming commentary",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_the_primeagen_show',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCUyeluBRhGPCW4rPe_UvBZQ',
    authType: 'none',
    categories: ["programming","developer-tools","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "ThePrimeagen",
    region: 'United States',
    country: 'United States'
  },
  youtube_networkchunk_dev_labs: {
    id: 'youtube_networkchunk_dev_labs',
    name: "NetworkChunk Cloud & Linux Labs (YouTube)",
    description: "Hands-on practical tutorials in Linux homelabs, Docker, Proxmox, WireGuard VPNs, and cloud architecture",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_networkchunk_dev_labs',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC46w_IfAr51338vDeCh014g',
    authType: 'none',
    categories: ["devops","cloud","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "NetworkChunk",
    region: 'United States',
    country: 'United States'
  },
  youtube_john_hammond_security: {
    id: 'youtube_john_hammond_security',
    name: "John Hammond Cybersecurity & Malware (YouTube)",
    description: "Malware analysis, capture-the-flag (CTF) walkthroughs, threat actor tactic dissections, and incident response",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_john_hammond_security',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCVeW9qkBjo3zosnqUbG7CFw',
    authType: 'none',
    categories: ["cybersecurity","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "John Hammond",
    region: 'United States',
    country: 'United States'
  },
  youtube_liveoverflow_security: {
    id: 'youtube_liveoverflow_security',
    name: "LiveOverflow Binary Exploitation (YouTube)",
    description: "In-depth binary exploitation, memory corruption, return-oriented programming (ROP), and hardware hacking",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_liveoverflow_security',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UClcRf_vwKhtuhbgizpC63MQ',
    authType: 'none',
    categories: ["cybersecurity","programming","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "LiveOverflow",
    region: 'Germany',
    country: 'United States'
  },
  youtube_fireship_clips_code: {
    id: 'youtube_fireship_clips_code',
    name: "Fireship 100 Seconds of Code (YouTube)",
    description: "High-density developer breakdowns of software engineering concepts, database internals, and modern frameworks",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_fireship_clips_code',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCipSxT7a3pnZZRVQK10guew',
    authType: 'none',
    categories: ["programming","developer-tools","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Fireship (Jeff Delaney)",
    region: 'United States',
    country: 'United States'
  },
  youtube_engineering_utsav: {
    id: 'youtube_engineering_utsav',
    name: "Engineering with Utsav (Distributed Systems)",
    description: "Real-world distributed systems case studies, system design interviews, Kafka architectures, and cache coherence",
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_engineering_utsav',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCY5sVep_bFq0VwJ3N4n8jvg',
    authType: 'none',
    categories: ["systems","cloud","video"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Engineering with Utsav",
    region: 'United States',
    country: 'United States'
  },
  frontend_focus_weekly: {
    id: 'frontend_focus_weekly',
    name: "Frontend Focus Weekly Web Dev",
    description: "Weekly digest of HTML5, CSS Grid, Web Components, modern browser APIs, and frontend performance",
    enabled: true,
    protocol: 'rss',
    connector: 'frontend_focus_weekly',
    baseUrl: 'https://cprss.s3.amazonaws.com/frontendfoc.us.xml',
    authType: 'none',
    categories: ["programming","web"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Cooperpress / Frontend Focus",
    region: 'Global',
    country: 'United States'
  },
  node_weekly_backend_js: {
    id: 'node_weekly_backend_js',
    name: "Node Weekly Server-Side JavaScript",
    description: "Node.js core releases, asynchronous iteration, TypeScript backends, Express/Fastify updates, and worker threads",
    enabled: true,
    protocol: 'rss',
    connector: 'node_weekly_backend_js',
    baseUrl: 'https://cprss.s3.amazonaws.com/nodeweekly.com.xml',
    authType: 'none',
    categories: ["programming","web"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Cooperpress / Node Weekly",
    region: 'Global',
    country: 'United States'
  },
  chromium_engine_blog: {
    id: 'chromium_engine_blog',
    name: "Chromium Official Blog",
    description: "Google Chrome and Chromium open source engine advances, Blink rendering engine, and web standards",
    enabled: true,
    protocol: 'atom',
    connector: 'chromium_engine_blog',
    baseUrl: 'https://blog.chromium.org/feeds/posts/default',
    authType: 'none',
    categories: ["web","open-source"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Chromium Project (Google)",
    region: 'United States',
    country: 'United States'
  },
  android_developers_blog: {
    id: 'android_developers_blog',
    name: "Android Developers Official Blog",
    description: "Android OS platform releases, Jetpack Compose UI toolkit, ART runtime improvements, and Kotlin updates",
    enabled: true,
    protocol: 'atom',
    connector: 'android_developers_blog',
    baseUrl: 'https://android-developers.googleblog.com/feeds/posts/default',
    authType: 'none',
    categories: ["programming","technology"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Google Android Engineering",
    region: 'United States',
    country: 'United States'
  },
  flutter_official_medium: {
    id: 'flutter_official_medium',
    name: "Flutter UI Framework News",
    description: "Cross-platform native compilation, Dart language updates, Impeller rendering engine, and desktop UI",
    enabled: true,
    protocol: 'rss',
    connector: 'flutter_official_medium',
    baseUrl: 'https://medium.com/feed/flutter',
    authType: 'none',
    categories: ["programming","developer-tools"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Google Flutter Team",
    region: 'United States',
    country: 'United States'
  },
  blender_3d_foundation: {
    id: 'blender_3d_foundation',
    name: "Blender 3D Graphics Foundation",
    description: "Cycles path-tracing engine, geometry nodes, real-time EEVEE rendering, and open source 3D graphics creation",
    enabled: true,
    protocol: 'rss',
    connector: 'blender_3d_foundation',
    baseUrl: 'https://www.blender.org/feed/',
    authType: 'none',
    categories: ["open-source","graphics"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Blender Foundation",
    region: 'Netherlands',
    country: 'United States'
  },
  fastly_edge_cloud_blog: {
    id: 'fastly_edge_cloud_blog',
    name: "Fastly Edge Cloud & WebAssembly",
    description: "Edge computing architectures, Lucet WebAssembly runtime, Varnish cache configurations, and DDoS mitigation",
    enabled: true,
    protocol: 'rss',
    connector: 'fastly_edge_cloud_blog',
    baseUrl: 'https://www.fastly.com/blog/rss.xml',
    authType: 'none',
    categories: ["cloud","systems","programming"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Fastly",
    region: 'United States',
    country: 'United States'
  },
  stripe_engineering_fintech: {
    id: 'stripe_engineering_fintech',
    name: "Stripe Payments Infrastructure Engineering",
    description: "Idempotency in distributed financial ledgers, Sorbet Ruby type-checker, and zero-downtime database migrations",
    enabled: true,
    protocol: 'rss',
    connector: 'stripe_engineering_fintech',
    baseUrl: 'https://stripe.com/blog/engineering/rss.xml',
    authType: 'none',
    categories: ["systems","cloud","programming"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Stripe Engineering",
    region: 'United States',
    country: 'United States'
  },
  linkedin_engineering_feed: {
    id: 'linkedin_engineering_feed',
    name: "LinkedIn Engineering Distributed Systems",
    description: "Rest.li microservices framework, Pinot real-time OLAP engine, and graph database infrastructure",
    enabled: true,
    protocol: 'rss',
    connector: 'linkedin_engineering_feed',
    baseUrl: 'https://engineering.linkedin.com/blog.rss',
    authType: 'none',
    categories: ["systems","cloud","databases"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "LinkedIn Engineering",
    region: 'United States',
    country: 'United States'
  },
  meta_open_source_blog: {
    id: 'meta_open_source_blog',
    name: "Meta Open Source Frameworks & Systems",
    description: "PyTorch, React, RocksDB, Zstandard compression, Velox vectorized engine, and Open Cellular hardware",
    enabled: true,
    protocol: 'rss',
    connector: 'meta_open_source_blog',
    baseUrl: 'https://engineering.fb.com/category/open-source/feed/',
    authType: 'none',
    categories: ["open-source","systems","programming"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Meta Open Source",
    region: 'United States',
    country: 'United States'
  },
  coreweave_gpu_cloud: {
    id: 'coreweave_gpu_cloud',
    name: "CoreWeave Specialized GPU Cloud",
    description: "Specialized Kubernetes cloud architecture optimized for large-scale GPU workloads and InfiniBand clusters",
    enabled: true,
    protocol: 'rss',
    connector: 'coreweave_gpu_cloud',
    baseUrl: 'https://www.coreweave.com/blog/rss.xml',
    authType: 'none',
    categories: ["cloud","ai-hardware","ai"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "CoreWeave",
    region: 'United States',
    country: 'United States'
  },
  lambda_labs_deep_learning: {
    id: 'lambda_labs_deep_learning',
    name: "Lambda Labs GPU Workstations & Cloud",
    description: "NVIDIA GPU training benchmarks, PyTorch cluster performance, thermal testing, and 1-Click ML clusters",
    enabled: true,
    protocol: 'rss',
    connector: 'lambda_labs_deep_learning',
    baseUrl: 'https://lambdalabs.com/blog/rss.xml',
    authType: 'none',
    categories: ["ai-hardware","machine-learning","cloud"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Lambda Labs",
    region: 'United States',
    country: 'United States'
  },
  istio_service_mesh_cloud: {
    id: 'istio_service_mesh_cloud',
    name: "Istio Service Mesh Architecture",
    description: "Mutual TLS (mTLS) enforcement, traffic routing rules, distributed tracing, and ambient mesh data planes",
    enabled: true,
    protocol: 'rss',
    connector: 'istio_service_mesh_cloud',
    baseUrl: 'https://istio.io/latest/feed.xml',
    authType: 'none',
    categories: ["cloud","security","devops"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Istio Project (CNCF)",
    region: 'Global',
    country: 'United States'
  },
  linkerd_service_mesh_rust: {
    id: 'linkerd_service_mesh_rust',
    name: "Linkerd Lightweight Rust Service Mesh",
    description: "Micro-proxy design in Rust (linkerd2-proxy), transparent mutual TLS, and zero-config Kubernetes networking",
    enabled: true,
    protocol: 'rss',
    connector: 'linkerd_service_mesh_rust',
    baseUrl: 'https://linkerd.io/feed.xml',
    authType: 'none',
    categories: ["cloud","security","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Linkerd (CNCF / Buoyant)",
    region: 'Global',
    country: 'United States'
  },
  opentelemetry_observability: {
    id: 'opentelemetry_observability',
    name: "OpenTelemetry Distributed Tracing & Metrics",
    description: "Vendor-agnostic telemetry collection, OTLP protocols, distributed context propagation, and OpenLLMetry",
    enabled: true,
    protocol: 'rss',
    connector: 'opentelemetry_observability',
    baseUrl: 'https://opentelemetry.io/blog/rss.xml',
    authType: 'none',
    categories: ["cloud","devops"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "OpenTelemetry (CNCF)",
    region: 'Global',
    country: 'United States'
  },
  linux_foundation_global: {
    id: 'linux_foundation_global',
    name: "The Linux Foundation Collaborative Projects",
    description: "Open source stewardship, LF Energy, OpenSSF cybersecurity initiatives, PyTorch Foundation, and CNCF",
    enabled: true,
    protocol: 'rss',
    connector: 'linux_foundation_global',
    baseUrl: 'https://www.linuxfoundation.org/feed',
    authType: 'none',
    categories: ["open-source","systems","cloud"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "The Linux Foundation",
    region: 'Global',
    country: 'United States'
  },
  usenix_conferences_feed: {
    id: 'usenix_conferences_feed',
    name: "USENIX Systems Research Conferences",
    description: "OSDI, SOSP, FAST, NSDI, and USENIX Security conference presentations and peer-reviewed computer systems papers",
    enabled: true,
    protocol: 'rss',
    connector: 'usenix_conferences_feed',
    baseUrl: 'https://www.usenix.org/rss/conferences.xml',
    authType: 'none',
    categories: ["research","systems","security"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "USENIX Association",
    region: 'United States',
    country: 'United States'
  },
  usenix_login_magazine: {
    id: 'usenix_login_magazine',
    name: "USENIX ;login: Systems Research Journal",
    description: "Reflective peer-reviewed computer systems journal exploring storage architectures, operating systems, and networking",
    enabled: true,
    protocol: 'rss',
    connector: 'usenix_login_magazine',
    baseUrl: 'https://www.usenix.org/rss/login.xml',
    authType: 'none',
    categories: ["research","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "USENIX Association",
    region: 'United States',
    country: 'United States'
  },
  techcrunch_hardware_robotics: {
    id: 'techcrunch_hardware_robotics',
    name: "TechCrunch Hardware & Deep Tech Robotics",
    description: "Commercial robotics funding, humanoid manufacturing prototypes, industrial automation, and deep tech startups",
    enabled: true,
    protocol: 'rss',
    connector: 'techcrunch_hardware_robotics',
    baseUrl: 'https://techcrunch.com/category/hardware/feed/',
    authType: 'none',
    categories: ["hardware","robotics","startups"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "TechCrunch",
    region: 'United States',
    country: 'United States'
  },
  zdnet_ai_enterprise_ml: {
    id: 'zdnet_ai_enterprise_ml',
    name: "ZDNet AI & Enterprise Machine Learning",
    description: "Enterprise AI investments, IT executive roadmaps, Microsoft Copilot deployments, and generative ROI metrics",
    enabled: true,
    protocol: 'rss',
    connector: 'zdnet_ai_enterprise_ml',
    baseUrl: 'https://www.zdnet.com/topic/artificial-intelligence/rss.xml',
    authType: 'none',
    categories: ["ai","technology"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "ZDNet / Ziff Davis",
    region: 'United States',
    country: 'United States'
  },
  computerworld_enterprise_ai: {
    id: 'computerworld_enterprise_ai',
    name: "Computerworld Enterprise AI & CIO Strategy",
    description: "CIO guidance on generative AI adoption, data governance, workplace automation, and enterprise vendor comparisons",
    enabled: true,
    protocol: 'rss',
    connector: 'computerworld_enterprise_ai',
    baseUrl: 'https://www.computerworld.com/category/artificial-intelligence/index.rss',
    authType: 'none',
    categories: ["ai","technology"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Computerworld / Foundry",
    region: 'United States',
    country: 'United States'
  },
  infoworld_machine_learning_frameworks: {
    id: 'infoworld_machine_learning_frameworks',
    name: "InfoWorld Machine Learning & Analytics",
    description: "Technical reviews of open source machine learning frameworks, data pipeline tools, and model serving stacks",
    enabled: true,
    protocol: 'rss',
    connector: 'infoworld_machine_learning_frameworks',
    baseUrl: 'https://www.infoworld.com/category/machine-learning/index.rss',
    authType: 'none',
    categories: ["ai","machine-learning","programming"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "InfoWorld / Foundry",
    region: 'United States',
    country: 'United States'
  },
  linux_insider_open_source: {
    id: 'linux_insider_open_source',
    name: "LinuxInsider Open Source Enterprise Computing",
    description: "Enterprise open source software adoption, distribution reviews, containerized infrastructure, and IT strategies",
    enabled: true,
    protocol: 'rss',
    connector: 'linux_insider_open_source',
    baseUrl: 'https://www.linuxinsider.com/feed',
    authType: 'none',
    categories: ["open-source","systems"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "ECT News Network / LinuxInsider",
    region: 'United States',
    country: 'United States'
  },
  betanews_enterprise_cloud: {
    id: 'betanews_enterprise_cloud',
    name: "BetaNews Enterprise Cloud & Computing",
    description: "Enterprise technology announcements, software architecture trends, cloud security, and developer ecosystem news",
    enabled: true,
    protocol: 'rss',
    connector: 'betanews_enterprise_cloud',
    baseUrl: 'https://betanews.com/feed/',
    authType: 'none',
    categories: ["cloud","technology"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "BetaNews",
    region: 'United States',
    country: 'United States'
  },
  readwrite_ai_edge_tech: {
    id: 'readwrite_ai_edge_tech',
    name: "ReadWrite AI & Edge Computing",
    description: "Edge artificial intelligence implementations, smart sensor arrays, connected devices, and autonomous applications",
    enabled: true,
    protocol: 'rss',
    connector: 'readwrite_ai_edge_tech',
    baseUrl: 'https://readwrite.com/category/ai/feed/',
    authType: 'none',
    categories: ["ai","technology"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "ReadWrite",
    region: 'United States',
    country: 'United States'
  },
  siliconangle_thecube_ai: {
    id: 'siliconangle_thecube_ai',
    name: "SiliconANGLE theCUBE Cloud & AI Wire",
    description: "Executive video interviews and investigative coverage on hyperscaler cloud economics, datacenters, and enterprise AI",
    enabled: true,
    protocol: 'rss',
    connector: 'siliconangle_thecube_ai',
    baseUrl: 'https://siliconangle.com/category/ai/feed/',
    authType: 'none',
    categories: ["ai","cloud","startups"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "SiliconANGLE Media",
    region: 'United States',
    country: 'United States'
  },
  martech_adtech_automation: {
    id: 'martech_adtech_automation',
    name: "MarTech Algorithmic Marketing & Customer Data",
    description: "Marketing automation algorithms, customer data platforms (CDP), predictive scoring, and attribution analytics",
    enabled: true,
    protocol: 'rss',
    connector: 'martech_adtech_automation',
    baseUrl: 'https://martech.org/feed/',
    authType: 'none',
    categories: ["advertising","technology"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "MarTech / Third Door Media",
    region: 'United States',
    country: 'United States'
  },
  adweek_technology_media: {
    id: 'adweek_technology_media',
    name: "Adweek Technology & Algorithmic Advertising",
    description: "Brand technology adoption, algorithmic ad placements, media buying automation, and digital audience measurement",
    enabled: true,
    protocol: 'rss',
    connector: 'adweek_technology_media',
    baseUrl: 'https://www.adweek.com/feed/',
    authType: 'none',
    categories: ["advertising","technology"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Adweek",
    region: 'United States',
    country: 'United States'
  },
  digiday_digital_publishing: {
    id: 'digiday_digital_publishing',
    name: "Digiday Media Automation & Digital Platforms",
    description: "Media business transformations, programmatic ad yield optimization, paywall algorithms, and publishing technology",
    enabled: true,
    protocol: 'rss',
    connector: 'digiday_digital_publishing',
    baseUrl: 'https://digiday.com/feed/',
    authType: 'none',
    categories: ["advertising","technology"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Digiday Media",
    region: 'United States',
    country: 'United States'
  },
  cnet_ai_innovations_wire: {
    id: 'cnet_ai_innovations_wire',
    name: "CNET AI Innovations & Technology",
    description: "Consumer artificial intelligence innovations, wearable tech teardowns, and digital assistant evolutions",
    enabled: true,
    protocol: 'rss',
    connector: 'cnet_ai_innovations_wire',
    baseUrl: 'https://www.cnet.com/rss/news/',
    authType: 'none',
    categories: ["technology","ai"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "CNET / Red Ventures",
    region: 'United States',
    country: 'United States'
  },
  gizmodo_future_tech_culture: {
    id: 'gizmodo_future_tech_culture',
    name: "Gizmodo Future Technology & Digital Culture",
    description: "Frontier consumer technology, robotics experiments, digital copyright debates, and emerging device designs",
    enabled: true,
    protocol: 'rss',
    connector: 'gizmodo_future_tech_culture',
    baseUrl: 'https://gizmodo.com/rss',
    authType: 'none',
    categories: ["technology","ai"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Gizmodo / G/O Media",
    region: 'United States',
    country: 'United States'
  },
  mashable_tech_platforms: {
    id: 'mashable_tech_platforms',
    name: "Mashable Tech & Emerging Platforms",
    description: "Digital consumer trends, multimodal AI interfaces, social platforms, and breakthrough consumer applications",
    enabled: true,
    protocol: 'rss',
    connector: 'mashable_tech_platforms',
    baseUrl: 'https://mashable.com/feeds/rss/tech',
    authType: 'none',
    categories: ["technology","social-media"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "Mashable / Ziff Davis",
    region: 'United States',
    country: 'United States'
  },
  wired_science_physics_space: {
    id: 'wired_science_physics_space',
    name: "WIRED Science, Physics & Space Exploration",
    description: "Deep investigative science reporting on astrophysics, particle detectors, gravitational wave observatories, and spaceflight",
    enabled: true,
    protocol: 'rss',
    connector: 'wired_science_physics_space',
    baseUrl: 'https://www.wired.com/feed/category/science/latest/rss',
    authType: 'none',
    categories: ["research","technology"],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: "WIRED (Condé Nast)",
    region: 'United States',
    country: 'United States'
  },
};
