import { ExtendedSourceDef } from './extended_sources.js';

export const MORE_SOURCES: Record<string, ExtendedSourceDef> = {
  // ==========================================
  // 1. Hyperscale & Scale Engineering Blogs
  // ==========================================
  uber_engineering: {
    id: 'uber_engineering',
    name: 'Uber Engineering',
    description: 'High-scale distributed systems, Michelangelo machine learning platform, driver dispatch routing, and microservice infrastructure',
    enabled: true,
    protocol: 'rss',
    connector: 'uber_engineering',
    baseUrl: 'https://www.uber.com/blog/engineering/rss/',
    authType: 'none',
    categories: ['cloud', 'programming', 'technology', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Uber Technologies',
    region: 'Global',
    country: 'United States'
  },
  pinterest_engineering: {
    id: 'pinterest_engineering',
    name: 'Pinterest Engineering',
    description: 'Large-scale computer vision, PinSage graph neural networks, real-time visual recommendation architectures, and storage systems',
    enabled: true,
    protocol: 'rss',
    connector: 'pinterest_engineering',
    baseUrl: 'https://medium.com/feed/pinterest-engineering',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'technology', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Pinterest Inc.',
    region: 'Global',
    country: 'United States'
  },
  doordash_engineering: {
    id: 'doordash_engineering',
    name: 'DoorDash Engineering',
    description: 'Real-time logistics algorithms, dynamic delivery dispatch optimization, ML infrastructure, and distributed microservices',
    enabled: true,
    protocol: 'rss',
    connector: 'doordash_engineering',
    baseUrl: 'https://doordash.engineering/feed/',
    authType: 'none',
    categories: ['programming', 'technology', 'machine-learning', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'DoorDash Inc.',
    region: 'Global',
    country: 'United States'
  },
  lyft_engineering: {
    id: 'lyft_engineering',
    name: 'Lyft Engineering',
    description: 'Creators of Envoy proxy and Flyte ML orchestration, autonomous vehicle simulation, and geo-distributed cloud architecture',
    enabled: true,
    protocol: 'rss',
    connector: 'lyft_engineering',
    baseUrl: 'https://eng.lyft.com/feed',
    authType: 'none',
    categories: ['cloud', 'programming', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Lyft Inc.',
    region: 'Global',
    country: 'United States'
  },
  instacart_engineering: {
    id: 'instacart_engineering',
    name: 'Instacart Tech Blog',
    description: 'Deep learning for grocery catalog classification, predictive order fulfillment algorithms, and high-throughput databases',
    enabled: true,
    protocol: 'rss',
    connector: 'instacart_engineering',
    baseUrl: 'https://tech.instacart.com/feed',
    authType: 'none',
    categories: ['machine-learning', 'programming', 'cloud', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Maplebear Inc. (Instacart)',
    region: 'Global',
    country: 'United States'
  },
  linkedin_engineering: {
    id: 'linkedin_engineering',
    name: 'LinkedIn Engineering',
    description: 'Pioneers of Apache Kafka, Apache Pinot, DataHub metadata graph, and trillion-message distributed streaming pipelines',
    enabled: true,
    protocol: 'rss',
    connector: 'linkedin_engineering',
    baseUrl: 'https://engineering.linkedin.com/blog.rss.html',
    authType: 'none',
    categories: ['cloud', 'programming', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'LinkedIn Corporation',
    region: 'Global',
    country: 'United States'
  },
  paypal_engineering: {
    id: 'paypal_engineering',
    name: 'PayPal Technology',
    description: 'Real-time financial fraud detection ML, high-concurrency Node and Java microservices, and global payment compliance',
    enabled: true,
    protocol: 'rss',
    connector: 'paypal_engineering',
    baseUrl: 'https://medium.com/feed/paypal-tech',
    authType: 'none',
    categories: ['programming', 'cybersecurity', 'cloud', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'PayPal Inc.',
    region: 'Global',
    country: 'United States'
  },
  ebay_tech: {
    id: 'ebay_tech',
    name: 'eBay Tech Blog',
    description: 'Massive scale e-commerce search, distributed graph databases, real-time auctions, and open cloud infrastructure',
    enabled: true,
    protocol: 'rss',
    connector: 'ebay_tech',
    baseUrl: 'https://tech.ebayinc.com/feed/',
    authType: 'none',
    categories: ['programming', 'cloud', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'eBay Inc.',
    region: 'Global',
    country: 'United States'
  },
  etsy_codeascraft: {
    id: 'etsy_codeascraft',
    name: 'Etsy Code as Craft',
    description: 'Pioneering continuous deployment culture, resilient web architecture, real-time search indexing, and engineering craft',
    enabled: true,
    protocol: 'rss',
    connector: 'etsy_codeascraft',
    baseUrl: 'https://codeascraft.com/feed/atom/',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Etsy Inc.',
    region: 'Global',
    country: 'United States'
  },
  salesforce_engineering: {
    id: 'salesforce_engineering',
    name: 'Salesforce Engineering',
    description: 'Multi-tenant cloud architecture, Einstein AI platform, autonomous sales agents, and enterprise data mesh systems',
    enabled: true,
    protocol: 'rss',
    connector: 'salesforce_engineering',
    baseUrl: 'https://engineering.salesforce.com/feed/',
    authType: 'none',
    categories: ['cloud', 'ai', 'ai-agents', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Salesforce Inc.',
    region: 'Global',
    country: 'United States'
  },
  atlassian_developer: {
    id: 'atlassian_developer',
    name: 'Atlassian Engineering & Dev',
    description: 'Jira and Confluence cloud migrations, micro frontend architectures, platform APIs, and team developer tooling',
    enabled: true,
    protocol: 'rss',
    connector: 'atlassian_developer',
    baseUrl: 'https://developer.atlassian.com/blog/feed.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Atlassian Pty Ltd',
    region: 'Global',
    country: 'Australia'
  },
  square_corner: {
    id: 'square_corner',
    name: 'Block / Square The Corner',
    description: 'Open source mobile engineering, Cash App ledger architecture, cryptographic payments, and developer primitives',
    enabled: true,
    protocol: 'rss',
    connector: 'square_corner',
    baseUrl: 'https://developer.squareup.com/blog/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Block Inc.',
    region: 'Global',
    country: 'United States'
  },
  box_tech: {
    id: 'box_tech',
    name: 'Box Tech Blog',
    description: 'Content cloud security, enterprise vector search, large-scale Kubernetes operations, and collaboration infrastructure',
    enabled: true,
    protocol: 'rss',
    connector: 'box_tech',
    baseUrl: 'https://medium.com/feed/box-tech-blog',
    authType: 'none',
    categories: ['cloud', 'cybersecurity', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Box Inc.',
    region: 'Global',
    country: 'United States'
  },
  notion_engineering: {
    id: 'notion_engineering',
    name: 'Notion Engineering & AI',
    description: 'Block editor architectures, collaborative CRDTs, Notion AI agent integration, and database partitioning at scale',
    enabled: true,
    protocol: 'rss',
    connector: 'notion_engineering',
    baseUrl: 'https://www.notion.so/blog/topic/engineering/rss.xml',
    authType: 'none',
    categories: ['programming', 'ai', 'ai-agents', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Notion Labs Inc.',
    region: 'Global',
    country: 'United States'
  },
  linear_blog: {
    id: 'linear_blog',
    name: 'Linear Method & Engineering',
    description: 'High-performance sync engines, local-first client architecture, keyboard-driven UI, and software craft',
    enabled: true,
    protocol: 'rss',
    connector: 'linear_blog',
    baseUrl: 'https://linear.app/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'startups'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Linear Orbit Inc.',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 2. Next-Gen Distributed Data & Sync
  // ==========================================
  cockroachdb_blog: {
    id: 'cockroachdb_blog',
    name: 'CockroachDB Engineering',
    description: 'Distributed SQL architectures, Raft consensus protocols, serializable multi-region consistency, and cloud database internals',
    enabled: true,
    protocol: 'rss',
    connector: 'cockroachdb_blog',
    baseUrl: 'https://www.cockroachlabs.com/feed.xml',
    authType: 'none',
    categories: ['cloud', 'programming', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cockroach Labs',
    region: 'Global',
    country: 'United States'
  },
  yugabyte_blog: {
    id: 'yugabyte_blog',
    name: 'YugabyteDB Distributed SQL',
    description: 'PostgreSQL-compatible distributed database, hybrid multi-cloud topologies, consensus replication, and transaction processing',
    enabled: true,
    protocol: 'rss',
    connector: 'yugabyte_blog',
    baseUrl: 'https://www.yugabyte.com/feed/',
    authType: 'none',
    categories: ['cloud', 'programming', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Yugabyte Inc.',
    region: 'Global',
    country: 'United States'
  },
  tidb_pingcap: {
    id: 'tidb_pingcap',
    name: 'PingCAP TiDB & TiKV',
    description: 'Hybrid Transactional and Analytical Processing (HTAP), distributed Raft key-value storage, and open-source database scale',
    enabled: true,
    protocol: 'rss',
    connector: 'tidb_pingcap',
    baseUrl: 'https://www.pingcap.com/feed/',
    authType: 'none',
    categories: ['cloud', 'programming', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'PingCAP Inc.',
    region: 'Global',
    country: 'United States'
  },
  singlestore_blog: {
    id: 'singlestore_blog',
    name: 'SingleStore Helios',
    description: 'Unified distributed SQL engine, real-time vector search integration, lock-free skip lists, and streaming analytics',
    enabled: true,
    protocol: 'rss',
    connector: 'singlestore_blog',
    baseUrl: 'https://www.singlestore.com/blog/rss/',
    authType: 'none',
    categories: ['ai', 'cloud', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'SingleStore Inc.',
    region: 'Global',
    country: 'United States'
  },
  aerospike_blog: {
    id: 'aerospike_blog',
    name: 'Aerospike Real-Time Data',
    description: 'Sub-millisecond hybrid memory architectures, multi-terabyte flash indexes, and real-time AI feature stores',
    enabled: true,
    protocol: 'rss',
    connector: 'aerospike_blog',
    baseUrl: 'https://aerospike.com/feed/',
    authType: 'none',
    categories: ['cloud', 'ai', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Aerospike Inc.',
    region: 'Global',
    country: 'United States'
  },
  planetscale_blog: {
    id: 'planetscale_blog',
    name: 'PlanetScale Database Insights',
    description: 'MySQL horizontal sharding with Vitess, non-blocking schema migrations, connection pooling, and serverless databases',
    enabled: true,
    protocol: 'rss',
    connector: 'planetscale_blog',
    baseUrl: 'https://planetscale.com/blog/rss.xml',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'PlanetScale Inc.',
    region: 'Global',
    country: 'United States'
  },
  turso_blog: {
    id: 'turso_blog',
    name: 'Turso & libSQL Edge Database',
    description: 'Open source fork of SQLite optimized for low-latency edge deployment, vector embeddings, and embedded replicas',
    enabled: true,
    protocol: 'rss',
    connector: 'turso_blog',
    baseUrl: 'https://turso.tech/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'cloud', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ChiselStrike Inc. (Turso)',
    region: 'Global',
    country: 'United States'
  },
  electric_sql: {
    id: 'electric_sql',
    name: 'ElectricSQL Local-First Sync',
    description: 'Local-first software architecture, bidirectional Postgres-to-SQLite synchronization, CRDTs, and offline-first apps',
    enabled: true,
    protocol: 'rss',
    connector: 'electric_sql',
    baseUrl: 'https://electric-sql.com/feed.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ElectricSQL Team',
    region: 'Global',
    country: 'United Kingdom'
  },
  powersync_blog: {
    id: 'powersync_blog',
    name: 'PowerSync Sync Engine',
    description: 'Real-time database sync for mobile and web apps, offline data replication, and reactive state management',
    enabled: true,
    protocol: 'rss',
    connector: 'powersync_blog',
    baseUrl: 'https://www.powersync.com/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Journey Mobile (PowerSync)',
    region: 'Global',
    country: 'United States'
  },
  convex_blog: {
    id: 'convex_blog',
    name: 'Convex Reactive Backend',
    description: 'Full-stack TypeScript reactive database, automatic reactivity subscriptions, transactional functions, and serverless state',
    enabled: true,
    protocol: 'rss',
    connector: 'convex_blog',
    baseUrl: 'https://www.convex.dev/feed.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Convex Inc.',
    region: 'Global',
    country: 'United States'
  },
  upstash_blog: {
    id: 'upstash_blog',
    name: 'Upstash Serverless Data',
    description: 'Serverless Redis, Kafka, and Vector database built for edge functions, serverless APIs, and per-request pricing',
    enabled: true,
    protocol: 'rss',
    connector: 'upstash_blog',
    baseUrl: 'https://upstash.com/blog/rss.xml',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Upstash Inc.',
    region: 'Global',
    country: 'United States'
  },
  confluent_blog: {
    id: 'confluent_blog',
    name: 'Confluent Streaming & Kafka',
    description: 'Event-driven architectures, Apache Flink stream processing, Kafka Connect ecosystems, and real-time enterprise pipelines',
    enabled: true,
    protocol: 'rss',
    connector: 'confluent_blog',
    baseUrl: 'https://www.confluent.io/feed/',
    authType: 'none',
    categories: ['cloud', 'programming', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Confluent Inc.',
    region: 'Global',
    country: 'United States'
  },
  temporal_blog: {
    id: 'temporal_blog',
    name: 'Temporal Workflow Engine',
    description: 'Durable execution systems, fault-tolerant stateful workflows, microservice orchestration, and reliable software design',
    enabled: true,
    protocol: 'rss',
    connector: 'temporal_blog',
    baseUrl: 'https://temporal.io/feed.xml',
    authType: 'none',
    categories: ['developer-tools', 'cloud', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Temporal Technologies Inc.',
    region: 'Global',
    country: 'United States'
  },
  inngest_blog: {
    id: 'inngest_blog',
    name: 'Inngest Event Orchestration',
    description: 'Event-driven serverless background queues, AI step functions, durable flow control, and rate limiting architectures',
    enabled: true,
    protocol: 'rss',
    connector: 'inngest_blog',
    baseUrl: 'https://www.inngest.com/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'cloud', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Inngest Inc.',
    region: 'Global',
    country: 'United States'
  },
  dagger_blog: {
    id: 'dagger_blog',
    name: 'Dagger CI/CD Engine',
    description: 'Programmable CI/CD engine running pipelines in isolated containers, GraphQL execution graphs, and portable automation',
    enabled: true,
    protocol: 'rss',
    connector: 'dagger_blog',
    baseUrl: 'https://dagger.io/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'cloud', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Dagger Inc. (Solomon Hykes)',
    region: 'Global',
    country: 'United States'
  },
  render_blog: {
    id: 'render_blog',
    name: 'Render Cloud Infrastructure',
    description: 'Modern developer cloud hosting, automated zero-downtime deploys, private services, and managed PostgreSQL scale',
    enabled: true,
    protocol: 'rss',
    connector: 'render_blog',
    baseUrl: 'https://render.com/blog/rss.xml',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'startups'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Render Services Inc.',
    region: 'Global',
    country: 'United States'
  },
  railway_blog: {
    id: 'railway_blog',
    name: 'Railway Cloud Platform',
    description: 'Instant infrastructure provisioning, ephemeral environments, containerized service meshes, and developer ergonomics',
    enabled: true,
    protocol: 'rss',
    connector: 'railway_blog',
    baseUrl: 'https://blog.railway.com/rss.xml',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'startups'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Railway Corp.',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 3. Frontier Robotics & Physical AI
  // ==========================================
  boston_dynamics_news: {
    id: 'boston_dynamics_news',
    name: 'Boston Dynamics Robotics',
    description: 'Electric Atlas humanoid advancements, Spot industrial autonomy, dynamic kinematic control, and warehouse automation',
    enabled: true,
    protocol: 'rss',
    connector: 'boston_dynamics_news',
    baseUrl: 'https://bostondynamics.com/feed/',
    authType: 'none',
    categories: ['robotics', 'ai', 'technology', 'ai-hardware'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Boston Dynamics (Hyundai)',
    region: 'Global',
    country: 'United States'
  },
  figure_ai_blog: {
    id: 'figure_ai_blog',
    name: 'Figure Humanoid AI',
    description: 'General-purpose humanoid robots (Figure 01, Figure 02), neural end-to-end visuomotor policies, and manufacturing automation',
    enabled: true,
    protocol: 'rss',
    connector: 'figure_ai_blog',
    baseUrl: 'https://www.figure.ai/feed',
    authType: 'none',
    categories: ['robotics', 'ai', 'ai-hardware', 'startups'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Figure AI Inc.',
    region: 'Global',
    country: 'United States'
  },
  sanctuary_ai_blog: {
    id: 'sanctuary_ai_blog',
    name: 'Sanctuary AI & Carbon',
    description: 'Phoenix general-purpose humanoid robots powered by Carbon, human-like dexterity, teleoperation, and cognitive software',
    enabled: true,
    protocol: 'rss',
    connector: 'sanctuary_ai_blog',
    baseUrl: 'https://www.sanctuary.ai/feed/',
    authType: 'none',
    categories: ['robotics', 'ai', 'ai-hardware'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Sanctuary Cognitive Systems Corp.',
    region: 'Global',
    country: 'Canada'
  },
  unitree_robotics: {
    id: 'unitree_robotics',
    name: 'Unitree Robotics',
    description: 'High-agility quadruped robots (Go2, B2) and mass-manufactured humanoid robots (H1, G1) dynamic motor controllers',
    enabled: true,
    protocol: 'rss',
    connector: 'unitree_robotics',
    baseUrl: 'https://www.unitree.com/feed/',
    authType: 'none',
    categories: ['robotics', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Unitree Robotics (Hangzhou Yushu Tech)',
    region: 'Asia-Pacific',
    country: 'China'
  },
  covariant_ai: {
    id: 'covariant_ai',
    name: 'Covariant AI Robotics',
    description: 'Universal AI platform (Covariant Brain) for autonomous physical manipulation, sorting, and robotic pick-and-place',
    enabled: true,
    protocol: 'rss',
    connector: 'covariant_ai',
    baseUrl: 'https://covariant.ai/feed/',
    authType: 'none',
    categories: ['robotics', 'ai', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Covariant AI (Peter Chen & Pieter Abbeel)',
    region: 'Global',
    country: 'United States'
  },
  skild_ai: {
    id: 'skild_ai',
    name: 'Skild AI Physical Intelligence',
    description: 'Scalable foundation models for diverse robotic bodies, dexterous manipulation, navigation, and physical autonomy',
    enabled: true,
    protocol: 'rss',
    connector: 'skild_ai',
    baseUrl: 'https://www.skild.ai/feed',
    authType: 'none',
    categories: ['robotics', 'ai', 'models', 'startups'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Skild AI Inc.',
    region: 'Global',
    country: 'United States'
  },
  physical_intelligence: {
    id: 'physical_intelligence',
    name: 'Physical Intelligence (Pi)',
    description: 'Bringing general-purpose AI to the physical world, pi-zero foundation models, and multi-task robotic mastery',
    enabled: true,
    protocol: 'rss',
    connector: 'physical_intelligence',
    baseUrl: 'https://www.physicalintelligence.company/feed.xml',
    authType: 'none',
    categories: ['robotics', 'ai', 'models', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Physical Intelligence Inc.',
    region: 'Global',
    country: 'United States'
  },
  agility_robotics: {
    id: 'agility_robotics',
    name: 'Agility Robotics (Digit)',
    description: 'Digit bipedal humanoid robots engineered for bulk material handling, logistics logistics facilities, and safety fleets',
    enabled: true,
    protocol: 'rss',
    connector: 'agility_robotics',
    baseUrl: 'https://agilityrobotics.com/feed',
    authType: 'none',
    categories: ['robotics', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Agility Robotics Inc.',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 4. Frontier AI Labs & Open Science
  // ==========================================
  cohere_for_ai: {
    id: 'cohere_for_ai',
    name: 'Cohere For AI Research',
    description: 'Open scientific research lab exploring multilingual foundation models (Aya), safety evaluations, and representation learning',
    enabled: true,
    protocol: 'rss',
    connector: 'cohere_for_ai',
    baseUrl: 'https://cohere.com/blog/rss',
    authType: 'none',
    categories: ['ai', 'research', 'models', 'llms'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cohere For AI (Sara Hooker)',
    region: 'Global',
    country: 'Canada'
  },
  adept_ai: {
    id: 'adept_ai',
    name: 'Adept AI & Action Transformers',
    description: 'Autonomous computer-use models (ACT-1), generalist software agents, and multimodal digital workflow automation',
    enabled: true,
    protocol: 'rss',
    connector: 'adept_ai',
    baseUrl: 'https://www.adept.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'ai-agents', 'models'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Adept AI Labs Inc.',
    region: 'Global',
    country: 'United States'
  },
  writer_ai: {
    id: 'writer_ai',
    name: 'Writer AI & Palmyra Models',
    description: 'Enterprise generative AI platform, Palmyra open-weights foundation models, graph-based RAG, and synthetic data',
    enabled: true,
    protocol: 'rss',
    connector: 'writer_ai',
    baseUrl: 'https://writer.com/blog/feed/',
    authType: 'none',
    categories: ['ai', 'models', 'llms', 'enterprise'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Writer Inc. (May Habib)',
    region: 'Global',
    country: 'United States'
  },
  eleuther_ai_blog: {
    id: 'eleuther_ai_blog',
    name: 'EleutherAI Non-Profit Research',
    description: 'Open-source frontier models (GPT-NeoX, Pythia), mechanistic interpretability research, and community evaluation benchmarks',
    enabled: true,
    protocol: 'rss',
    connector: 'eleuther_ai_blog',
    baseUrl: 'https://www.eleuther.ai/feed.xml',
    authType: 'none',
    categories: ['ai', 'research', 'open-source-ai', 'llms'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'EleutherAI Institute',
    region: 'Global',
    country: 'United States'
  },
  allen_institute_ai: {
    id: 'allen_institute_ai',
    name: 'Allen Institute for AI (Ai2)',
    description: 'Paul G. Allen non-profit research institute creating truly open science language models (OLMo), Tülu, and AI evaluation',
    enabled: true,
    protocol: 'rss',
    connector: 'allen_institute_ai',
    baseUrl: 'https://blog.allenai.org/feed',
    authType: 'none',
    categories: ['ai', 'research', 'open-source-ai', 'models'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Allen Institute for AI',
    region: 'Global',
    country: 'United States'
  },
  cmu_ai_blog: {
    id: 'cmu_ai_blog',
    name: 'Carnegie Mellon AI & Robotics',
    description: 'CMU School of Computer Science breakthroughs in neural theorem proving, autonomous driving, NLP, and reinforcement learning',
    enabled: true,
    protocol: 'rss',
    connector: 'cmu_ai_blog',
    baseUrl: 'https://www.cs.cmu.edu/news/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'robotics', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Carnegie Mellon University',
    region: 'Global',
    country: 'United States'
  },
  oxford_ai_lab: {
    id: 'oxford_ai_lab',
    name: 'Oxford Applied AI & Machine Learning',
    description: 'University of Oxford Department of Computer Science research on Bayesian deep learning, ethics, and multi-agent coordination',
    enabled: true,
    protocol: 'rss',
    connector: 'oxford_ai_lab',
    baseUrl: 'https://www.cs.ox.ac.uk/news/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'ethics', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'University of Oxford',
    region: 'Global',
    country: 'United Kingdom'
  },
  cambridge_ai: {
    id: 'cambridge_ai',
    name: 'Cambridge Computer Laboratory',
    description: 'University of Cambridge research in trustworthy machine learning, secure architectures, compilers, and biological computing',
    enabled: true,
    protocol: 'rss',
    connector: 'cambridge_ai',
    baseUrl: 'https://www.cst.cam.ac.uk/news/rss',
    authType: 'none',
    categories: ['research', 'ai', 'technology', 'cybersecurity'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'University of Cambridge',
    region: 'Global',
    country: 'United Kingdom'
  },
  mila_quebec_ai: {
    id: 'mila_quebec_ai',
    name: 'Mila Quebec AI Institute',
    description: 'World-leading deep learning institute founded by Yoshua Bengio, AI for climate, drug discovery, and foundational theory',
    enabled: true,
    protocol: 'rss',
    connector: 'mila_quebec_ai',
    baseUrl: 'https://mila.quebec/en/feed',
    authType: 'none',
    categories: ['research', 'ai', 'machine-learning', 'ethics'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Mila (Quebec Artificial Intelligence Institute)',
    region: 'Global',
    country: 'Canada'
  },
  vector_institute: {
    id: 'vector_institute',
    name: 'Vector Institute for AI',
    description: 'Premier Canadian research institute for artificial intelligence in Toronto, deep learning foundations, and health AI',
    enabled: true,
    protocol: 'rss',
    connector: 'vector_institute',
    baseUrl: 'https://vectorinstitute.ai/feed/',
    authType: 'none',
    categories: ['research', 'ai', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Vector Institute',
    region: 'Global',
    country: 'Canada'
  },

  // ==========================================
  // 5. Silicon, Fabs & Hardware Architecture
  // ==========================================
  tsmc_news: {
    id: 'tsmc_news',
    name: 'TSMC Semiconductor & Fab News',
    description: 'World foundry leader updates on 2nm nanosheet GAA transistors, CoWoS 2.5D/3D advanced packaging, and A16 fabrication nodes',
    enabled: true,
    protocol: 'rss',
    connector: 'tsmc_news',
    baseUrl: 'https://pr.tsmc.com/english/rss/news.xml',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Taiwan Semiconductor Manufacturing Co.',
    region: 'Asia-Pacific',
    country: 'Taiwan'
  },
  asml_insights: {
    id: 'asml_insights',
    name: 'ASML EUV Lithography & Optics',
    description: 'Extreme Ultraviolet (EUV) lithography systems, High-NA 0.55 optics breakthroughs, and sub-nanometer semiconductor physics',
    enabled: true,
    protocol: 'rss',
    connector: 'asml_insights',
    baseUrl: 'https://www.asml.com/en/news/press-releases?format=rss',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ASML Holding N.V.',
    region: 'Europe',
    country: 'Netherlands'
  },
  arm_community: {
    id: 'arm_community',
    name: 'Arm Architecture & Community',
    description: 'Armv9 instruction set specifications, Neoverse cloud server cores, KleidiAI micro-kernels, and mobile silicon efficiency',
    enabled: true,
    protocol: 'rss',
    connector: 'arm_community',
    baseUrl: 'https://community.arm.com/cfs-filesystemfile/__key/communityserver-components-securewidgets-rss/00-00-00-00-14/rss.xml',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Arm Limited',
    region: 'Global',
    country: 'United Kingdom'
  },
  riscv_international: {
    id: 'riscv_international',
    name: 'RISC-V International',
    description: 'Open standard Instruction Set Architecture (ISA) developments, vector processing extensions, and open silicon ecosystems',
    enabled: true,
    protocol: 'rss',
    connector: 'riscv_international',
    baseUrl: 'https://riscv.org/feed/',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'RISC-V International',
    region: 'Global',
    country: 'Switzerland'
  },
  qualcomm_developer: {
    id: 'qualcomm_developer',
    name: 'Qualcomm Snapdragon & On-Device AI',
    description: 'Snapdragon X Elite Oryon CPU architectures, Hexagon NPU edge acceleration, and on-device multimodal model inference',
    enabled: true,
    protocol: 'rss',
    connector: 'qualcomm_developer',
    baseUrl: 'https://www.qualcomm.com/developer/blog/rss',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Qualcomm Technologies Inc.',
    region: 'Global',
    country: 'United States'
  },
  intel_newsroom: {
    id: 'intel_newsroom',
    name: 'Intel Technology News',
    description: 'Intel 18A foundry nodes, PowerVia backside power delivery, Gaudi AI accelerators, and Lunar Lake x86 architectures',
    enabled: true,
    protocol: 'rss',
    connector: 'intel_newsroom',
    baseUrl: 'https://newsroom.intel.com/feed/',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Intel Corporation',
    region: 'Global',
    country: 'United States'
  },
  amd_community_blog: {
    id: 'amd_community_blog',
    name: 'AMD Community & ROCm Ecosystem',
    description: 'Instinct MI300X GPU accelerators, ROCm open-source GPU software stack, Zen 5 CPU microarchitecture, and EPYC datacenters',
    enabled: true,
    protocol: 'rss',
    connector: 'amd_community_blog',
    baseUrl: 'https://community.amd.com/t5/custom/page/page-id/rss?page=1',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Advanced Micro Devices (AMD)',
    region: 'Global',
    country: 'United States'
  },
  synopsys_blog: {
    id: 'synopsys_blog',
    name: 'Synopsys Electronic Design & Silicon',
    description: 'Electronic Design Automation (EDA), AI-driven chip placement synthesis (DSO.ai), silicon IP, and semiconductor verification',
    enabled: true,
    protocol: 'rss',
    connector: 'synopsys_blog',
    baseUrl: 'https://blogs.synopsys.com/feed/',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Synopsys Inc.',
    region: 'Global',
    country: 'United States'
  },
  cadence_design: {
    id: 'cadence_design',
    name: 'Cadence Design Systems',
    description: 'Computational software for silicon design, 3D-IC chiplet packaging simulation, palladium emulation, and physical verification',
    enabled: true,
    protocol: 'rss',
    connector: 'cadence_design',
    baseUrl: 'https://community.cadence.com/cadence_blogs_8/b/rss',
    authType: 'none',
    categories: ['semiconductors', 'ai-hardware', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cadence Design Systems Inc.',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 6. Threat Intel & Offensive/Defensive Cyber
  // ==========================================
  hackerone_blog: {
    id: 'hackerone_blog',
    name: 'HackerOne Vulnerability Insights',
    description: 'Crowdsourced ethical hacking research, attack surface vulnerability trends, AI safety bug bounties, and defense playbooks',
    enabled: true,
    protocol: 'rss',
    connector: 'hackerone_blog',
    baseUrl: 'https://www.hackerone.com/blog.xml',
    authType: 'none',
    categories: ['cybersecurity', 'technology', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'HackerOne Inc.',
    region: 'Global',
    country: 'United States'
  },
  bugcrowd_research: {
    id: 'bugcrowd_research',
    name: 'Bugcrowd Cyber Research',
    description: 'Penetration testing telemetry, novel attack vectors, crowdsourced red teaming, and vulnerability disclosure reports',
    enabled: true,
    protocol: 'rss',
    connector: 'bugcrowd_research',
    baseUrl: 'https://www.bugcrowd.com/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Bugcrowd Inc.',
    region: 'Global',
    country: 'United States'
  },
  crowdstrike_blog: {
    id: 'crowdstrike_blog',
    name: 'CrowdStrike Falcon OverWatch',
    description: 'Frontline adversary threat intelligence, nation-state intrusion tactics, identity-based attacks, and cloud defense telemetry',
    enabled: true,
    protocol: 'rss',
    connector: 'crowdstrike_blog',
    baseUrl: 'https://www.crowdstrike.com/blog/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'cloud', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'CrowdStrike Holdings Inc.',
    region: 'Global',
    country: 'United States'
  },
  trendmicro_research: {
    id: 'trendmicro_research',
    name: 'Trend Micro & Zero Day Initiative',
    description: 'World-renowned Zero Day Initiative (ZDI) disclosures, advanced persistent threat (APT) dissections, and reverse engineering',
    enabled: true,
    protocol: 'rss',
    connector: 'trendmicro_research',
    baseUrl: 'https://www.trendmicro.com/vinfo/us/security/rss',
    authType: 'none',
    categories: ['cybersecurity', 'technology', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Trend Micro & ZDI',
    region: 'Global',
    country: 'Japan'
  },
  checkpoint_research: {
    id: 'checkpoint_research',
    name: 'Check Point Threat Research (CPR)',
    description: 'Cyber warfare group analyses, zero-day exploit discovery, firmware reverse-engineering, and cryptographic flaw analyses',
    enabled: true,
    protocol: 'rss',
    connector: 'checkpoint_research',
    baseUrl: 'https://research.checkpoint.com/feed/',
    authType: 'none',
    categories: ['cybersecurity', 'technology', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Check Point Software Technologies',
    region: 'Global',
    country: 'Israel'
  },
  talos_intelligence: {
    id: 'talos_intelligence',
    name: 'Cisco Talos Threat Intelligence',
    description: 'One of the world largest private threat intelligence teams, Snort engine rule sets, telemetry, and exploit teardowns',
    enabled: true,
    protocol: 'rss',
    connector: 'talos_intelligence',
    baseUrl: 'https://blog.talosintelligence.com/rss/',
    authType: 'none',
    categories: ['cybersecurity', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cisco Systems Inc.',
    region: 'Global',
    country: 'United States'
  },

  // ==========================================
  // 7. Compilers, Languages & Frameworks
  // ==========================================
  swift_org_blog: {
    id: 'swift_org_blog',
    name: 'Swift.org Official Blog',
    description: 'Swift programming language evolution, Embedded Swift on bare metal microcontrollers, actor concurrency, and compiler internals',
    enabled: true,
    protocol: 'rss',
    connector: 'swift_org_blog',
    baseUrl: 'https://www.swift.org/atom.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Swift Open Source Project',
    region: 'Global',
    country: 'United States'
  },
  scala_lang_blog: {
    id: 'scala_lang_blog',
    name: 'Scala Language News',
    description: 'Scala 3 compiler advances (Dotty), functional programming paradigms, type-level systems, and distributed Akka/Pekko runtimes',
    enabled: true,
    protocol: 'rss',
    connector: 'scala_lang_blog',
    baseUrl: 'https://scala-lang.org/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Scala Center (EPFL)',
    region: 'Global',
    country: 'Switzerland'
  },
  astral_uv_ruff: {
    id: 'astral_uv_ruff',
    name: 'Astral (Ruff & uv Python)',
    description: 'Next-generation Python tooling written in Rust: uv blazingly fast package manager, Ruff linter, and modern Python workflows',
    enabled: true,
    protocol: 'rss',
    connector: 'astral_uv_ruff',
    baseUrl: 'https://astral.sh/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'startups'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Astral Software Inc. (Charlie Marsh)',
    region: 'Global',
    country: 'United States'
  },
  pydantic_blog: {
    id: 'pydantic_blog',
    name: 'Pydantic & Logfire',
    description: 'Rust-accelerated Python type parsing, Pydantic Core, and Logfire observability platform for LLM applications',
    enabled: true,
    protocol: 'rss',
    connector: 'pydantic_blog',
    baseUrl: 'https://pydantic.dev/articles/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Pydantic Inc. (Samuel Colvin)',
    region: 'Global',
    country: 'United Kingdom'
  },
  turborepo_blog: {
    id: 'turborepo_blog',
    name: 'Turborepo & Turbo Engine',
    description: 'High-speed monorepo build systems, Rust caching pipelines, task dependency graphs, and developer infrastructure',
    enabled: true,
    protocol: 'rss',
    connector: 'turborepo_blog',
    baseUrl: 'https://turbo.build/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Vercel Inc. (Turborepo)',
    region: 'Global',
    country: 'United States'
  },
  astro_build_blog: {
    id: 'astro_build_blog',
    name: 'Astro Web Framework',
    description: 'Zero-JS by default web architecture, component islands, content collections, and modern server-side rendering',
    enabled: true,
    protocol: 'rss',
    connector: 'astro_build_blog',
    baseUrl: 'https://astro.build/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Astro Technology Co.',
    region: 'Global',
    country: 'United States'
  },
  solidjs_blog: {
    id: 'solidjs_blog',
    name: 'SolidJS & Signals Reactive UI',
    description: 'Fine-grained reactivity primitives, zero-virtual-DOM compilation, SolidStart full-stack routing, and web performance',
    enabled: true,
    protocol: 'rss',
    connector: 'solidjs_blog',
    baseUrl: 'https://www.solidjs.com/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Ryan Carniato & SolidJS Community',
    region: 'Global',
    country: 'United States'
  },
  nim_lang_blog: {
    id: 'nim_lang_blog',
    name: 'Nim Systems Language',
    description: 'Statically typed compiled systems programming language with Python-like syntax, C/C++ transpilation, and macro metaprogramming',
    enabled: true,
    protocol: 'rss',
    connector: 'nim_lang_blog',
    baseUrl: 'https://nim-lang.org/blog.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Nim Programming Language Team',
    region: 'Global',
    country: 'Germany'
  },
  crystal_lang_news: {
    id: 'crystal_lang_news',
    name: 'Crystal Programming Language',
    description: 'Ruby-like syntax with C-like performance, static type inference, LLVM-backed compilation, and fibers concurrency',
    enabled: true,
    protocol: 'rss',
    connector: 'crystal_lang_news',
    baseUrl: 'https://crystal-lang.org/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Manas Technology Solutions (Crystal)',
    region: 'Global',
    country: 'Argentina'
  },
  gleam_lang_news: {
    id: 'gleam_lang_news',
    name: 'Gleam Language & BEAM',
    description: 'Fast, friendly, and type-safe language that runs on the Erlang BEAM runtime and compiles to JavaScript for full-stack type safety',
    enabled: true,
    protocol: 'rss',
    connector: 'gleam_lang_news',
    baseUrl: 'https://gleam.run/news/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Louis Pilfold & Gleam Community',
    region: 'Global',
    country: 'United Kingdom'
  },
  mojo_modular: {
    id: 'mojo_modular',
    name: 'Modular Mojo & MAX Engine',
    description: 'Mojo programming language designed for AI accelerators, combining Python syntax with C++ performance and hardware SIMD control',
    enabled: true,
    protocol: 'rss',
    connector: 'mojo_modular',
    baseUrl: 'https://www.modular.com/blog/rss.xml',
    authType: 'none',
    categories: ['programming', 'ai', 'ai-hardware', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Modular AI (Chris Lattner)',
    region: 'Global',
    country: 'United States'
  },
  pytorch_foundation: {
    id: 'pytorch_foundation',
    name: 'PyTorch Foundation',
    description: 'Linux Foundation open source project for deep learning, TorchDynamo compilation, distributed training (FSDP), and ecosystem updates',
    enabled: true,
    protocol: 'rss',
    connector: 'pytorch_foundation',
    baseUrl: 'https://pytorch.org/feed.xml',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'open-source-ai', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Linux Foundation (PyTorch)',
    region: 'Global',
    country: 'United States'
  },
  triton_openai: {
    id: 'triton_openai',
    name: 'OpenAI Triton GPU Compiler',
    description: 'Open-source Python-like programming language and compiler for writing highly optimized custom Deep Learning GPU kernels without CUDA',
    enabled: true,
    protocol: 'rss',
    connector: 'triton_openai',
    baseUrl: 'https://triton-lang.org/main/feed.xml',
    authType: 'none',
    categories: ['ai', 'ai-hardware', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'OpenAI Triton Project (Philippe Tillet)',
    region: 'Global',
    country: 'United States'
  },
  candle_rust: {
    id: 'candle_rust',
    name: 'Hugging Face Candle (Rust ML)',
    description: 'Minimalist ML framework for Rust with focus on performance (including GPU support) and ease of use, running models in WASM and edge',
    enabled: true,
    protocol: 'rss',
    connector: 'candle_rust',
    baseUrl: 'https://huggingface.co/blog/feed.xml',
    authType: 'none',
    categories: ['open-source-ai', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Hugging Face Open Source',
    region: 'Global',
    country: 'United States'
  },
  burn_rust: {
    id: 'burn_rust',
    name: 'Burn Deep Learning (Rust)',
    description: 'Comprehensive, flexible and blazingly fast deep learning framework in Rust with multi-backend execution (WGPU, LibTorch, Candle)',
    enabled: true,
    protocol: 'rss',
    connector: 'burn_rust',
    baseUrl: 'https://burn.dev/feed.xml',
    authType: 'none',
    categories: ['open-source-ai', 'programming', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Tracel AI (Burn Framework)',
    region: 'Global',
    country: 'Canada'
  },

  // ==========================================
  // 8. Visual Educators, Creators & Visionaries
  // ==========================================
  youtube_andrej_karpathy: {
    id: 'youtube_andrej_karpathy',
    name: 'Andrej Karpathy (Neural Networks & AI)',
    description: 'Masterclass tutorials building GPT from scratch, micrograd autograd engine, LLM tokenization, and deep learning intuitions',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_andrej_karpathy',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCXUPKJO4M-m_5rPspOsnkAg',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'video', 'research'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Andrej Karpathy',
    region: 'Global',
    country: 'United States'
  },
  youtube_yannic_kilcher: {
    id: 'youtube_yannic_kilcher',
    name: 'Yannic Kilcher (AI Paper Teardowns)',
    description: 'Rigorous step-by-step reading and visual breakdown of landmark artificial intelligence, LLM, and computer vision papers',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_yannic_kilcher',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew',
    authType: 'none',
    categories: ['ai', 'research', 'video', 'machine-learning'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Yannic Kilcher',
    region: 'Global',
    country: 'Switzerland'
  },
  youtube_primeagen: {
    id: 'youtube_primeagen',
    name: 'The Primeagen (Systems & Software Craft)',
    description: 'High-energy explorations of low-level systems programming, algorithms, Neovim, developer workflows, and architecture debates',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_primeagen',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC8ENHE5xdFSwx71u3fDH5Xw',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'video'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'The Primeagen (Michael Paulson)',
    region: 'Global',
    country: 'United States'
  },
  youtube_networkchuck: {
    id: 'youtube_networkchuck',
    name: 'NetworkChuck (Networking & Cyber)',
    description: 'Practical networking protocols, TCP/IP, Linux administration, cybersecurity attacks, homelab servers, and cloud security',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_networkchuck',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9x0AN7BWHpCDHSm9NiJFJQ',
    authType: 'none',
    categories: ['cybersecurity', 'cloud', 'video', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'NetworkChuck (Chuck Keith)',
    region: 'Global',
    country: 'United States'
  },
  youtube_neetcode: {
    id: 'youtube_neetcode',
    name: 'NeetCode (Algorithms & System Design)',
    description: 'Algorithm visualizations, data structure fundamentals, dynamic programming, and scalable distributed system design',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_neetcode',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC_mYaQAE6-71MREQHxEvBRg',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'video'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'NeetCode (Navdeep Singh)',
    region: 'Global',
    country: 'United States'
  },
  youtube_hussein_nasser: {
    id: 'youtube_hussein_nasser',
    name: 'Hussein Nasser (Backend Engineering)',
    description: 'Deep dives into database indexing, proxy protocols (HTTP/2, QUIC, gRPC), connection pools, and backend operating systems',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_hussein_nasser',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC_ML5xP23TOWKUcc-oAE_EQ',
    authType: 'none',
    categories: ['programming', 'cloud', 'video', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Hussein Nasser',
    region: 'Global',
    country: 'United States'
  },
  youtube_george_hotz: {
    id: 'youtube_george_hotz',
    name: 'George Hotz / tiny corp (tinygrad)',
    description: 'Raw deep learning framework engineering from scratch, hardware accelerators, driver reverse-engineering, and robotics software',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_george_hotz',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCwgKmJM4ZJQRJ-U5NjvR2dg',
    authType: 'none',
    categories: ['ai', 'ai-hardware', 'programming', 'video'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'George Hotz (tiny corp / comma.ai)',
    region: 'Global',
    country: 'United States'
  },
  youtube_jeff_heaton: {
    id: 'youtube_jeff_heaton',
    name: 'Jeff Heaton (Deep Learning & PyTorch)',
    description: 'Washington University professor explaining neural architectures, computer vision, tabular modeling, and PyTorch applications',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_jeff_heaton',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCR1-GEpyOPzT2AO4D_eAECg',
    authType: 'none',
    categories: ['ai', 'machine-learning', 'video', 'research'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Jeff Heaton',
    region: 'Global',
    country: 'United States'
  },
  youtube_low_level_learning: {
    id: 'youtube_low_level_learning',
    name: 'Low Level Learning (C, ASM & Reverse Eng)',
    description: 'Demystifying low-level computer science, x86 and ARM assembly, C memory exploitation, hardware peripherals, and compilers',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_low_level_learning',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC6qj_cfNiv4KgVQHZrCXnWg',
    authType: 'none',
    categories: ['programming', 'cybersecurity', 'video'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Low Level Learning',
    region: 'Global',
    country: 'United States'
  },
  youtube_jon_gjengset: {
    id: 'youtube_jon_gjengset',
    name: 'Jon Gjengset (Crust of Rust)',
    description: 'Deep, multi-hour technical dives into Rust programming language internals, lock-free concurrency, asynchronous runtimes, and unsafe code',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_jon_gjengset',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC_iD0xZCrxwGW6vNgLDt5CQ',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'video'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Jon Gjengset',
    region: 'Global',
    country: 'Norway'
  },
  youtube_anthonygg: {
    id: 'youtube_anthonygg',
    name: 'Anthony GG (Go Distributed Systems)',
    description: 'Building production-grade microservices, distributed crypto exchanges, custom HTTP routers, and protocol buffers in Golang',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_anthonygg',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCnUYZluO0XbC6V5N44t5i9w',
    authType: 'none',
    categories: ['programming', 'cloud', 'video'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Anthony GG',
    region: 'Global',
    country: 'Netherlands'
  },
  youtube_arjan_codes: {
    id: 'youtube_arjan_codes',
    name: 'ArjanCodes (Software Architecture & Python)',
    description: 'Clean code principles, dependency injection, object-oriented design patterns, functional programming, and software refactoring',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_arjan_codes',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCVhQ2NnY5Rskt6UjCUkJ_DA',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'video'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ArjanCodes (Arjan Egges)',
    region: 'Global',
    country: 'Netherlands'
  },

  // ==========================================
  // 9. Computing Foundations & Publications
  // ==========================================
  acm_queue: {
    id: 'acm_queue',
    name: 'ACM Queue Architecture Magazine',
    description: 'Peer-reviewed practical computer science perspectives from the Association for Computing Machinery on systems, scale, and software',
    enabled: true,
    protocol: 'rss',
    connector: 'acm_queue',
    baseUrl: 'https://queue.acm.org/rss/feeds/queuecontent.xml',
    authType: 'none',
    categories: ['research', 'technology', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Association for Computing Machinery (ACM)',
    region: 'Global',
    country: 'United States'
  },
  dzone_dev: {
    id: 'dzone_dev',
    name: 'DZone Architecture & Cloud',
    description: 'Practitioner technical guides on microservices, cloud orchestration, container runtimes, database indexing, and DevOps',
    enabled: true,
    protocol: 'rss',
    connector: 'dzone_dev',
    baseUrl: 'https://feeds.dzone.com/home',
    authType: 'none',
    categories: ['cloud', 'programming', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'DZone Media',
    region: 'Global',
    country: 'United States'
  },
  scientific_american_tech: {
    id: 'scientific_american_tech',
    name: 'Scientific American Computing & Physics',
    description: 'Authoritative coverage of quantum computing, neuro-computational science, synthetic biology, and foundational physics',
    enabled: true,
    protocol: 'rss',
    connector: 'scientific_american_tech',
    baseUrl: 'https://www.scientificamerican.com/feed/rss/technology',
    authType: 'none',
    categories: ['research', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Springer Nature (Scientific American)',
    region: 'Global',
    country: 'United States'
  },
  spectrum_ieee_computing: {
    id: 'spectrum_ieee_computing',
    name: 'IEEE Computer Society Computing',
    description: 'Breakthroughs in supercomputing, high-performance distributed systems, fault-tolerant networks, and optical computing',
    enabled: true,
    protocol: 'rss',
    connector: 'spectrum_ieee_computing',
    baseUrl: 'https://spectrum.ieee.org/feeds/topic/computing.rss',
    authType: 'none',
    categories: ['research', 'technology', 'semiconductors'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'IEEE Computer Society',
    region: 'Global',
    country: 'United States'
  }
};
