import { SourceDefinition } from '../../types.js';

export const ULTRA_SOURCES: Record<string, SourceDefinition> = {
  // === 1. AI SAFETY, ALIGNMENT & GOVERNANCE ===
  alignment_forum: {
    id: 'alignment_forum',
    name: 'AI Alignment Forum',
    description: 'Technical research, alignment methodologies, mechanistic interpretability, and AI safety discussions',
    enabled: true,
    protocol: 'rss',
    connector: 'alignment_forum',
    baseUrl: 'https://www.alignmentforum.org/feed.xml',
    authType: 'none',
    categories: ['ai-safety', 'research', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'AI Alignment Forum',
    region: 'Global',
    country: 'United States'
  },
  future_of_life: {
    id: 'future_of_life',
    name: 'Future of Life Institute (FLI)',
    description: 'Steering transformative technologies and AI away from extreme risks and toward benefiting life',
    enabled: true,
    protocol: 'rss',
    connector: 'future_of_life',
    baseUrl: 'https://futureoflife.org/feed/',
    authType: 'none',
    categories: ['ai-safety', 'policy', 'ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Future of Life Institute',
    region: 'Global',
    country: 'United States'
  },
  cais_safety: {
    id: 'cais_safety',
    name: 'Center for AI Safety (CAIS)',
    description: 'Frontier research in empirical AI safety, catastrophic risk reduction, and AI evaluation benchmarks',
    enabled: true,
    protocol: 'rss',
    connector: 'cais_safety',
    baseUrl: 'https://www.safe.ai/feed.xml',
    authType: 'none',
    categories: ['ai-safety', 'research', 'policy'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Center for AI Safety',
    region: 'North America',
    country: 'United States'
  },
  epoch_ai: {
    id: 'epoch_ai',
    name: 'Epoch AI Research',
    description: 'Empirical data, compute trends, algorithmic progress rates, and forecasting for artificial intelligence',
    enabled: true,
    protocol: 'rss',
    connector: 'epoch_ai',
    baseUrl: 'https://epochai.org/blog/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'policy'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Epoch AI',
    region: 'Global',
    country: 'United States'
  },
  lesswrong_ai: {
    id: 'lesswrong_ai',
    name: 'LessWrong AI Community',
    description: 'Foundational discussions on rationality, artificial general intelligence alignment, and decision theory',
    enabled: true,
    protocol: 'rss',
    connector: 'lesswrong_ai',
    baseUrl: 'https://www.lesswrong.com/feed.xml',
    authType: 'none',
    categories: ['ai-safety', 'community', 'research'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'LessWrong Community',
    region: 'Global',
    country: 'United States'
  },
  govai_oxford: {
    id: 'govai_oxford',
    name: 'Centre for the Governance of AI (GovAI)',
    description: 'Pioneering research in global governance, semiconductor supply chains, and AI safety international treaties',
    enabled: true,
    protocol: 'rss',
    connector: 'govai_oxford',
    baseUrl: 'https://www.governance.ai/feed.xml',
    authType: 'none',
    categories: ['policy', 'ai-safety', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Centre for the Governance of AI',
    region: 'Europe',
    country: 'United Kingdom'
  },

  // === 2. UNIVERSITY & FRONTIER LAB RESEARCH BLOGS ===
  bair_berkeley: {
    id: 'bair_berkeley',
    name: 'Berkeley AI Research (BAIR) Blog',
    description: 'UC Berkeley researchers on robotics, reinforcement learning, computer vision, and foundation models',
    enabled: true,
    protocol: 'rss',
    connector: 'bair_berkeley',
    baseUrl: 'https://bair.berkeley.edu/blog/feed.xml',
    authType: 'none',
    categories: ['research', 'ai', 'robotics'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'UC Berkeley BAIR Lab',
    region: 'North America',
    country: 'United States'
  },
  stanford_hai: {
    id: 'stanford_hai',
    name: 'Stanford HAI (Human-Centered AI)',
    description: 'Stanford Institute for Human-Centered Artificial Intelligence research, policy, and AI Index reports',
    enabled: true,
    protocol: 'rss',
    connector: 'stanford_hai',
    baseUrl: 'https://hai.stanford.edu/news/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'policy'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Stanford University HAI',
    region: 'North America',
    country: 'United States'
  },
  cmu_lti: {
    id: 'cmu_lti',
    name: 'CMU Language Technologies Institute',
    description: 'Carnegie Mellon University frontier research in natural language processing, speech, and multimodal systems',
    enabled: true,
    protocol: 'rss',
    connector: 'cmu_lti',
    baseUrl: 'https://www.lti.cs.cmu.edu/news/rss.xml',
    authType: 'none',
    categories: ['research', 'llms', 'nlp'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Carnegie Mellon University',
    region: 'North America',
    country: 'United States'
  },
  vector_institute: {
    id: 'vector_institute',
    name: 'Vector Institute for Artificial Intelligence',
    description: 'Toronto-based AI research institute founded by Geoffrey Hinton advancing deep learning and generative AI',
    enabled: true,
    protocol: 'rss',
    connector: 'vector_institute',
    baseUrl: 'https://vectorinstitute.ai/feed/',
    authType: 'none',
    categories: ['research', 'ai', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Vector Institute',
    region: 'North America',
    country: 'Canada'
  },
  mila_quebec: {
    id: 'mila_quebec',
    name: 'Mila Quebec AI Institute',
    description: 'Yoshua Bengio lead AI research institute driving deep learning, AI for science, and drug discovery',
    enabled: true,
    protocol: 'rss',
    connector: 'mila_quebec',
    baseUrl: 'https://mila.quebec/en/news/rss',
    authType: 'none',
    categories: ['research', 'ai', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Mila Quebec',
    region: 'North America',
    country: 'Canada'
  },
  turing_institute: {
    id: 'turing_institute',
    name: 'Alan Turing Institute',
    description: 'The UK national institute for data science and artificial intelligence research, defence, and health',
    enabled: true,
    protocol: 'rss',
    connector: 'turing_institute',
    baseUrl: 'https://www.turing.ac.uk/news/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'policy'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'The Alan Turing Institute',
    region: 'Europe',
    country: 'United Kingdom'
  },
  inria_ai: {
    id: 'inria_ai',
    name: 'Inria French National AI Research',
    description: 'National institute for research in digital science, computer science, and mathematical foundations of AI',
    enabled: true,
    protocol: 'rss',
    connector: 'inria_ai',
    baseUrl: 'https://www.inria.fr/en/rss.xml',
    authType: 'none',
    categories: ['research', 'technology', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Inria Research France',
    region: 'Europe',
    country: 'France'
  },
  eth_zurich_ai: {
    id: 'eth_zurich_ai',
    name: 'ETH Zurich AI Center',
    description: 'Interdisciplinary research center uniting computer science, robotics, and physical AI in Switzerland',
    enabled: true,
    protocol: 'rss',
    connector: 'eth_zurich_ai',
    baseUrl: 'https://ai.ethz.ch/news-and-events/news.rss',
    authType: 'none',
    categories: ['research', 'ai', 'robotics'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ETH Zurich',
    region: 'Europe',
    country: 'Switzerland'
  },
  max_planck_is: {
    id: 'max_planck_is',
    name: 'Max Planck Institute for Intelligent Systems',
    description: 'Fundamental research into biological and artificial perception, learning, and control algorithms',
    enabled: true,
    protocol: 'rss',
    connector: 'max_planck_is',
    baseUrl: 'https://is.mpg.de/news.rss',
    authType: 'none',
    categories: ['research', 'robotics', 'ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Max Planck Society',
    region: 'Europe',
    country: 'Germany'
  },

  // === 3. VECTOR DATABASES, FRAMEWORKS & LLMOPS ===
  pinecone_blog: {
    id: 'pinecone_blog',
    name: 'Pinecone Vector Database Blog',
    description: 'Vector search architectures, RAG design patterns, hybrid retrieval, and real-time embedding indexing',
    enabled: true,
    protocol: 'rss',
    connector: 'pinecone_blog',
    baseUrl: 'https://www.pinecone.io/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'llms', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Pinecone Systems',
    region: 'North America',
    country: 'United States'
  },
  weaviate_blog: {
    id: 'weaviate_blog',
    name: 'Weaviate Vector Database Insights',
    description: 'Open-source vector database engineering, multimodal search, GraphQL integration, and generative search',
    enabled: true,
    protocol: 'rss',
    connector: 'weaviate_blog',
    baseUrl: 'https://weaviate.io/blog/rss.xml',
    authType: 'none',
    categories: ['open-source-ai', 'developer-tools', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Weaviate B.V.',
    region: 'Global',
    country: 'Netherlands'
  },
  qdrant_blog: {
    id: 'qdrant_blog',
    name: 'Qdrant Vector Search Engine',
    description: 'Rust-based vector database internals, quantization, payload filtering, and distributed search benchmarks',
    enabled: true,
    protocol: 'rss',
    connector: 'qdrant_blog',
    baseUrl: 'https://qdrant.tech/blog/index.xml',
    authType: 'none',
    categories: ['developer-tools', 'open-source-ai', 'programming'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Qdrant',
    region: 'Europe',
    country: 'Germany'
  },
  langchain_blog: {
    id: 'langchain_blog',
    name: 'LangChain Framework Blog',
    description: 'Autonomous AI agents, LangGraph multi-agent systems, prompt composition, and LLM orchestration',
    enabled: true,
    protocol: 'rss',
    connector: 'langchain_blog',
    baseUrl: 'https://blog.langchain.dev/rss/',
    authType: 'none',
    categories: ['llms', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 15,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'LangChain',
    region: 'North America',
    country: 'United States'
  },
  llamaindex_blog: {
    id: 'llamaindex_blog',
    name: 'LlamaIndex Data Framework',
    description: 'Context augmentation, structured data indexing, knowledge graphs for LLMs, and RAG evaluation',
    enabled: true,
    protocol: 'rss',
    connector: 'llamaindex_blog',
    baseUrl: 'https://www.llamaindex.ai/blog/rss.xml',
    authType: 'none',
    categories: ['llms', 'developer-tools', 'ai'],
    fetchIntervalMinutes: 15,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'LlamaIndex',
    region: 'North America',
    country: 'United States'
  },
  wandb_blog: {
    id: 'wandb_blog',
    name: 'Weights & Biases (W&B) Engineering',
    description: 'Machine learning experiment tracking, model evaluation, artifact versioning, and LLM fine-tuning logs',
    enabled: true,
    protocol: 'rss',
    connector: 'wandb_blog',
    baseUrl: 'https://wandb.ai/fully-connected/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'machine-learning', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Weights & Biases',
    region: 'North America',
    country: 'United States'
  },
  neptune_ai: {
    id: 'neptune_ai',
    name: 'Neptune.ai MLOps & Experiment Tracking',
    description: 'In-depth tutorials on MLOps pipelines, distributed model training, hyperparameters, and GPU telemetry',
    enabled: true,
    protocol: 'rss',
    connector: 'neptune_ai',
    baseUrl: 'https://neptune.ai/blog/feed',
    authType: 'none',
    categories: ['developer-tools', 'machine-learning', 'programming'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Neptune.ai',
    region: 'Europe',
    country: 'Poland'
  },
  arize_ai: {
    id: 'arize_ai',
    name: 'Arize AI Observability & LLM Evaluation',
    description: 'AI model monitoring, embedding drift detection, hallucination tracing, and Phoenix open-source evals',
    enabled: true,
    protocol: 'rss',
    connector: 'arize_ai',
    baseUrl: 'https://arize.com/blog/feed/',
    authType: 'none',
    categories: ['developer-tools', 'ai', 'machine-learning'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Arize AI',
    region: 'North America',
    country: 'United States'
  },

  // === 4. CHIPS, HARDWARE & ACCELERATED SYSTEMS ===
  semianalysis_feed: {
    id: 'semianalysis_feed',
    name: 'SemiAnalysis (Dylan Patel)',
    description: 'In-depth semiconductor supply chain analysis, wafer yields, HBM memory packaging, and AI datacenter economics',
    enabled: true,
    protocol: 'rss',
    connector: 'semianalysis_feed',
    baseUrl: 'https://www.semianalysis.com/feed',
    authType: 'none',
    categories: ['hardware', 'semiconductors', 'business'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'SemiAnalysis',
    region: 'North America',
    country: 'United States'
  },
  servethehome: {
    id: 'servethehome',
    name: 'ServeTheHome (STH)',
    description: 'Enterprise server hardware, Nvidia DGX / HGX clusters, PCIe switches, liquid cooling, and datacenter tech',
    enabled: true,
    protocol: 'rss',
    connector: 'servethehome',
    baseUrl: 'https://www.servethehome.com/feed/',
    authType: 'none',
    categories: ['hardware', 'technology', 'cloud'],
    fetchIntervalMinutes: 15,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'ServeTheHome (Patrick Kennedy)',
    region: 'North America',
    country: 'United States'
  },
  next_platform: {
    id: 'next_platform',
    name: 'The Next Platform',
    description: 'High-performance computing (HPC), AI supercomputers, hyperscale infrastructure, and chip architecture',
    enabled: true,
    protocol: 'rss',
    connector: 'next_platform',
    baseUrl: 'https://www.nextplatform.com/feed/',
    authType: 'none',
    categories: ['hardware', 'cloud', 'semiconductors'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'The Next Platform (Timothy Prickett Morgan)',
    region: 'North America',
    country: 'United States'
  },
  semiengineering: {
    id: 'semiengineering',
    name: 'Semiconductor Engineering',
    description: 'Deep technical analysis of 2nm and GAA transistors, chiplets, EUV lithography, and packaging tech',
    enabled: true,
    protocol: 'rss',
    connector: 'semiengineering',
    baseUrl: 'https://semiengineering.com/feed/',
    authType: 'none',
    categories: ['semiconductors', 'hardware', 'research'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Semiconductor Engineering',
    region: 'North America',
    country: 'United States'
  },
  chipsandcheese: {
    id: 'chipsandcheese',
    name: 'Chips and Cheese',
    description: 'Microarchitectural deep dives, cache latency tests, execution pipeline analyses, and instruction throughput',
    enabled: true,
    protocol: 'rss',
    connector: 'chipsandcheese',
    baseUrl: 'https://chipsandcheese.com/feed/',
    authType: 'none',
    categories: ['hardware', 'semiconductors', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Chips and Cheese',
    region: 'North America',
    country: 'United States'
  },
  eetimes_chips: {
    id: 'eetimes_chips',
    name: 'EE Times Semiconductor & Design',
    description: 'Global electronics and semiconductor news covering silicon foundries, analog chips, and automotive ICs',
    enabled: true,
    protocol: 'rss',
    connector: 'eetimes_chips',
    baseUrl: 'https://www.eetimes.com/feed/',
    authType: 'none',
    categories: ['semiconductors', 'hardware', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'EE Times (AspenCore)',
    region: 'Global',
    country: 'United States'
  },
  arm_community: {
    id: 'arm_community',
    name: 'Arm Architecture & Neoverse Blog',
    description: 'Arm instruction set architecture, Neoverse datacenter cores, Ethos NPUs, and low-power edge AI',
    enabled: true,
    protocol: 'rss',
    connector: 'arm_community',
    baseUrl: 'https://community.arm.com/cfs-filesystemfile/__key/communityserver-components-blogs-rss/00-00-00-00-24.xml',
    authType: 'none',
    categories: ['hardware', 'semiconductors', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Arm Community',
    region: 'Europe',
    country: 'United Kingdom'
  },
  qualcomm_ai: {
    id: 'qualcomm_ai',
    name: 'Qualcomm On-Device AI & Snapdragon',
    description: 'Neural Processing Unit (NPU) innovations, INT4 quantization on mobile, and low-latency edge inference',
    enabled: true,
    protocol: 'rss',
    connector: 'qualcomm_ai',
    baseUrl: 'https://www.qualcomm.com/news/onq/feed',
    authType: 'none',
    categories: ['hardware', 'ai', 'mobile'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Qualcomm Technologies',
    region: 'North America',
    country: 'United States'
  },

  // === 5. QUANTUM COMPUTING & EMERGING PHYSICS ===
  quantum_insider: {
    id: 'quantum_insider',
    name: 'The Quantum Insider',
    description: 'Commercial quantum computing hardware, superconducting qubits, neutral-atom processors, and quantum algorithms',
    enabled: true,
    protocol: 'rss',
    connector: 'quantum_insider',
    baseUrl: 'https://thequantuminsider.com/feed/',
    authType: 'none',
    categories: ['quantum', 'technology', 'research'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'The Quantum Insider',
    region: 'Global',
    country: 'United Kingdom'
  },
  ibm_quantum: {
    id: 'ibm_quantum',
    name: 'IBM Quantum Computing Blog',
    description: 'Qiskit open-source quantum SDK, utility-scale quantum error mitigation, and superconducting processors',
    enabled: true,
    protocol: 'rss',
    connector: 'ibm_quantum',
    baseUrl: 'https://www.ibm.com/blogs/research/category/quantum-computing/feed/',
    authType: 'none',
    categories: ['quantum', 'research', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'IBM Quantum',
    region: 'North America',
    country: 'United States'
  },

  // === 6. ROBOTICS & AUTONOMOUS SYSTEMS ===
  robot_report: {
    id: 'robot_report',
    name: 'The Robot Report',
    description: 'Commercial robotics, mobile manipulators, autonomous mobile robots (AMRs), and industrial sensors',
    enabled: true,
    protocol: 'rss',
    connector: 'robot_report',
    baseUrl: 'https://www.therobotreport.com/feed/',
    authType: 'none',
    categories: ['robotics', 'hardware', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'The Robot Report (WTWH Media)',
    region: 'North America',
    country: 'United States'
  },
  ieee_automaton: {
    id: 'ieee_automaton',
    name: 'IEEE Spectrum Automaton Robotics',
    description: 'Cutting-edge academic robotics, bipedal locomotion, soft robotics, bio-inspired drones, and exoskeletons',
    enabled: true,
    protocol: 'rss',
    connector: 'ieee_automaton',
    baseUrl: 'https://spectrum.ieee.org/rss/topic/robotics/fulltext',
    authType: 'none',
    categories: ['robotics', 'research', 'hardware'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'IEEE Spectrum',
    region: 'Global',
    country: 'United States'
  },
  waymo_blog: {
    id: 'waymo_blog',
    name: 'Waymo Autonomous Driving Blog',
    description: 'Autonomous vehicle safety records, multimodal perception systems, sensor fusion, and commercial robotaxi expansion',
    enabled: true,
    protocol: 'rss',
    connector: 'waymo_blog',
    baseUrl: 'https://waymo.com/blog/rss.xml',
    authType: 'none',
    categories: ['robotics', 'ai', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Waymo (Alphabet)',
    region: 'North America',
    country: 'United States'
  },

  // === 7. EXPERT PRACTITIONER BLOGS & RESEARCH NEWSLETTERS ===
  chiphuyen_blog: {
    id: 'chiphuyen_blog',
    name: 'Chip Huyen (Machine Learning Systems)',
    description: 'Designing Machine Learning Systems author on production AI architectures, real-time data, and evaluation',
    enabled: true,
    protocol: 'rss',
    connector: 'chiphuyen_blog',
    baseUrl: 'https://huyenchip.com/feed.xml',
    authType: 'none',
    categories: ['machine-learning', 'programming', 'ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Chip Huyen',
    region: 'North America',
    country: 'United States'
  },
  lilian_weng: {
    id: 'lilian_weng',
    name: "Lilian Weng's AI Log",
    description: 'Ex-OpenAI VP of Research comprehensive surveys on diffusion, LLM agents, memory, and RLHF',
    enabled: true,
    protocol: 'rss',
    connector: 'lilian_weng',
    baseUrl: 'https://lilianweng.github.io/index.xml',
    authType: 'none',
    categories: ['research', 'ai', 'llms'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Lilian Weng',
    region: 'North America',
    country: 'United States'
  },
  sebastian_raschka: {
    id: 'sebastian_raschka',
    name: 'Ahead of AI (Sebastian Raschka)',
    description: 'Hands-on architectures for building LLMs from scratch, LoRA parameter-efficient fine-tuning, and model benchmarks',
    enabled: true,
    protocol: 'rss',
    connector: 'sebastian_raschka',
    baseUrl: 'https://magazine.sebastianraschka.com/feed',
    authType: 'none',
    categories: ['llms', 'research', 'machine-learning'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Sebastian Raschka (Ahead of AI)',
    region: 'North America',
    country: 'United States'
  },
  eugene_yan: {
    id: 'eugene_yan',
    name: 'Eugene Yan (Applied AI & Systems)',
    description: 'Practical guides on recommendation systems, LLM evaluation, search relevance, and deploying models to production',
    enabled: true,
    protocol: 'rss',
    connector: 'eugene_yan',
    baseUrl: 'https://eugeneyan.com/rss/',
    authType: 'none',
    categories: ['machine-learning', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Eugene Yan (Amazon Applied AI)',
    region: 'North America',
    country: 'United States'
  },
  jay_alammar: {
    id: 'jay_alammar',
    name: 'Jay Alammar (Visual Machine Learning)',
    description: 'World-famous illustrated guides to Transformers, BERT, GPT, Attention mechanisms, and Stable Diffusion',
    enabled: true,
    protocol: 'rss',
    connector: 'jay_alammar',
    baseUrl: 'https://jalammar.github.io/feed.xml',
    authType: 'none',
    categories: ['research', 'ai', 'llms'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Jay Alammar (Cohere)',
    region: 'North America',
    country: 'United States'
  },
  simonw_blog: {
    id: 'simonw_blog',
    name: 'Simon Willison’s Weblog (LLM & Security)',
    description: 'Prompt injection security vulnerabilities, local LLMs with llamafile, SQLite integration, and datasette engineering',
    enabled: true,
    protocol: 'rss',
    connector: 'simonw_blog',
    baseUrl: 'https://simonwillison.net/atom/everything/',
    authType: 'none',
    categories: ['llms', 'cybersecurity', 'programming'],
    fetchIntervalMinutes: 15,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Simon Willison',
    region: 'North America',
    country: 'United States'
  },
  vicki_boykis: {
    id: 'vicki_boykis',
    name: 'Vicki Boykis (Data Engineering & Embeddings)',
    description: 'Machine learning systems, embeddings architectures, vector search internals, and distributed databases',
    enabled: true,
    protocol: 'rss',
    connector: 'vicki_boykis',
    baseUrl: 'https://vickiboykis.com/feed.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'machine-learning'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Vicki Boykis (Automattic)',
    region: 'North America',
    country: 'United States'
  },
  hamel_husain: {
    id: 'hamel_husain',
    name: 'Hamel Husain (Practical LLM Evals)',
    description: 'Industry-standard guides on LLM fine-tuning, automated evaluations, synthetic data pipelines, and error analysis',
    enabled: true,
    protocol: 'rss',
    connector: 'hamel_husain',
    baseUrl: 'https://hamel.dev/index.xml',
    authType: 'none',
    categories: ['llms', 'developer-tools', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Hamel Husain',
    region: 'North America',
    country: 'United States'
  },
  interconnects_ai: {
    id: 'interconnects_ai',
    name: 'Interconnects (Nathan Lambert)',
    description: 'Post-training reinforcement learning (RLHF, DPO), open foundation model weights, and AI ecosystem politics',
    enabled: true,
    protocol: 'rss',
    connector: 'interconnects_ai',
    baseUrl: 'https://www.interconnects.ai/feed',
    authType: 'none',
    categories: ['llms', 'research', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Nathan Lambert (Ai2 / Interconnects)',
    region: 'North America',
    country: 'United States'
  },
  explosion_ai: {
    id: 'explosion_ai',
    name: 'Explosion AI Blog (spaCy & Prodigy)',
    description: 'Modern NLP software engineering, data annotation methodology, and transformer pipelines from the creators of spaCy',
    enabled: true,
    protocol: 'rss',
    connector: 'explosion_ai',
    baseUrl: 'https://explosion.ai/blog/feed.xml',
    authType: 'none',
    categories: ['developer-tools', 'nlp', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Explosion AI (Ines Montani & Matthew Honnibal)',
    region: 'Europe',
    country: 'Germany'
  },

  // === 8. ENTERPRISE CLOUD, SYSTEMS & OPEN SOURCE PLATFORMS ===
  cloudflare_blog: {
    id: 'cloudflare_blog',
    name: 'Cloudflare Blog & Workers AI',
    description: 'Edge computing, global serverless GPUs, DDoS mitigation, web standards, and distributed systems architecture',
    enabled: true,
    protocol: 'rss',
    connector: 'cloudflare_blog',
    baseUrl: 'https://blog.cloudflare.com/rss/',
    authType: 'none',
    categories: ['cloud', 'cybersecurity', 'developer-tools'],
    fetchIntervalMinutes: 15,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cloudflare Inc.',
    region: 'North America',
    country: 'United States'
  },
  databricks_blog: {
    id: 'databricks_blog',
    name: 'Databricks Engineering & Mosaic AI',
    description: 'Data lakehouse architecture, Apache Spark, MLflow, Mosaic AI foundation models, and enterprise GenAI',
    enabled: true,
    protocol: 'rss',
    connector: 'databricks_blog',
    baseUrl: 'https://www.databricks.com/blog/rss.xml',
    authType: 'none',
    categories: ['cloud', 'machine-learning', 'developer-tools'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Databricks',
    region: 'North America',
    country: 'United States'
  },
  snowflake_blog: {
    id: 'snowflake_blog',
    name: 'Snowflake Engineering & Cortex AI',
    description: 'Cloud data warehouse optimization, Snowflake Cortex LLMs, Iceberg table formats, and secure data sharing',
    enabled: true,
    protocol: 'rss',
    connector: 'snowflake_blog',
    baseUrl: 'https://www.snowflake.com/blog/feed/',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Snowflake Inc.',
    region: 'North America',
    country: 'United States'
  },
  redis_blog: {
    id: 'redis_blog',
    name: 'Redis Engineering & Real-Time AI',
    description: 'In-memory database caching, vector similarity search, semantic caching for LLMs, and pub-sub messaging',
    enabled: true,
    protocol: 'rss',
    connector: 'redis_blog',
    baseUrl: 'https://redis.io/blog/feed/',
    authType: 'none',
    categories: ['developer-tools', 'cloud', 'programming'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Redis Ltd.',
    region: 'Global',
    country: 'United States'
  },
  mongodb_blog: {
    id: 'mongodb_blog',
    name: 'MongoDB Engineering & Vector Search',
    description: 'Document database architectures, Atlas Vector Search, distributed replica sets, and operational AI data',
    enabled: true,
    protocol: 'rss',
    connector: 'mongodb_blog',
    baseUrl: 'https://www.mongodb.com/blog/rss',
    authType: 'none',
    categories: ['developer-tools', 'cloud', 'programming'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'MongoDB Inc.',
    region: 'North America',
    country: 'United States'
  },
  neo4j_blog: {
    id: 'neo4j_blog',
    name: 'Neo4j Graph Database & GraphRAG',
    description: 'Knowledge graph construction, GraphRAG for hallucinations reduction, Cypher queries, and graph algorithms',
    enabled: true,
    protocol: 'rss',
    connector: 'neo4j_blog',
    baseUrl: 'https://neo4j.com/blog/feed/',
    authType: 'none',
    categories: ['developer-tools', 'ai', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Neo4j',
    region: 'North America',
    country: 'United States'
  },
  thenewstack: {
    id: 'thenewstack',
    name: 'The New Stack (Cloud Native & AI)',
    description: 'Kubernetes orchestration, platform engineering, WebAssembly, open-source AI infrastructure, and microservices',
    enabled: true,
    protocol: 'rss',
    connector: 'thenewstack',
    baseUrl: 'https://thenewstack.io/feed/',
    authType: 'none',
    categories: ['cloud', 'developer-tools', 'technology'],
    fetchIntervalMinutes: 15,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'The New Stack (Insight Partners)',
    region: 'North America',
    country: 'United States'
  },
  infoq_ai: {
    id: 'infoq_ai',
    name: 'InfoQ AI, ML & Data Engineering',
    description: 'Software architecture trends, enterprise generative AI patterns, model serving, and distributed caching',
    enabled: true,
    protocol: 'rss',
    connector: 'infoq_ai',
    baseUrl: 'https://feed.infoq.com/ai-ml-data-eng/news/',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'cloud'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'InfoQ (C4Media)',
    region: 'Global',
    country: 'Canada'
  },
  kdnuggets: {
    id: 'kdnuggets',
    name: 'KDnuggets Data Science & Machine Learning',
    description: 'Authoritative data science community tutorials, Python libraries, SQL analytics, and LLM cheat sheets',
    enabled: true,
    protocol: 'rss',
    connector: 'kdnuggets',
    baseUrl: 'https://www.kdnuggets.com/feed',
    authType: 'none',
    categories: ['machine-learning', 'programming', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'KDnuggets (Gregory Piatetsky-Shapiro)',
    region: 'North America',
    country: 'United States'
  },
  towards_datascience: {
    id: 'towards_datascience',
    name: 'Towards Data Science',
    description: 'Practitioner essays and technical walkthroughs across machine learning, statistics, neural architectures, and MLOps',
    enabled: true,
    protocol: 'rss',
    connector: 'towards_datascience',
    baseUrl: 'https://towardsdatascience.com/feed',
    authType: 'none',
    categories: ['machine-learning', 'research', 'programming'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Towards Data Science Publication',
    region: 'Global',
    country: 'United States'
  },
  fastai_blog: {
    id: 'fastai_blog',
    name: 'Fast.ai Blog (Jeremy Howard)',
    description: 'Making neural networks uncool again: accessible deep learning, PyTorch tips, ULMFiT, and practical AI research',
    enabled: true,
    protocol: 'rss',
    connector: 'fastai_blog',
    baseUrl: 'https://www.fast.ai/index.xml',
    authType: 'none',
    categories: ['machine-learning', 'research', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Fast.ai (Jeremy Howard)',
    region: 'Global',
    country: 'Australia'
  },
  pyimagesearch: {
    id: 'pyimagesearch',
    name: 'PyImageSearch (OpenCV & Computer Vision)',
    description: 'Computer vision, OpenCV tutorials, YOLO object detection, image segmentation, and deep learning in Python',
    enabled: true,
    protocol: 'rss',
    connector: 'pyimagesearch',
    baseUrl: 'https://pyimagesearch.com/feed/',
    authType: 'none',
    categories: ['computer-vision', 'programming', 'machine-learning'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'PyImageSearch',
    region: 'North America',
    country: 'United States'
  },
  machinelearningmastery: {
    id: 'machinelearningmastery',
    name: 'Machine Learning Mastery',
    description: 'Step-by-step applied machine learning tutorials, deep learning with Keras, and time series forecasting',
    enabled: true,
    protocol: 'rss',
    connector: 'machinelearningmastery',
    baseUrl: 'https://machinelearningmastery.com/feed/',
    authType: 'none',
    categories: ['machine-learning', 'programming', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Machine Learning Mastery',
    region: 'Global',
    country: 'Australia'
  },
  realpython_ml: {
    id: 'realpython_ml',
    name: 'Real Python Tutorials',
    description: 'Python programming mastery, async programming, data structures, NumPy, pandas, and web framework engineering',
    enabled: true,
    protocol: 'rss',
    connector: 'realpython_ml',
    baseUrl: 'https://realpython.com/atom.xml',
    authType: 'none',
    categories: ['programming', 'developer-tools'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Real Python (Dan Bader)',
    region: 'North America',
    country: 'Canada'
  },

  // === 9. PRESTIGIOUS ACADEMIC & PEER-REVIEWED SCIENCE ===
  nature_machine_intelligence: {
    id: 'nature_machine_intelligence',
    name: 'Nature Machine Intelligence',
    description: 'Peer-reviewed research across machine learning, robotics, cognitive systems, and societal impacts of AI',
    enabled: true,
    protocol: 'rss',
    connector: 'nature_machine_intelligence',
    baseUrl: 'https://www.nature.com/natmachintell.rss',
    authType: 'none',
    categories: ['research', 'ai', 'robotics'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Nature Portfolio / Springer Nature',
    region: 'Global',
    country: 'United Kingdom'
  },
  science_robotics: {
    id: 'science_robotics',
    name: 'Science Robotics (AAAS)',
    description: 'Transformative peer-reviewed research in micro-robotics, surgical robots, space robotics, and physical autonomy',
    enabled: true,
    protocol: 'rss',
    connector: 'science_robotics',
    baseUrl: 'https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=scirobotics',
    authType: 'none',
    categories: ['research', 'robotics', 'hardware'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'American Association for the Advancement of Science (AAAS)',
    region: 'North America',
    country: 'United States'
  },
  acm_cacm: {
    id: 'acm_cacm',
    name: 'Communications of the ACM (CACM)',
    description: 'The flagship magazine of the Association for Computing Machinery on computing practice, research, and ethics',
    enabled: true,
    protocol: 'rss',
    connector: 'acm_cacm',
    baseUrl: 'https://cacm.acm.org/feed/',
    authType: 'none',
    categories: ['research', 'technology', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Association for Computing Machinery (ACM)',
    region: 'Global',
    country: 'United States'
  },
  ieee_computer_society: {
    id: 'ieee_computer_society',
    name: 'IEEE Computer Society News',
    description: 'IEEE technical committee updates on cloud computing, cybersecurity, high performance systems, and software engineering',
    enabled: true,
    protocol: 'rss',
    connector: 'ieee_computer_society',
    baseUrl: 'https://www.computer.org/rss/news',
    authType: 'none',
    categories: ['technology', 'research', 'cybersecurity'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'IEEE Computer Society',
    region: 'Global',
    country: 'United States'
  },
  mit_news_ai: {
    id: 'mit_news_ai',
    name: 'MIT News: Artificial Intelligence',
    description: 'Breakthroughs from MIT CSAIL and the Schwarzman College of Computing in neural science, robotics, and algorithmic theory',
    enabled: true,
    protocol: 'rss',
    connector: 'mit_news_ai',
    baseUrl: 'https://news.mit.edu/rss/topic/artificial-intelligence2',
    authType: 'none',
    categories: ['research', 'ai', 'robotics'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'MIT News Office',
    region: 'North America',
    country: 'United States'
  },
  caltech_news: {
    id: 'caltech_news',
    name: 'Caltech Computing & Mathematical Sciences',
    description: 'Pioneering work in quantum information, computational science, autonomous spacecraft, and applied mathematics',
    enabled: true,
    protocol: 'rss',
    connector: 'caltech_news',
    baseUrl: 'https://www.caltech.edu/about/news/rss.xml',
    authType: 'none',
    categories: ['research', 'quantum', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'California Institute of Technology (Caltech)',
    region: 'North America',
    country: 'United States'
  },

  // === 10. INTERNATIONAL LABS & EUROPEAN / ASIAN AI CENTRES ===
  riken_aip: {
    id: 'riken_aip',
    name: 'RIKEN Center for Advanced Intelligence Project',
    description: 'Japan national AI research center on mathematical machine learning, ethical AI, and disaster prevention models',
    enabled: true,
    protocol: 'rss',
    connector: 'riken_aip',
    baseUrl: 'https://aip.riken.jp/feed/',
    authType: 'none',
    categories: ['research', 'ai', 'policy'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'RIKEN AIP Japan',
    region: 'Asia',
    country: 'Japan'
  },
  dfki_germany: {
    id: 'dfki_germany',
    name: 'DFKI (German Research Center for Artificial Intelligence)',
    description: 'Leading European research center for innovative AI software technologies, autonomous systems, and cognitive assistants',
    enabled: true,
    protocol: 'rss',
    connector: 'dfki_germany',
    baseUrl: 'https://www.dfki.de/en/web/news/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'robotics'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'DFKI Germany',
    region: 'Europe',
    country: 'Germany'
  },
  cwi_amsterdam: {
    id: 'cwi_amsterdam',
    name: 'CWI Amsterdam (Centrum Wiskunde & Informatica)',
    description: 'The national research institute for mathematics and computer science in the Netherlands, birth home of Python',
    enabled: true,
    protocol: 'rss',
    connector: 'cwi_amsterdam',
    baseUrl: 'https://www.cwi.nl/en/news/rss.xml',
    authType: 'none',
    categories: ['research', 'programming', 'quantum'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'CWI Netherlands',
    region: 'Europe',
    country: 'Netherlands'
  },
  fraunhofer_ai: {
    id: 'fraunhofer_ai',
    name: 'Fraunhofer Institute for Applied IT & AI',
    description: 'Applied microelectronics, trustworthy AI certification, industrial cyber-physical systems, and edge automation',
    enabled: true,
    protocol: 'rss',
    connector: 'fraunhofer_ai',
    baseUrl: 'https://www.fit.fraunhofer.de/en/press-releases/rss.xml',
    authType: 'none',
    categories: ['research', 'technology', 'hardware'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Fraunhofer Society',
    region: 'Europe',
    country: 'Germany'
  },

  // === 11. AUTONOMOUS ROBOTICS & PHYSICAL AI PIONEERS ===
  boston_dynamics_news: {
    id: 'boston_dynamics_news',
    name: 'Boston Dynamics Engineering Updates',
    description: 'Electric Atlas humanoid, Spot quadruped autonomy, warehouse logistics manipulation, and whole-body control',
    enabled: true,
    protocol: 'rss',
    connector: 'boston_dynamics_news',
    baseUrl: 'https://bostondynamics.com/feed/',
    authType: 'none',
    categories: ['robotics', 'hardware', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Boston Dynamics (Hyundai Motor Group)',
    region: 'North America',
    country: 'United States'
  },
  zoox_mobility: {
    id: 'zoox_mobility',
    name: 'Zoox Autonomous Mobility',
    description: 'Purpose-built bidirectional autonomous robotaxis, high-density LiDAR systems, and urban fleet operations',
    enabled: true,
    protocol: 'rss',
    connector: 'zoox_mobility',
    baseUrl: 'https://zoox.com/feed.xml',
    authType: 'none',
    categories: ['robotics', 'technology', 'ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Zoox (Amazon)',
    region: 'North America',
    country: 'United States'
  },
  aurora_innovation: {
    id: 'aurora_innovation',
    name: 'Aurora Autonomous Trucking & Driver',
    description: 'Class 8 commercial autonomous long-haul trucking, FirstLight FMCW LiDAR, and Aurora Horizon deployment',
    enabled: true,
    protocol: 'rss',
    connector: 'aurora_innovation',
    baseUrl: 'https://aurora.tech/feed.xml',
    authType: 'none',
    categories: ['robotics', 'technology', 'hardware'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Aurora Innovation Inc.',
    region: 'North America',
    country: 'United States'
  },
  figure_robotics: {
    id: 'figure_robotics',
    name: 'Figure AI Humanoid Robotics',
    description: 'General purpose autonomous humanoid robots for manufacturing, logistics, and dexterous physical labor',
    enabled: true,
    protocol: 'rss',
    connector: 'figure_robotics',
    baseUrl: 'https://www.figure.ai/feed.xml',
    authType: 'none',
    categories: ['robotics', 'ai', 'hardware'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Figure AI',
    region: 'North America',
    country: 'United States'
  },
  agility_robotics: {
    id: 'agility_robotics',
    name: 'Agility Robotics (Digit Humanoid)',
    description: 'Bipedal mobile manipulation robots designed to work safely alongside people in logistics and order fulfillment',
    enabled: true,
    protocol: 'rss',
    connector: 'agility_robotics',
    baseUrl: 'https://agilityrobotics.com/feed.xml',
    authType: 'none',
    categories: ['robotics', 'hardware', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Agility Robotics',
    region: 'North America',
    country: 'United States'
  },

  // === 12. OPEN ARCHITECTURES, STANDARDS & FOUNDATIONS ===
  riscv_international: {
    id: 'riscv_international',
    name: 'RISC-V International Architecture News',
    description: 'Open standard instruction set architecture (ISA), vector extensions for machine learning, and custom accelerators',
    enabled: true,
    protocol: 'rss',
    connector: 'riscv_international',
    baseUrl: 'https://riscv.org/feed/',
    authType: 'none',
    categories: ['hardware', 'semiconductors', 'open-source-ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'RISC-V International',
    region: 'Global',
    country: 'Switzerland'
  },
  linux_foundation_ai: {
    id: 'linux_foundation_ai',
    name: 'Linux Foundation AI & Data (LF AI)',
    description: 'Neutral open-source ecosystem driving PyTorch, ONNX, Milvus, and open-weight model sustainability',
    enabled: true,
    protocol: 'rss',
    connector: 'linux_foundation_ai',
    baseUrl: 'https://lfaidata.foundation/feed/',
    authType: 'none',
    categories: ['open-source-ai', 'developer-tools', 'cloud'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'LF AI & Data Foundation',
    region: 'Global',
    country: 'United States'
  },
  apache_software_foundation: {
    id: 'apache_software_foundation',
    name: 'Apache Software Foundation AI & Big Data',
    description: 'Open-source distributed backbones: Apache Arrow, Parquet, Kafka, Spark, Iceberg, and Flink',
    enabled: true,
    protocol: 'rss',
    connector: 'apache_software_foundation',
    baseUrl: 'https://blogs.apache.org/foundation/feed/entries/atom',
    authType: 'none',
    categories: ['developer-tools', 'cloud', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Apache Software Foundation',
    region: 'Global',
    country: 'United States'
  },

  // === 13. GENERATIVE MEDIA, CREATIVE AI & MULTIMODAL ===
  stability_ai_community: {
    id: 'stability_ai_community',
    name: 'Stability AI Research & Releases',
    description: 'Stable Diffusion 3, Stable Video, audio diffusion models, and open multimodal generative models',
    enabled: true,
    protocol: 'rss',
    connector: 'stability_ai_community',
    baseUrl: 'https://stability.ai/news?format=rss',
    authType: 'none',
    categories: ['open-source-ai', 'computer-vision', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Stability AI Ltd.',
    region: 'Global',
    country: 'United Kingdom'
  },
  runway_research: {
    id: 'runway_research',
    name: 'Runway Gen-3 Research & World Models',
    description: 'Generative video systems, multimodal world simulators, camera motion control, and AI filmmaking tools',
    enabled: true,
    protocol: 'rss',
    connector: 'runway_research',
    baseUrl: 'https://runwayml.com/feed.xml',
    authType: 'none',
    categories: ['computer-vision', 'research', 'ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Runway AI Inc.',
    region: 'North America',
    country: 'United States'
  },
  luma_ai_research: {
    id: 'luma_ai_research',
    name: 'Luma AI Dream Machine & 3D Gaussian Splats',
    description: 'Neural radiance fields (NeRFs), 3D Gaussian splatting, Dream Machine generative video, and spatial intelligence',
    enabled: true,
    protocol: 'rss',
    connector: 'luma_ai_research',
    baseUrl: 'https://lumalabs.ai/feed.xml',
    authType: 'none',
    categories: ['computer-vision', 'research', 'ai'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Luma AI Inc.',
    region: 'North America',
    country: 'United States'
  },

  // === 14. BIOLOGICAL AI, PROTEIN FOLDING & HEALTH AI ===
  deepmind_alphafold: {
    id: 'deepmind_alphafold',
    name: 'DeepMind Science & AlphaFold 3',
    description: 'Structure prediction of proteins, DNA, RNA, ligands, and molecular complexes driving biological discoveries',
    enabled: true,
    protocol: 'rss',
    connector: 'deepmind_alphafold',
    baseUrl: 'https://deepmind.google/discover/blog/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Google DeepMind',
    region: 'Global',
    country: 'United Kingdom'
  },
  broad_institute_ai: {
    id: 'broad_institute_ai',
    name: 'Broad Institute (MIT & Harvard) Genomic AI',
    description: 'Machine learning for single-cell genomics, variant effect predictors, CRISPR targeting, and computational biology',
    enabled: true,
    protocol: 'rss',
    connector: 'broad_institute_ai',
    baseUrl: 'https://www.broadinstitute.org/news/rss.xml',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Broad Institute of MIT and Harvard',
    region: 'North America',
    country: 'United States'
  },
  cell_patterns: {
    id: 'cell_patterns',
    name: 'Cell Press: Patterns (Data Science & AI in Science)',
    description: 'High-impact open-access journal publishing data science, artificial intelligence algorithms, and scientific datasets',
    enabled: true,
    protocol: 'rss',
    connector: 'cell_patterns',
    baseUrl: 'https://www.cell.com/patterns/current.rss',
    authType: 'none',
    categories: ['research', 'ai', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 30,
    attribution: 'Cell Press (Elsevier)',
    region: 'Global',
    country: 'United States'
  }
};
