import { SourceDefinition } from '../../types.js';

/**
 * Vanguard Sources Expansion:
 * Premium AI Frontier Labs, Deep-Dive Audio Podcasts, Humanoid Robotics,
 * Advanced Silicon/Semiconductors, Computational Biology & Next-Gen Developer Runtimes.
 */
export const VANGUARD_SOURCES: Record<string, SourceDefinition> = {
  // === 1. FRONTIER FOUNDATION MODEL LABS & AI PLATFORMS ===
  mistral_blog: {
    id: 'mistral_blog',
    name: 'Mistral AI News & Releases',
    description: 'Official releases, open foundation weights, Pixtral multimodal models, and Le Chat intelligence from Mistral AI',
    enabled: true,
    protocol: 'rss',
    connector: 'mistral_blog',
    baseUrl: 'https://mistral.ai/news/index.xml',
    authType: 'none',
    categories: ['ai', 'llms', 'open-source-ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Mistral AI',
    region: 'Europe',
    country: 'France'
  },
  xai_blog: {
    id: 'xai_blog',
    name: 'xAI Grok & Frontier Research',
    description: 'Frontier reasoning architectures, Grok vision, Colossus supercluster developments, and mathematical reasoning from xAI',
    enabled: true,
    protocol: 'rss',
    connector: 'xai_blog',
    baseUrl: 'https://x.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'llms', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'xAI',
    region: 'Global',
    country: 'United States'
  },
  perplexity_blog: {
    id: 'perplexity_blog',
    name: 'Perplexity AI Engineering & Search',
    description: 'Conversational search engines, live web grounding, RAG at internet scale, and agentic workflows from Perplexity AI',
    enabled: true,
    protocol: 'rss',
    connector: 'perplexity_blog',
    baseUrl: 'https://www.perplexity.ai/hub/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'ai-agents', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Perplexity AI',
    region: 'Global',
    country: 'United States'
  },
  meta_fair: {
    id: 'meta_fair',
    name: 'Meta Fundamental AI Research (FAIR)',
    description: 'Llama architectures, Segment Anything, open science, synthetic speech, and neuro-symbolic reasoning from Meta AI',
    enabled: true,
    protocol: 'rss',
    connector: 'meta_fair',
    baseUrl: 'https://ai.meta.com/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'research', 'llms'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Meta AI',
    region: 'Global',
    country: 'United States'
  },
  elevenlabs_blog: {
    id: 'elevenlabs_blog',
    name: 'ElevenLabs Voice AI & Generative Audio',
    description: 'State-of-the-art voice cloning, conversational agents, text-to-speech architectures, and real-time audio models',
    enabled: true,
    protocol: 'rss',
    connector: 'elevenlabs_blog',
    baseUrl: 'https://elevenlabs.io/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'technology', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'ElevenLabs',
    region: 'Global',
    country: 'United States'
  },
  vllm_blog: {
    id: 'vllm_blog',
    name: 'vLLM High-Throughput Inference Project',
    description: 'PagedAttention, spec decoding, continuous batching, and high-performance open-source LLM serving architectures',
    enabled: true,
    protocol: 'rss',
    connector: 'vllm_blog',
    baseUrl: 'https://blog.vllm.ai/feed.xml',
    authType: 'none',
    categories: ['open-source-ai', 'ai-hardware', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'vLLM Team',
    region: 'Global',
    country: 'United States'
  },
  suno_ai: {
    id: 'suno_ai',
    name: 'Suno AI Generative Audio Research',
    description: 'Diffusion and autoregressive transformer models synthesizing full-fidelity vocal and musical compositions',
    enabled: true,
    protocol: 'rss',
    connector: 'suno_ai',
    baseUrl: 'https://suno.com/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'technology', 'research'],
    fetchIntervalMinutes: 40,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Suno AI',
    region: 'Global',
    country: 'United States'
  },
  luma_ai: {
    id: 'luma_ai',
    name: 'Luma AI Dream Machine & World Models',
    description: '3D Gaussian splatting, video generative models, physics-aware neural scene reconstruction, and interactive worlds',
    enabled: true,
    protocol: 'rss',
    connector: 'luma_ai',
    baseUrl: 'https://lumalabs.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'research', 'technology'],
    fetchIntervalMinutes: 40,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Luma AI',
    region: 'Global',
    country: 'United States'
  },
  cognition_devin: {
    id: 'cognition_devin',
    name: 'Cognition AI & Devin Engineering',
    description: 'Autonomous software engineering agents, long-horizon planning, codebase refactoring, and benchmark evaluations',
    enabled: true,
    protocol: 'rss',
    connector: 'cognition_devin',
    baseUrl: 'https://www.cognition.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai-agents', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Cognition AI',
    region: 'Global',
    country: 'United States'
  },
  poolside_ai: {
    id: 'poolside_ai',
    name: 'Poolside AI Code Foundation Models',
    description: 'Pre-training frontier software intelligence, automated code synthesis, and reinforcement learning for compilers',
    enabled: true,
    protocol: 'rss',
    connector: 'poolside_ai',
    baseUrl: 'https://poolside.ai/blog/rss.xml',
    authType: 'none',
    categories: ['ai', 'programming', 'developer-tools'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Poolside AI',
    region: 'Global',
    country: 'France'
  },

  // === 2. AUDIO STREAMING & AI PODCASTS (DIRECT AUDIO MEDIA) ===
  latent_space_podcast: {
    id: 'latent_space_podcast',
    name: 'The Latent Space Podcast (Swyx & Alessio)',
    description: 'High-signal technical interviews with frontier AI researchers, model builders, agent engineers, and founders',
    enabled: true,
    protocol: 'rss',
    connector: 'latent_space_podcast',
    baseUrl: 'https://api.substack.com/feed/podcast/1084089.rss',
    authType: 'none',
    categories: ['ai', 'podcast', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'Latent Space',
    region: 'Global',
    country: 'United States'
  },
  eye_on_ai_podcast: {
    id: 'eye_on_ai_podcast',
    name: 'Eye on AI Podcast (Craig S. Smith)',
    description: 'Bi-weekly investigations into artificial general intelligence, transformer theory, and societal implications with top minds',
    enabled: true,
    protocol: 'rss',
    connector: 'eye_on_ai_podcast',
    baseUrl: 'https://feeds.megaphone.fm/eyeonai',
    authType: 'none',
    categories: ['ai', 'podcast', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'Eye on AI',
    region: 'Global',
    country: 'United States'
  },
  no_priors_podcast: {
    id: 'no_priors_podcast',
    name: 'No Priors Podcast (Elad Gil & Sarah Guo)',
    description: 'Conversations with the engineers, researchers, and founders defining the state of the art in artificial intelligence',
    enabled: true,
    protocol: 'rss',
    connector: 'no_priors_podcast',
    baseUrl: 'https://feeds.megaphone.fm/nopriors',
    authType: 'none',
    categories: ['ai', 'podcast', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'No Priors',
    region: 'Global',
    country: 'United States'
  },
  practical_ai_podcast: {
    id: 'practical_ai_podcast',
    name: 'Practical AI (Changelog Media)',
    description: 'Making artificial intelligence practical, productive, and accessible to software engineers and enterprise architects',
    enabled: true,
    protocol: 'rss',
    connector: 'practical_ai_podcast',
    baseUrl: 'https://changelog.com/practicalai/feed',
    authType: 'none',
    categories: ['ai', 'podcast', 'programming'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'Changelog Practical AI',
    region: 'Global',
    country: 'United States'
  },
  machine_learning_street_talk: {
    id: 'machine_learning_street_talk',
    name: 'Machine Learning Street Talk (MLST)',
    description: 'Unfiltered, rigorous technical debates on AGI, mathematical foundations, category theory, and cognition',
    enabled: true,
    protocol: 'rss',
    connector: 'machine_learning_street_talk',
    baseUrl: 'https://anchor.fm/s/1e8f2370/podcast/rss',
    authType: 'none',
    categories: ['research', 'podcast', 'ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'MLST (Tim Scarfe)',
    region: 'Global',
    country: 'United Kingdom'
  },
  ai_breakdown_podcast: {
    id: 'ai_breakdown_podcast',
    name: 'The AI Breakdown (Daily Audio)',
    description: 'Daily morning analysis of breaking AI news, regulatory updates, compute infrastructure, and startup ecosystems',
    enabled: true,
    protocol: 'rss',
    connector: 'ai_breakdown_podcast',
    baseUrl: 'https://anchor.fm/s/dfdf1e4/podcast/rss',
    authType: 'none',
    categories: ['ai', 'podcast', 'technology'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'The AI Breakdown',
    region: 'Global',
    country: 'United States'
  },
  gradient_dissent_podcast: {
    id: 'gradient_dissent_podcast',
    name: 'Gradient Dissent (Weights & Biases)',
    description: 'Behind the scenes with leading machine learning practitioners, researchers, and system designers',
    enabled: true,
    protocol: 'rss',
    connector: 'gradient_dissent_podcast',
    baseUrl: 'https://feeds.simplecast.com/8_j4w6w4',
    authType: 'none',
    categories: ['ai', 'podcast', 'developer-tools'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'Weights & Biases',
    region: 'Global',
    country: 'United States'
  },
  twiml_ai_podcast: {
    id: 'twiml_ai_podcast',
    name: 'TWIML AI Podcast (Sam Charrington)',
    description: 'Voice of the AI community exploring deep learning, natural language processing, neural architectures, and data science',
    enabled: true,
    protocol: 'rss',
    connector: 'twiml_ai_podcast',
    baseUrl: 'https://twimlai.com/feed/podcast',
    authType: 'none',
    categories: ['ai', 'podcast', 'machine-learning'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'TWIML AI',
    region: 'Global',
    country: 'United States'
  },

  // === 3. ROBOTICS & PHYSICAL INTELLIGENCE ===
  figure_ai: {
    id: 'figure_ai',
    name: 'Figure AI Humanoid Robotics',
    description: 'General-purpose humanoid robots (Figure 01 & 02) integrated with vision-language-action foundation models',
    enabled: true,
    protocol: 'rss',
    connector: 'figure_ai',
    baseUrl: 'https://www.figure.ai/news/rss.xml',
    authType: 'none',
    categories: ['robotics', 'ai', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Figure AI',
    region: 'Global',
    country: 'United States'
  },
  tesla_ai: {
    id: 'tesla_ai',
    name: 'Tesla AI & Autopilot Architecture',
    description: 'End-to-end neural network autonomy, FSD V12+ vision models, Dojo training clusters, and Optimus humanoid developments',
    enabled: true,
    protocol: 'rss',
    connector: 'tesla_ai',
    baseUrl: 'https://www.notateslaapp.com/rss/autopilot',
    authType: 'none',
    categories: ['robotics', 'ai', 'ai-hardware'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Tesla Autopilot Feed',
    region: 'Global',
    country: 'United States'
  },
  spectrum_ieee_robotics: {
    id: 'spectrum_ieee_robotics',
    name: 'IEEE Spectrum Automaton Robotics',
    description: 'World-renowned reporting on experimental robotics, bio-inspired mechanics, bipedal locomotion, and industrial cobots',
    enabled: true,
    protocol: 'rss',
    connector: 'spectrum_ieee_robotics',
    baseUrl: 'https://spectrum.ieee.org/feeds/topic/robotics.rss',
    authType: 'none',
    categories: ['robotics', 'technology', 'research'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'IEEE Spectrum',
    region: 'Global',
    country: 'United States'
  },

  // === 4. QUANTUM COMPUTING & ADVANCED SILICON ===
  quera_computing: {
    id: 'quera_computing',
    name: 'QuEra Neutral Atom Quantum Computing',
    description: 'Fault-tolerant quantum computation using laser-trapped rubidium neutral atoms and reconfigurable qubit arrays',
    enabled: true,
    protocol: 'rss',
    connector: 'quera_computing',
    baseUrl: 'https://www.quera.com/blog/rss.xml',
    authType: 'none',
    categories: ['research', 'technology', 'ai-hardware'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'QuEra Computing',
    region: 'Global',
    country: 'United States'
  },
  rigetti_quantum: {
    id: 'rigetti_quantum',
    name: 'Rigetti Superconducting Quantum Systems',
    description: 'Multi-chip superconducting quantum processors, hybrid classical-quantum algorithms, and quantum cloud services',
    enabled: true,
    protocol: 'rss',
    connector: 'rigetti_quantum',
    baseUrl: 'https://www.rigetti.com/news/rss.xml',
    authType: 'none',
    categories: ['research', 'technology', 'ai-hardware'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Rigetti Computing',
    region: 'Global',
    country: 'United States'
  },
  chips_and_cheese_tech: {
    id: 'chips_and_cheese_tech',
    name: 'Chips and Cheese Microarchitectures',
    description: 'Exhaustive silicon microarchitectural benchmarking, instruction reordering, cache hierarchy analysis, and GPU execution pipelines',
    enabled: true,
    protocol: 'rss',
    connector: 'chips_and_cheese_tech',
    baseUrl: 'https://chipsandcheese.com/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'technology', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Chips and Cheese',
    region: 'Global',
    country: 'United States'
  },
  semiconductor_engineering: {
    id: 'semiconductor_engineering',
    name: 'Semiconductor Engineering (AI Silicon)',
    description: 'Advanced lithography, EUV, GAAFET transistors, chiplets, 2.5D/3D interposers, and High Bandwidth Memory (HBM3e/HBM4)',
    enabled: true,
    protocol: 'rss',
    connector: 'semiconductor_engineering',
    baseUrl: 'https://semiengineering.com/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Semiconductor Engineering',
    region: 'Global',
    country: 'United States'
  },
  semi_wiki: {
    id: 'semi_wiki',
    name: 'SemiWiki Semiconductor Design & EDA',
    description: 'Electronic design automation, wafer fabrication insights, foundry roadmaps (TSMC, Intel, Samsung), and IP blocks',
    enabled: true,
    protocol: 'rss',
    connector: 'semi_wiki',
    baseUrl: 'https://semiwiki.com/feed/',
    authType: 'none',
    categories: ['ai-hardware', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'SemiWiki',
    region: 'Global',
    country: 'United States'
  },

  // === 5. COMPUTATIONAL BIOLOGY & AI HEALTHCARE ===
  biorxiv_compbio: {
    id: 'biorxiv_compbio',
    name: 'bioRxiv Computational Biology Preprints',
    description: 'Open access preprints in algorithmic biology, protein folding, RNA structure prediction, and biological neural models',
    enabled: true,
    protocol: 'rss',
    connector: 'biorxiv_compbio',
    baseUrl: 'https://connect.biorxiv.org/biorxiv_xml.php?subject=computational_biology',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 25,
    timeoutMs: 14000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 50,
    attribution: 'Cold Spring Harbor Laboratory bioRxiv',
    region: 'Global',
    country: 'United States'
  },
  biorxiv_bioinformatics: {
    id: 'biorxiv_bioinformatics',
    name: 'bioRxiv Bioinformatics Algorithms',
    description: 'Genome sequencing analysis, deep learning for variant interpretation, single-cell transcriptomics, and phylogenetics',
    enabled: true,
    protocol: 'rss',
    connector: 'biorxiv_bioinformatics',
    baseUrl: 'https://connect.biorxiv.org/biorxiv_xml.php?subject=bioinformatics',
    authType: 'none',
    categories: ['research', 'ai', 'programming'],
    fetchIntervalMinutes: 25,
    timeoutMs: 14000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 50,
    attribution: 'Cold Spring Harbor Laboratory bioRxiv',
    region: 'Global',
    country: 'United States'
  },
  insilico_medicine: {
    id: 'insilico_medicine',
    name: 'Insilico Medicine Generative AI Biology',
    description: 'End-to-end generative chemistry, Pharma.AI pipeline breakthroughs, novel target discovery, and clinical trial results',
    enabled: true,
    protocol: 'rss',
    connector: 'insilico_medicine',
    baseUrl: 'https://insilico.com/feed',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Insilico Medicine',
    region: 'Global',
    country: 'United States'
  },

  // === 6. CYBERSECURITY, AI SAFETY & EVALUATIONS ===
  cisa_alerts: {
    id: 'cisa_alerts',
    name: 'CISA Real-Time Cybersecurity Bulletins',
    description: 'Official US Cybersecurity & Infrastructure Security Agency alerts on critical zero-days, exploited CVEs, and infrastructure threats',
    enabled: true,
    protocol: 'rss',
    connector: 'cisa_alerts',
    baseUrl: 'https://www.cisa.gov/uscert/ncas/all.xml',
    authType: 'none',
    categories: ['cybersecurity', 'technology'],
    fetchIntervalMinutes: 15,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'CISA (US Department of Homeland Security)',
    region: 'North America',
    country: 'United States'
  },
  metr_research: {
    id: 'metr_research',
    name: 'METR (Model Evaluation & Threat Research)',
    description: 'Evaluating autonomous capabilities, cyber offense risks, self-replication, and dangerous capabilities of frontier AI models',
    enabled: true,
    protocol: 'rss',
    connector: 'metr_research',
    baseUrl: 'https://metr.org/feed.xml',
    authType: 'none',
    categories: ['cybersecurity', 'research', 'ai'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'METR Research',
    region: 'Global',
    country: 'United States'
  },

  // === 7. DEVELOPER PLATFORMS & RUNTIMES ===
  dbt_blog: {
    id: 'dbt_blog',
    name: 'dbt Labs Analytics Engineering & Data Stack',
    description: 'Modular SQL/Python data modeling, semantic layers, data transformations, and LLM orchestration in data warehouses',
    enabled: true,
    protocol: 'rss',
    connector: 'dbt_blog',
    baseUrl: 'https://www.getdbt.com/blog/rss.xml',
    authType: 'none',
    categories: ['developer-tools', 'programming', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'dbt Labs',
    region: 'Global',
    country: 'United States'
  },
  tinygrad_blog: {
    id: 'tinygrad_blog',
    name: 'tinygrad Deep Learning Engine (George Hotz)',
    description: 'Minimalistic, high-performance Python deep learning framework targeting tinybox, AMD, NVIDIA, and Apple Silicon accelerators',
    enabled: true,
    protocol: 'rss',
    connector: 'tinygrad_blog',
    baseUrl: 'https://github.com/tinygrad/tinygrad/commits/master.atom',
    authType: 'none',
    categories: ['open-source-ai', 'programming', 'ai-hardware'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'tinygrad (geohot)',
    region: 'Global',
    country: 'United States'
  },
  simon_willison_weblog: {
    id: 'simon_willison_weblog',
    name: 'Simon Willison’s Weblog (LLMs & Tools)',
    description: 'Hands-on investigations of prompt injection, local LLMs, Datasette, open source AI utilities, and Python engineering',
    enabled: true,
    protocol: 'rss',
    connector: 'simon_willison_weblog',
    baseUrl: 'https://simonwillison.net/atom/everything/',
    authType: 'none',
    categories: ['ai', 'programming', 'open-source-ai'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Simon Willison',
    region: 'Global',
    country: 'United States'
  },
  eugeneyan_applied_ml: {
    id: 'eugeneyan_applied_ml',
    name: 'Eugene Yan (Applied LLMs & Machine Learning)',
    description: 'Design patterns for real-world LLM systems, evals, guardrails, retrieval-augmented generation, and recommender engines',
    enabled: true,
    protocol: 'rss',
    connector: 'eugeneyan_applied_ml',
    baseUrl: 'https://eugeneyan.com/feed.xml',
    authType: 'none',
    categories: ['machine-learning', 'ai-agents', 'programming'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Eugene Yan (Amazon AI)',
    region: 'Global',
    country: 'United States'
  },
  lilian_weng_blog: {
    id: 'lilian_weng_blog',
    name: 'Lil’Log (Lilian Weng AI Safety & Architecture)',
    description: 'Legendary technical literature reviews on diffusion models, agent memory, hallucination reduction, and RLHF from OpenAI VP',
    enabled: true,
    protocol: 'rss',
    connector: 'lilian_weng_blog',
    baseUrl: 'https://lilianweng.github.io/index.xml',
    authType: 'none',
    categories: ['research', 'ai', 'llms'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Lilian Weng',
    region: 'Global',
    country: 'United States'
  },
  chip_huyen_blog: {
    id: 'chip_huyen_blog',
    name: 'Chip Huyen (Machine Learning Engineering)',
    description: 'Foundational writings on AI engineering, real-time ML, LLM evaluation pipelines, and hardware accelerators',
    enabled: true,
    protocol: 'rss',
    connector: 'chip_huyen_blog',
    baseUrl: 'https://huyenchip.com/feed.xml',
    authType: 'none',
    categories: ['machine-learning', 'ai', 'programming'],
    fetchIntervalMinutes: 35,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Chip Huyen',
    region: 'Global',
    country: 'United States'
  },
  the_gradient_pub: {
    id: 'the_gradient_pub',
    name: 'The Gradient AI Journal & Perspectives',
    description: 'In-depth essays, technical interviews, and perspectives on machine learning written by researchers and engineers',
    enabled: true,
    protocol: 'rss',
    connector: 'the_gradient_pub',
    baseUrl: 'https://thegradient.pub/rss/',
    authType: 'none',
    categories: ['research', 'ai', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'The Gradient',
    region: 'Global',
    country: 'United States'
  },
  gary_marcus_sub: {
    id: 'gary_marcus_sub',
    name: 'Marcus on AI (Gary Marcus Critical Dispatches)',
    description: 'Neurosymbolic critique, benchmark evaluations, LLM reliability, safety debates, and AI policy analysis',
    enabled: true,
    protocol: 'rss',
    connector: 'gary_marcus_sub',
    baseUrl: 'https://garymarcus.substack.com/feed',
    authType: 'none',
    categories: ['ai', 'research', 'technology'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Gary Marcus',
    region: 'Global',
    country: 'United States'
  },
  import_ai_newsletter: {
    id: 'import_ai_newsletter',
    name: 'Import AI (Jack Clark / Anthropic)',
    description: 'Weekly intelligence on compute growth, national AI strategies, safety benchmarks, and policy implications',
    enabled: true,
    protocol: 'rss',
    connector: 'import_ai_newsletter',
    baseUrl: 'https://importai.substack.com/feed',
    authType: 'none',
    categories: ['ai', 'technology', 'research'],
    fetchIntervalMinutes: 30,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 60,
    attribution: 'Jack Clark',
    region: 'Global',
    country: 'United States'
  },

  // === 8. HIGH-IMPACT YOUTUBE & VIDEO MEDIA CHANNELS ===
  youtube_ai_explained: {
    id: 'youtube_ai_explained',
    name: 'AI Explained (Paper Teardowns & SOTA Benchmarks)',
    description: 'Deep visual teardowns of state-of-the-art AI papers, benchmark validations, frontier models, and reasoning mechanisms',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_ai_explained',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCNJ1Ymd5yFuUPtn21xtRbbw',
    authType: 'none',
    categories: ['ai', 'research', 'video'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'AI Explained',
    region: 'Global',
    country: 'United Kingdom'
  },
  youtube_wes_roth: {
    id: 'youtube_wes_roth',
    name: 'Wes Roth (Frontier AI & Computing Architecture)',
    description: 'Daily visual breakdowns of autonomous agents, reasoning models, compute clusters, and the march toward AGI',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_wes_roth',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCqcbQf6yw5KzRoDDcZ_wBSw',
    authType: 'none',
    categories: ['ai', 'technology', 'video'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'Wes Roth',
    region: 'Global',
    country: 'United States'
  },
  youtube_matthew_berman: {
    id: 'youtube_matthew_berman',
    name: 'Matthew Berman (Open Source AI & Agent Systems)',
    description: 'Hands-on tutorials testing local LLMs, quantization benchmarks, agent workflows, Ollama, and open-source models',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_matthew_berman',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCaw1OH_Bs57iHSY7jG5yC5g',
    authType: 'none',
    categories: ['open-source-ai', 'ai-agents', 'video'],
    fetchIntervalMinutes: 20,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'Matthew Berman',
    region: 'Global',
    country: 'United States'
  },
  youtube_the_primeagen: {
    id: 'youtube_the_primeagen',
    name: 'ThePrimeagen (Software Architecture & Runtimes)',
    description: 'Deep dives into compiler efficiency, high-performance systems engineering, Vim/Neovim, Go, and developer ergonomics',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_the_primeagen',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC8ENHE5xdFSwx71u3fDH5Xw',
    authType: 'none',
    categories: ['programming', 'developer-tools', 'video'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'ThePrimeagen',
    region: 'Global',
    country: 'United States'
  },
  youtube_sabine_hossenfelder: {
    id: 'youtube_sabine_hossenfelder',
    name: 'Sabine Hossenfelder (Science & Computing Realities)',
    description: 'Critical analysis of quantum hype, fusion claims, semiconductor limits, and the theoretical physics of computation',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_sabine_hossenfelder',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC1yNl2E66ZzKApQdLMimNIg',
    authType: 'none',
    categories: ['research', 'technology', 'video'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'Sabine Hossenfelder',
    region: 'Global',
    country: 'Germany'
  },
  youtube_networkchunk: {
    id: 'youtube_networkchunk',
    name: 'NetworkChuck (Linux, Networking & Cloud Security)',
    description: 'Hands-on masterclasses on Docker, Kubernetes, zero-trust tunnels, Wireshark, cloud automation, and networking',
    enabled: true,
    protocol: 'rss',
    connector: 'youtube_networkchunk',
    baseUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9x0AN7BWHpCDHSm9NiJFJQ',
    authType: 'none',
    categories: ['cybersecurity', 'developer-tools', 'video'],
    fetchIntervalMinutes: 25,
    timeoutMs: 12000,
    maxRetries: 3,
    paginationSupport: false,
    searchSupport: false,
    requiresKey: false,
    rateLimitPerMinute: 40,
    attribution: 'NetworkChuck',
    region: 'Global',
    country: 'United States'
  }
};
